// @ts-nocheck
import { TranslationKey } from './ta';

export const en: Record<TranslationKey, string> = {
  // App General
  appName: 'Niril',
  appNameFull: 'Elvan Niril',
  welcomeBack: 'Welcome back!',
  loading: 'Loading...',
  error: 'Error',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Edit',
  delete: 'Delete',
  add: 'Add',
  search: 'Search...',
  print: 'Print',
  preview: 'Preview',
  actions: 'Actions',
  yes: 'Yes',
  no: 'No',
  selected: 'Selected',
  copyDuplicate: 'Copy / Duplicate',
  connected: 'Connected',
  offlineMode: 'Offline mode',
  connecting: 'Connecting...',

  // Navigation / Sidebar
  home: 'Home',
  invoices: 'Invoices',
  accountingGroup: 'Accounting',
  reportsGroup: 'Reports & GST',
  coolieBill: 'Coolie Bill',
  silksBill: 'Grocery Bill',
  newBill: 'New Bill',
  bills: 'Bills',
  allBills: 'All Bills',
  merchants: 'Merchants',
  inventory: 'Inventory',
  receipts: 'Receipts',
  expenses: 'Expenses',
  purchases: 'Purchases',
  recurring: 'Recurring',
  reports: 'Reports',
  gstReturns: 'GST Returns',
  settings: 'Settings',
  userGuide: 'User Guide',
  notifications: 'Notifications',
  logout: 'Logout',

  // Theme & Language
  darkMode: 'Dark Mode',
  lightMode: 'Light Mode',
  language: 'Language',

  // Forms & Inputs
  name: 'Name',
  mugavari: 'Address',
  oor: 'City',
  tholaipesi: 'Phone',
  email: 'Email',
  date: 'Date',
  description: 'Description',

  // Billing / Invoice
  billNo: 'Bill No',
  invoiceDetails: 'Invoice Details',
  itemsList: 'Items',
  itemName: 'Item Name',
  weight: 'Weight',
  rate: 'Rate',
  price: 'Price',
  amount: 'Amount',
  total: 'Total',
  subTotal: 'Sub Total',
  addAnotherItem: 'Add Row',
  notes: 'Notes',
  terms: 'Terms',
  
  // Merchants
  newMerchant: 'New Merchant',
  merchantName: 'Merchant Name',
  noMerchants: 'No merchants yet',
  deleteMerchantConfirm: 'Are you sure you want to delete this merchant?',

  // Items
  newItem: 'New Item',
  noItems: 'No items yet',
  deleteItemConfirm: 'Are you sure you want to delete this item?',

  // Settings
  appearance: 'Appearance',
  account: 'Account',
  profile: 'Profile',
  security: 'Security',
  dataBackup: 'Data Backup',
  cloudSync: 'Cloud Sync',
  about: 'About',
  businessProfile: 'Business Profile',
  bankDetails: 'Bank Details',
  companyName: 'Company Name',
  accountNo: 'Account No',
  ifscCode: 'IFSC Code',
  kilai: 'Branch',
  
  // Messages
  successSaved: 'Saved successfully!',
  errorSaveFailed: 'Failed to save:',
  noDataAvailable: 'No Data Available',
  // Invoice Form
  billedTo: 'Billed To',
  clientName: 'Client Name',
  billingAddress: 'Billing Address',
  country: 'Country',
  pinCode: 'PIN Code',
  maanilam: 'State',
  gstin: 'GSTIN',
  invoiceDetailsForm: 'Invoice Details',
  invoiceNumber: 'Invoice Number',
  invoiceDate: 'Invoice Date',
  dueDate: 'Due Date',
  placeOfSupply: 'Place of Supply',
  lineItems: 'Line Items',
  pricesIncludeTax: 'Prices include tax',
  hsnSac: 'HSN/SAC',
  qty: 'Qty',
  unit: 'Unit',
  discount: 'Discount',
  cess: 'Cess %',

  // Settings Page
  settingsTitle: 'Settings',
  settingsSubtitle: 'Business profile, branding, integrations & data',
  modulesTitle: 'Modules',
  modulesDesc: 'Turn off the features you don\'t need. They disappear from the sidebar and forms — your data stays untouched.',
  regionTitle: 'Region Preference',
  regionDesc: 'Choose how the app behaves. You can change this any time without losing data.',
  companyDetailsTitle: 'Company Details',
  paymentAccountsTitle: 'Payment Accounts',
  paymentAccountsDesc: 'Multiple bank / UPI accounts per profile. Pick one per invoice in the Customize panel. The ⭐ default account is preselected on new invoices.',
  invoiceNumberFormatTitle: 'Invoice Number Format',
  brandingTitle: 'Branding',
  businessLogo: 'Business Logo',
  signature: 'Signature / Stamp',
  cloudBackupTitle: 'Cloud Backup (Google Drive)',
  cloudBackupDesc: 'Auto-sync your invoices to Google Drive — no coding or API setup needed.',
  exportImportTitle: 'Export & Import Data',
  exportImportDesc: 'Backup your data locally or restore from a previous backup file.',
  resetToDefault: 'Reset to default',

  // Module Groups
  moduleGroup_sales: 'Sales & Invoicing',
  moduleDesc_sales: 'Invoice creation, recurring invoices, payment receipts',
  module_invoicing: 'Tax invoices, proforma, credit notes',
  module_recurring: 'Recurring invoices',
  module_receipts: 'Payment receipts',

  moduleGroup_directory: 'Directory',
  moduleDesc_directory: 'Clients and product catalog',
  module_clients: 'Clients',
  module_inventory: 'Products & Services (inventory)',

  moduleGroup_purchases: 'Purchases & Expenses',
  moduleDesc_purchases: 'Vendor bills, expense tracking, ITC',
  module_expenses: 'Expense tracker',
  module_purchases: 'Purchase bills',
  module_gstr2b: 'GSTR-2B reconciliation (purchase ITC matching)',

  moduleGroup_gst: 'GST & Tax (India)',
  moduleDesc_gst: 'GSTR returns, e-Way Bill, TDS/TCS, HSN summaries',
  module_gstReturns: 'GSTR-1 / GSTR-3B exports + filing guide',
  module_ewayBill: 'E-Way Bill JSON export',
  module_tdsTcs: 'TDS / TCS on invoices',

  moduleGroup_reports: 'Reports',
  moduleDesc_reports: 'Dashboards and financial reports',
  module_dashboard: 'Dashboard',
  module_reports: 'Reports view',

  moduleGroup_integrations: 'Integrations',
  moduleDesc_integrations: 'Cloud backup and payment QR codes',
  module_googleDrive: 'Google Drive backup',
  module_upiQr: 'UPI QR code on invoices',

  // Settings Form
  businessNameLabel: 'Business Name *',
  countryLabel: 'Country',
  mugavariLabel: 'Address',
  oorLabel: 'City / Town',
  emailLabel: 'Email',
  tholaipesiLabel: 'Phone',
  mobileLabel: 'Mobile',

  'PIN Code': 'PIN Code',
  'GSTIN': 'GSTIN',
  'Select maanilam': 'Select State',
  'e.g. Mumbai': 'e.g. Mumbai',

  // Misc Settings
  includeFinancialYear: 'Include Financial Year',
  yesFinYear: 'Yes (2026-27)',

  numberPadding: 'Number Padding',
  digits3: '3 digits (001)',
  digits4: '4 digits (0001)',
  digits5: '5 digits (00001)',
  digits6: '6 digits (000001)',
  saving: 'Saving...',
  saveNumberFormat: 'Save Number Format',
  uploadLogo: 'Upload Logo',
  logoHint: 'PNG or JPG, square or wide (max 500KB)',
  uploadSignature: 'Upload Signature',
  sigHint: 'PNG, JPG (max 500KB)',
  saveProfile: 'Save Profile',
  
  termsTemplatesTitle: 'Terms & Conditions Templates',
  newTemplate: 'New Template',
  termsTemplatesDesc: 'Create reusable templates or pick from ready-made ones below.',
  quickStartTemplate: 'QUICK START — PICK A TEMPLATE FOR YOUR BUSINESS:',
  templateName: 'Template Name',
  templateContent: 'Content (paste your terms here)',

  saveTemplate: 'Save Template',
  noTemplates: 'No templates yet.',

  businessProfilesTitle: 'Business Profiles',
  addNewProfile: 'Add New Profile',
  saveAsProfile: 'Save as Profile',
  businessProfilesDesc1: 'Save multiple business profiles and switch between them instantly. Switching auto-saves your current profile first.',
  businessProfilesDesc2: 'No saved profiles yet. Fill in your business details above and click "Save as Profile".',

  appUpdatesTitle: 'App Updates',
  appUpdatesDesc: 'Check if a newer version is available.',
  checkingUpdate: 'Checking...',
  checkForUpdates: 'Check for Updates',

  dataManagementTitle: 'Data Management',
  dataNoticeText: '<strong>Your data is on this computer only.</strong> Nothing is uploaded to us, our servers, or any third party — not invoices, not clients, not settings. The only time anything leaves your machine is if you explicitly click <em>Save to Drive</em> below (uploads to <strong>your own</strong> Google Drive account). Files live under <code>data/</code> and <code>Saved Invoices/</code> next to the app.',
  dataManagementDesc: 'Choose what to back up or restore — invoices, clients, products, settings, custom units, or just specific parts. Backup files are plain JSON you can keep on a USB drive, OneDrive, or your own Google Drive.',
  exportBackup: 'Export Backup...',
  importBackup: 'Import Backup...',
  
  googleDriveEasyWay: 'Easiest Way — Google Drive for Desktop (Recommended)',


  // Reports page
  reportsSubtitle: 'Overview of your sales revenue and taxes collected',
  filterByLabel: 'Filter By',
  fiscalYearLabel: 'Fiscal Year',
  monthYearLabel: 'Month / Year',
  monthLabel: 'Month',
  yearLabel: 'Year',
  currencyLabel: 'Currency',
  revenueExTax: 'Revenue (ex. Tax)',
  salesSummaryTitle: 'Sales Summary',
  showingCurrencyInvoicesOnly: 'invoices only',
  totalRevenueLabel: 'Total Revenue',
  lessGstCollectedLabel: 'Less: Tax Collected',
  netRevenueLabel: 'Net Revenue',
  monthlySalesTitle: 'Monthly Sales Breakdown',
  revenueCol: 'Revenue',

  // Dashboard
  recentActivity: 'Recent Activity',
  totalItems: 'Total',
  seeAll: 'See All',
  newInvoice: 'New Invoice',
  dashboard: 'Dashboard',
  overviewOfInvoices: 'Overview of your invoices',
  totalInvoiced: 'Total Invoiced',
  taxCollected: 'Tax Collected',
  overdueLabel: 'Overdue',
  
  // Dropdowns
  invoiceModeGoods: 'Goods',
  invoiceModeServices: 'Services',
  invoiceModeMixed: 'Mixed',
  noneLabel: 'None',
  selectLabelGeneric: 'Select',
  langTamil: 'தமிழ் (Tamil)',
  langEnglish: 'English',
  langHindi: 'हिन्दी (Hindi)',
  langTelugu: 'తెలుగు (Telugu)',
  langKannada: 'ಕನ್ನಡ (Kannada)',
  langMalayalam: 'മലയാളം (Malayalam)',
  langMarathi: 'मराठी (Marathi)',
  langGujarati: 'ગુજરાતી (Gujarati)',
  langBengali: 'বাংলা (Bengali)',
  paymentCash: 'Cash',
  paymentUPI: 'UPI',
  paymentBank: 'Bank Transfer',
  paymentCheque: 'Cheque',
  paymentCard: 'Card',
  paymentOther: 'Other',
  outstanding: 'Outstanding',
  invoicesCount: 'Invoices',
  searchClientOrInvoice: 'Search client or invoice...',
  allYears: 'All Years',
  allTypes: 'All Types',
  allStatus: 'All Status',
  noInvoicesYet: 'No invoices yet.',
  noInvoicesMatch: 'No invoices match your filters.',
  createInvoiceBtn: 'Create Invoice',
  dateCol: 'Date',
  invoiceNoCol: 'Invoice No.',
  typeCol: 'Type',
  clientCol: 'Client',
  amountCol: 'Amount',
  paidCol: 'Paid',
  statusCol: 'Status',
  actionsCol: 'Actions',

  // Statuses
  status_unpaid: 'Unpaid',
  status_partial: 'Partial',
  status_paid: 'Paid',
  status_overdue: 'Overdue',

  // New Invoice
  draftOnly: 'Draft Only — Not saved yet',
  downloadPdf: 'Download PDF',
  whatsapp: 'WhatsApp',
  ewayBill: 'E-Way Bill',
  invoiceType: 'Invoice Type',
  customize: 'Customize',
  thisInvoiceIsFor: 'This invoice is for',
  goods: 'Goods',
  services: 'Services',
  mixed: 'Mixed',
  typeClientName: 'Type to search client name or add new',
  egMumbai: 'e.g. Mumbai',
  selectState: 'Select State',
  optionalLabel: 'Optional',
  pdfPreviewHeader: 'PDF Preview — This is how your invoice will look',
  termsAndConditionsLabel: 'Terms & Conditions',

  // Invoice Types
  invoiceTypes_tax_invoice: 'Tax Invoice',
  invoiceTypes_proforma: 'Proforma Invoice',
  invoiceTypes_bill_of_supply: 'Bill of Supply',
  invoiceTypes_composition: 'Composition Invoice',
  invoiceTypes_credit_note: 'Credit Note',
  invoiceTypes_delivery_challan: 'Delivery Challan',
  invoiceDesc_tax_invoice: 'Standard invoice for B2B/B2C sales with tax',
  invoiceDesc_proforma: 'Estimated invoice or quote before actual sale',
  invoiceDesc_bill_of_supply: 'For selling tax-exempt items without charging tax',
  invoiceDesc_composition: 'For businesses under Composition scheme (flat tax)',
  invoiceDesc_credit_note: 'For sales returns or reducing the invoice amount',
  invoiceDesc_delivery_challan: 'For sending items on approval, job work, or branch transfer',
};
