// @ts-nocheck
export const ta = {
  'PIN Code': 'அஞ்சல் குறியீடு',
  'GSTIN': 'GSTIN',
  'Select maanilam': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
  'e.g. Mumbai': 'உ.ம். சென்னை',
  // App General
  appName: 'நிறிள்',
  appNameFull: 'எல்வன் நிறிள்',
  welcomeBack: 'நல்வரவு!',
  loading: 'ஏற்றுகிறது...',
  error: 'பிழை',
  save: 'சேமி',
  cancel: 'ரத்து',
  edit: 'திருத்து',
  delete: 'நீக்கு',
  add: 'சேர்',
  search: 'தேடு...',
  print: 'அச்சிடு',
  preview: 'முன்னோட்டம்',
  actions: 'செயல்கள்',
  yes: 'ஆம்',
  no: 'இல்லை',
  selected: 'தேர்வு',
  copyDuplicate: 'நகலெடு (Copy)',
  connected: 'இணைக்கப்பட்டது',
  offlineMode: 'ஆஃப்லைன்',
  connecting: 'இணைகிறது...',

  // Navigation / Sidebar
  home: 'முகப்பு',
  invoices: 'பட்டியல்கள்',
  accountingGroup: 'கணக்கியல்',
  reportsGroup: 'அறிக்கைகள்',
  coolieBill: 'கூலிப் பட்டியல்',
  silksBill: 'மளிகைப் பட்டியல்',
  newBill: 'புதிய பட்டியல்',
  bills: 'பட்டியல்கள்',
  allBills: 'அனைத்து பட்டியல்கள்',
  merchants: 'வணிகர்கள்',
  inventory: 'பொருள்',
  receipts: 'பற்றுச்சீட்டுகள்',
  expenses: 'செலவுகள்',
  purchases: 'கொள்முதல்',
  recurring: 'தொடர் பட்டியல்கள்',
  reports: 'அறிக்கைகள்',
  gstReturns: 'வரி அறிக்கைகள்',
  settings: 'அமைப்புகள்',
  userGuide: 'கையேடு',
  notifications: 'அறிவிப்புகள்',
  logout: 'வெளியேறு',

  // Theme & Language
  darkMode: 'இருள் நிலை',
  lightMode: 'ஒளி நிலை',
  language: 'மொழி',

  // Forms & Inputs
  name: 'பெயர்',
  mugavari: 'முகவரி',
  oor: 'ஊர்',
  tholaipesi: 'தொலைபேசி',
  email: 'மின்னஞ்சல்',
  date: 'நாள்',
  description: 'விளக்கம்',

  // Billing / Invoice
  billNo: 'பட்டியல் எண்',
  invoiceDetails: 'பட்டியல் விவரங்கள்',
  itemsList: 'பொருட்கள்',
  itemName: 'பொருள் பெயர்',
  weight: 'எடை',
  rate: 'கூலி',
  price: 'விலை',
  amount: 'தொகை',
  total: 'மொத்தம்',
  subTotal: 'கூடுதல்',
  addAnotherItem: 'புதிய வரிசை',
  notes: 'குறிப்புகள்',
  terms: 'நிபந்தனைகள்',
  
  // Merchants
  newMerchant: 'புதிய வணிகர்',
  merchantName: 'வணிகர் பெயர்',
  noMerchants: 'வணிகர்கள் இல்லை',
  deleteMerchantConfirm: 'இந்த வணிகரை உறுதியாக நீக்க வேண்டுமா?',

  // Items
  newItem: 'புதிய பொருள்',
  noItems: 'பொருட்கள் இல்லை',
  deleteItemConfirm: 'இந்த பொருளை உறுதியாக நீக்க வேண்டுமா?',

  // Settings
  appearance: 'தோற்றம்',
  account: 'கணக்கு',
  profile: 'சுயவிவரம்',
  security: 'பாதுகாப்பு',
  dataBackup: 'தரவு காப்பு',
  cloudSync: 'ஒத்திசைவு',
  about: 'பற்றி',
  businessProfile: 'நிறுவன விவரங்கள்',
  bankDetails: 'வங்கி விவரங்கள்',
  companyName: 'நிறுவன பெயர்',
  accountNo: 'கணக்கு எண்',
  ifscCode: 'IFSC குறியீடு',
  kilai: 'கிளை',
  
  // Messages
  successSaved: 'வெற்றிகரமாக சேமிக்கப்பட்டது!',
  errorSaveFailed: 'சேமிப்பதில் தோல்வி:',
  noDataAvailable: 'தகவல் இல்லை',
  // Invoice Form
  billedTo: 'வாடிக்கையாளர்',
  clientName: 'வாடிக்கையாளர் பெயர்',
  billingAddress: 'பட்டியல் முகவரி',
  country: 'நாடு',
  pinCode: 'அஞ்சல் குறியீடு',
  maanilam: 'மாநிலம்',
  gstin: 'GSTIN',
  invoiceDetailsForm: 'பட்டியல் விவரங்கள்',
  invoiceNumber: 'பட்டியல் எண்',
  invoiceDate: 'பட்டியல் தேதி',
  dueDate: 'கடைசி தேதி',
  placeOfSupply: 'வழங்கும் இடம்',
  lineItems: 'பொருட்கள்',
  pricesIncludeTax: 'வரிகள் அடங்கும்',
  hsnSac: 'HSN/SAC',
  qty: 'அளவு',
  unit: 'அலகு',
  discount: 'தள்ளுபடி',
  cess: 'செஸ் %',

  // Settings Page
  settingsTitle: 'அமைப்புகள்',
  settingsSubtitle: 'நிறுவன விவரங்கள், வணிக அடையாளம் & தரவுகள்',
  modulesTitle: 'தொகுதிகள் (Modules)',
  modulesDesc: 'உங்களுக்குத் தேவையில்லாத அம்சங்களை முடக்கலாம்.',
  regionTitle: 'பகுதி முன்னுரிமை',
  regionDesc: 'பயன்பாடு எவ்வாறு செயல்பட வேண்டும் என்பதைத் தேர்ந்தெடுக்கவும்.',
  companyDetailsTitle: 'நிறுவன விவரங்கள்',
  paymentAccountsTitle: 'கட்டணக் கணக்குகள்',
  paymentAccountsDesc: 'ஒரு சுயவிவரத்திற்கு பல வங்கி/UPI கணக்குகள்.',
  invoiceNumberFormatTitle: 'பட்டியல் எண் வடிவம்',
  brandingTitle: 'வணிக அடையாளம்',
  businessLogo: 'நிறுவனத்தின் சின்னம்',
  signature: 'கையொப்பம்',
  cloudBackupTitle: 'கிளவுட் காப்பு (Google Drive)',
  cloudBackupDesc: 'உங்கள் பட்டியல்களை Google Drive உடன் தானாக ஒத்திசைக்கலாம்.',
  exportImportTitle: 'தரவு ஏற்றுமதி & இறக்குமதி',
  exportImportDesc: 'உங்கள் தரவை உள்ளூரில் பாதுகாப்பாக காப்பு எடுக்கலாம்.',
  resetToDefault: 'இயல்புநிலைக்கு மீட்டமை',

  // Module Groups
  moduleGroup_sales: 'விற்பனை & பட்டியல்கள்',
  moduleDesc_sales: 'பட்டியல் உருவாக்கம், தொடர் பட்டியல்கள், கட்டணப் பற்றுச்சீட்டுகள்',
  module_invoicing: 'வரி பட்டியல்கள், மதிப்பீட்டுப் பட்டியல்கள், கடன் குறிப்புகள்',
  module_recurring: 'தொடர் பட்டியல்கள்',
  module_receipts: 'கட்டணப் பற்றுச்சீட்டுகள்',

  moduleGroup_directory: 'அடைவு (Directory)',
  moduleDesc_directory: 'வாடிக்கையாளர்கள் மற்றும் பொருள் பட்டியல்',
  module_clients: 'வாடிக்கையாளர்கள்',
  module_inventory: 'பொருட்கள் & சேவைகள் (கையிருப்பு)',

  moduleGroup_purchases: 'கொள்முதல் & செலவுகள்',
  moduleDesc_purchases: 'விற்பனையாளர் பட்டியல்கள், செலவு கண்காணிப்பு, ITC',
  module_expenses: 'செலவு கண்காணிப்பு',
  module_purchases: 'கொள்முதல் பட்டியல்கள்',
  module_gstr2b: 'GSTR-2B பொருத்தம் (ITC பொருத்துதல்)',

  moduleGroup_gst: 'GST & வரி (இந்தியா)',
  moduleDesc_gst: 'GSTR தாக்கல், e-Way Bill, TDS/TCS, HSN சுருக்கம்',
  module_gstReturns: 'GSTR-1 / GSTR-3B ஏற்றுமதி & வழிகாட்டி',
  module_ewayBill: 'E-Way Bill JSON ஏற்றுமதி',
  module_tdsTcs: 'பட்டியல்களில் TDS / TCS',

  moduleGroup_reports: 'அறிக்கைகள்',
  moduleDesc_reports: 'முகப்பு பலகை மற்றும் நிதி அறிக்கைகள்',
  module_dashboard: 'முகப்பு பலகை',
  module_reports: 'அறிக்கைகள் பார்வை',

  moduleGroup_integrations: 'ஒருங்கிணைப்புகள்',
  moduleDesc_integrations: 'கிளவுட் காப்பு & QR குறியீடுகள்',
  module_googleDrive: 'Google Drive காப்பு',
  module_upiQr: 'பட்டியல்களில் UPI QR குறியீடு',

  // Settings Form
  businessNameLabel: 'நிறுவனத்தின் பெயர் *',
  countryLabel: 'நாடு',
  mugavariLabel: 'முகவரி',
  oorLabel: 'ஊர் / நகரம்',
  emailLabel: 'மின்னஞ்சல்',
  tholaipesiLabel: 'தொலைபேசி',
  mobileLabel: 'கைபேசி',


  // Misc Settings
  includeFinancialYear: 'பொருளாண்டை சேர்க்கவா',
  yesFinYear: 'ஆம் (2026-27)',

  numberPadding: 'எண் இலக்கங்கள் (Number Padding)',
  digits3: '3 இலக்கங்கள் (001)',
  digits4: '4 இலக்கங்கள் (0001)',
  digits5: '5 இலக்கங்கள் (00001)',
  digits6: '6 இலக்கங்கள் (000001)',
  saving: 'சேமிக்கப்படுகிறது...',
  saveNumberFormat: 'எண் வடிவத்தை சேமி',
  uploadLogo: 'சின்னத்தை பதிவேற்று',
  logoHint: 'PNG அல்லது JPG, (அதிகபட்சம் 500KB)',
  uploadSignature: 'கையொப்பத்தை பதிவேற்று',
  sigHint: 'PNG, JPG (அதிகபட்சம் 500KB)',
  saveProfile: 'சுயவிவரத்தை சேமி',
  
  termsTemplatesTitle: 'விதிமுறைகள் & நிபந்தனைகள் வார்ப்புருக்கள்',
  newTemplate: 'புதிய வார்ப்புரு',
  termsTemplatesDesc: 'மீண்டும் பயன்படுத்தக்கூடிய வார்ப்புருக்களை உருவாக்கவும் அல்லது கீழேயுள்ளவற்றிலிருந்து தேர்ந்தெடுக்கவும்.',
  quickStartTemplate: 'விரைவான தொடக்கம் — உங்கள் வணிகத்திற்கான வார்ப்புருவைத் தேர்ந்தெடுக்கவும்:',
  templateName: 'வார்ப்புரு பெயர்',
  templateContent: 'உள்ளடக்கம் (உங்கள் விதிமுறைகளை இங்கே ஒட்டவும்)',

  saveTemplate: 'வார்ப்புருவை சேமி',
  noTemplates: 'இன்னும் வார்ப்புருக்கள் இல்லை.',

  businessProfilesTitle: 'வணிக சுயவிவரங்கள்',
  addNewProfile: 'புதிய சுயவிவரம் சேர்',
  saveAsProfile: 'சுயவிவரமாக சேமி',
  businessProfilesDesc1: 'பல வணிக சுயவிவரங்களைச் சேமித்து, அவற்றை உடனடியாக மாற்றிக் கொள்ளலாம்.',
  businessProfilesDesc2: 'இன்னும் சேமிக்கப்பட்ட சுயவிவரங்கள் இல்லை. உங்கள் வணிக விவரங்களை மேலே பூர்த்தி செய்து "சுயவிவரமாக சேமி" என்பதைக் கிளிக் செய்யவும்.',

  appUpdatesTitle: 'பயன்பாட்டு புதுப்பிப்புகள்',
  appUpdatesDesc: 'புதிய பதிப்பு உள்ளதா என சரிபார்க்கவும்.',
  checkingUpdate: 'சரிபார்க்கப்படுகிறது...',
  checkForUpdates: 'புதுப்பிப்புகளை சரிபார்',

  dataManagementTitle: 'தரவு மேலாண்மை (Data Management)',
  dataNoticeText: '<strong>உங்கள் தரவு இந்தக் கணினியில் மட்டுமே உள்ளது.</strong> எங்களுக்கு, எங்கள் சேவையகங்களுக்கு அல்லது எந்த மூன்றாம் தரப்பினருக்கும் எதுவும் பதிவேற்றப்படவில்லை. நீங்கள் வெளிப்படையாகக் கோரும்போது மட்டுமே தரவு உங்கள் சொந்த Google Drive-க்குச் செல்லும்.',
  dataManagementDesc: 'எதை காப்புப் பிரதி எடுக்க வேண்டும் அல்லது மீட்டெடுக்க வேண்டும் என்பதைத் தேர்வுசெய்க. காப்பு கோப்புகளை USB டிரைவ் அல்லது Google Drive-ல் பாதுகாப்பாக வைக்கலாம்.',
  exportBackup: 'காப்புப் பிரதியை ஏற்றுமதி செய்...',
  importBackup: 'காப்புப் பிரதியை இறக்குமதி செய்...',
  
  googleDriveEasyWay: 'எளிதான வழி — Google Drive for Desktop (பரிந்துரைக்கப்படுகிறது)',




  // Dashboard
  recentActivity: 'நடப்பு வினைகள்',
  totalItems: 'மொத்தம்',
  seeAll: 'யாவும்',
  newInvoice: 'புதிய பட்டியல்',
  dashboard: 'முகப்பு',
  overviewOfInvoices: 'உங்கள் பட்டியல்களின் சுருக்கம்',
  totalInvoiced: 'மொத்த பட்டியல்',
  taxCollected: 'வசூலித்த வரி',
  outstanding: 'நிலுவை',
  invoicesCount: 'பட்டியல்கள்',
  searchClientOrInvoice: 'வாடிக்கையாளர் அல்லது பட்டியலைத் தேடுக...',
  allYears: 'அனைத்து ஆண்டுகளும்',
  allTypes: 'அனைத்து வகைகளும்',
  allStatus: 'அனைத்து நிலைகளும்',
  noInvoicesYet: 'இன்னும் பட்டியல்கள் இல்லை.',
  noInvoicesMatch: 'உங்கள் தேடலுக்குப் பொருத்தமான பட்டியல்கள் இல்லை.',
  createInvoiceBtn: 'பட்டியலை உருவாக்கு',
  dateCol: 'தேதி',
  invoiceNoCol: 'பட்டியல் எண்',
  typeCol: 'வகை',
  clientCol: 'வாடிக்கையாளர்',
  amountCol: 'தொகை',
  paidCol: 'செலுத்தப்பட்டது',
  statusCol: 'நிலை',
  actionsCol: 'செயல்கள்',

  // Statuses
  status_unpaid: 'செலுத்தப்படாதவை',
  status_partial: 'பகுதி செலுத்தியவை',
  status_paid: 'செலுத்தியவை',
  status_overdue: 'காலக்கெடு முடிந்தது',


  // New Invoice
  draftOnly: 'வரைவு மட்டுமே — இன்னும் சேமிக்கப்படவில்லை',
  downloadPdf: 'PDF பதிவிறக்கு',
  whatsapp: 'வாட்ஸ்அப்',
  ewayBill: 'E-Way Bill',
  invoiceType: 'பட்டியல் வகை',
  customize: 'தனிப்பயனாக்கு',
  thisInvoiceIsFor: 'இந்த பட்டியல் இதற்கானது:',
  goods: 'பொருட்கள்',
  services: 'சேவைகள்',
  mixed: 'இரண்டும்',
  typeClientName: 'வாடிக்கையாளர் பெயரைத் தேட அல்லது புதிதாகச் சேர்க்க தட்டச்சு செய்க',
  egMumbai: 'உ.ம். சென்னை',
  selectState: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
  optionalLabel: 'விருப்பத்திற்குரியது',
  pdfPreviewHeader: 'PDF முன்னோட்டம் — உங்கள் பட்டியல் இப்படித்தான் இருக்கும்',
  termsAndConditionsLabel: 'விதிமுறைகள் & நிபந்தனைகள்',

  // Invoice Types
  invoiceTypes_tax_invoice: 'வரிப் பட்டியல் (Tax Invoice)',
  invoiceTypes_proforma: 'மதிப்பீட்டுப் பட்டியல் (Proforma)',
  invoiceTypes_bill_of_supply: 'வழங்கல் சீட்டு (Bill of Supply)',
  invoiceTypes_composition: 'கலவை வரிப் பட்டியல் (Composition)',
  invoiceTypes_credit_note: 'வரவுக் குறிப்பு (Credit Note)',
  invoiceTypes_delivery_challan: 'வழங்கல் சீட்டு (Challan)',
  invoiceDesc_tax_invoice: 'பொருட்கள் விற்பனைக்கான சாதாரண வரிப் பட்டியல்',
  invoiceDesc_proforma: 'விற்பனைக்கு முந்தைய மதிப்பீடு',
  invoiceDesc_bill_of_supply: 'வரி விலக்கு அளிக்கப்பட்ட பொருட்களுக்கான பட்டியல்',
  invoiceDesc_composition: 'காம்போசிஷன் திட்டத்தின் கீழ் உள்ள வணிகங்களுக்கானது',
  invoiceDesc_credit_note: 'விற்பனைத் திருப்பம் அல்லது தொகையைக் குறைக்க',
  invoiceDesc_delivery_challan: 'பொருட்களை வேலைக்கு அல்லது வேறு கிளைக்கு அனுப்ப',
  totalDueLabel: 'செலுத்த வேண்டிய மொத்தத் தொகை',

  // New Invoice Line Items & Extras
  descriptionCol: 'விளக்கம்',
  hsnSacCol: 'HSN/SAC',
  rateCol: 'விகிதம் %',
  addItemBtn: 'பொருளைச் சேர் (Add Item)',
  termsHeading: 'விதிமுறைகள் & நிபந்தனைகள்',
  insertPreset: 'முன்-அமைப்பைச் செருகு (Insert preset)',
  pickBusinessType: '— வணிக வகையைத் தேர்ந்தெடுக்கவும் —',
  indiaSpecificStarter: 'இந்திய வணிகங்களுக்கான மாதிரி வரிகள். தேவைக்கேற்ப திருத்தலாம்.',
  loadSavedTemplate: 'சேமிக்கப்பட்ட வார்ப்புருவை ஏற்று (Load saved template)',
  termsAppearsOnInvoice: 'விதிமுறைகள் (பட்டியலில் தோன்றும் — rich formatting ஆதரவு)',
  privateNote: 'தனிப்பட்ட குறிப்பு (பட்டியலில் தோன்றாது)',
  privateNoteEg: 'உ.ம். வாடிக்கையாளர் 15 நாள் கடன் கேட்டார், ரவியால் பரிந்துரைக்கப்பட்டது...',
  additionalPages: 'கூடுதல் பக்கங்கள் / பிரிவுகள்',
  addSectionBtn: 'பிரிவைச் சேர் (Add Section)',
  addExtraSectionsDesc: 'பட்டியல் அடிக்குறிப்புக்குப் பிறகு தோன்றும் கூடுதல் பிரிவுகளைச் சேர்க்கவும். (HTML உள்ளடக்கத்தை ஒட்டலாம்).',
  noExtraSections: 'கூடுதல் பிரிவுகள் இல்லை. உருவாக்க "பிரிவைச் சேர்" என்பதைக் கிளிக் செய்யவும்.',

  // Clients Page
  clientsTitle: 'வாடிக்கையாளர்கள்',
  clientsSubtitle: 'வாடிக்கையாளர் வாரியான பட்டியல் மற்றும் நிலுவை',
  importCSV: 'CSV ஐ இறக்குமதி செய்',
  addClient: 'வாடிக்கையாளரைச் சேர்',
  newInvoiceBtn: 'புதிய பட்டியல்',
  searchClients: 'வாடிக்கையாளர்களைத் தேட...',
  noClientsFound: 'வாடிக்கையாளர்கள் யாரும் இல்லை.',
  addFirstClient: 'உங்கள் முதல் வாடிக்கையாளரைச் சேர்க்கவும்',
  invoiceCountSingular: 'பட்டியல்',
  totalLabel: 'மொத்தம்',
  paidLabel: 'செலுத்தப்பட்டது',
  overdueLabel: 'காலதாமதம்',
  
  // Dropdowns
  invoiceModeGoods: 'பொருட்கள் (Goods)',
  invoiceModeServices: 'சேவைகள் (Services)',
  invoiceModeMixed: 'இரண்டும் (Mixed)',
  noneLabel: 'இல்லை',
  selectLabelGeneric: 'தேர்ந்தெடு',
  langTamil: 'தமிழ் (Tamil)',
  langEnglish: 'ஆங்கிலம் (English)',
  langHindi: 'இந்தி (Hindi)',
  langTelugu: 'தெலுங்கு (Telugu)',
  langKannada: 'கன்னடம் (Kannada)',
  langMalayalam: 'மலையாளம் (Malayalam)',
  langMarathi: 'மராத்தி (Marathi)',
  langGujarati: 'குஜராத்தி (Gujarati)',
  langBengali: 'வங்காளம் (Bengali)',
  paymentCash: 'பணம்',
  paymentUPI: 'யு.பி.ஐ (UPI)',
  paymentBank: 'வங்கிப் பரிமாற்றம்',
  paymentCheque: 'காசோலை',
  paymentCard: 'கார்டு',
  paymentOther: 'மற்றவை',

  outstandingLabel: 'நிலுவை',
  hideLabel: 'மறை',
  viewLabel: 'காண்பி',
  noInvoicesForClient: 'இந்த வாடிக்கையாளருக்கு இன்னும் பட்டியல்கள் இல்லை.',
  removeSavedClientConfirm: 'இந்த வாடிக்கையாளரை அகற்ற வேண்டுமா?',
  clientRemoved: 'வாடிக்கையாளர் அகற்றப்பட்டார்',
  deleteInvoiceConfirm: 'இந்த பட்டியலை நீக்க வேண்டுமா? இதை மாற்ற இயலாது.',
  invoiceDeleted: 'பட்டியல் நீக்கப்பட்டது',
  failedToDelete: 'நீக்க முடியவில்லை',
  editClientBtn: 'திருத்து',
  deleteClientBtn: 'நீக்கு',
  saveAsClientBtn: 'வாடிக்கையாளராகச் சேமி',
  editClientTitle: 'வாடிக்கையாளரைத் திருத்து',
  addNewClientTitle: 'புதிய வாடிக்கையாளரைச் சேர்',
  clientBusinessName: 'வாடிக்கையாளர் / நிறுவனத்தின் பெயர் *',
  streetAddressPlaceholder: 'தெரு முகவரி, பகுதி',
  cityPlaceholder: 'உ.ம். சென்னை',
  selectLabel: 'தேர்ந்தெடு',
  emailPlaceholder: 'client@example.com',
  phoneLabel: 'தொலைபேசி',
  phonePlaceholder: '+91 98765 43210',
  sezUnitTitle: 'SEZ / Developer — மாநிலத்தைப் பொருட்படுத்தாமல் IGST விதிக்கப்படும் (பிரிவு 16, IGST சட்டம்).',
  updateClientModalBtn: 'புதுப்பி',
  saveClientModalBtn: 'சேமி',
  cancelModalBtn: 'ரத்து',
  

  // Inventory (Porul) Page
  inventoryTitle: 'பொருள்',
  inventorySubtitle: 'உங்கள் பொருட்கள் மற்றும் சேவைகளை நிர்வகிக்கவும்',
  addProductBtn: 'பொருளைச் சேர்',
  searchProducts: 'பெயர் அல்லது HSN மூலம் தேடுக...',
  editProductTitle: 'பொருளைத் திருத்து',
  addProductTitle: 'புதிய பொருளைச் சேர்',
  productNameLabel: 'பொருள் / சேவை பெயர் *',
  productNamePlaceholder: 'உ.ம். இணையதளம் உருவாக்குதல்',
  hsnCodeLabel: 'HSN / SAC குறியீடு',
  hsnCodePlaceholder: 'உ.ம். 998314',
  rateLabel: 'விலை (அடிப்படை விலை)',
  gstPercentLabel: 'GST %',
  unitLabel: 'அலகு (Unit)',
  stockQuantityLabel: 'கையிருப்பு அளவு',
  descriptionLabelOptional: 'விளக்கம் (விரும்பினால்)',
  descriptionPlaceholder: 'சுருக்கமான விளக்கம்...',
  productsAndServices: 'பொருட்கள் & சேவைகள்',
  noProductsYet: 'இன்னும் பொருட்கள் இல்லை. உங்கள் முதல் பொருளைச் சேர்க்கவும்.',
  noProductsMatch: 'உங்கள் தேடலுக்கு எந்தப் பொருளும் பொருந்தவில்லை.',
  outOfStock: 'கையிருப்பு இல்லை',
  productUpdatedToast: 'பொருள் புதுப்பிக்கப்பட்டது',
  productAddedToast: 'பொருள் சேர்க்கப்பட்டது',
  productNameRequiredToast: 'பொருளின் பெயர் அவசியம்',
  deleteProductConfirmMsg: 'இந்தப் பொருளை நீக்க வேண்டுமா? இதை மாற்ற இயலாது.',
  productDeletedToast: 'பொருள் நீக்கப்பட்டது',
  failedToSaveProductToast: 'பொருளைச் சேமிக்க முடியவில்லை',
  failedToLoadProductsToast: 'பொருட்களை ஏற்ற முடியவில்லை',
  emptyCsvWarningToast: 'CSV கோப்பு காலியாக உள்ளது',
  failedToParseCsvToast: 'CSV கோப்பைப் படிக்க முடியவில்லை',
  nameCol: 'பெயர்',
  hsnCol: 'HSN',
  stockCol: 'கையிருப்பு',
  

  // Receipts Page
  receiptsSubtitle: 'வாடிக்கையாளர்களுக்கான கட்டணப் பற்றுச்சீட்டுகளை உருவாக்கவும்',
  newReceiptBtn: 'புதிய பற்றுச்சீட்டு',
  newPaymentReceiptTitle: 'புதிய கட்டணப் பற்றுச்சீட்டு',
  quickSelectUnpaid: 'விரைவான தேர்வு — நிலுவையில் உள்ள பட்டியல்கள்',
  receiptNoLabel: 'பற்றுச்சீட்டு எண்',
  dateLabel: 'தேதி',
  receivedFromLabel: 'பெறப்பட்டது (வாடிக்கையாளர் பெயர்) *',
  amountLabelStar: 'தொகை *',
  paymentModeLabel: 'கட்டண முறை',
  referenceNoLabel: 'பரிவர்த்தனை எண்',
  againstInvoiceLabel: 'எந்தப் பட்டியலுக்கு (Against Invoice)',
  againstInvoicePlaceholder: 'உ.ம். INV/2025-26/0001',
  noteOptionalLabel: 'குறிப்பு (விரும்பினால்)',
  saveReceiptBtn: 'ரசீதைச் சேமி',
  searchReceipts: 'பற்றுச்சீட்டுகளைத் தேட...',
  paymentReceiptsTableTitle: 'கட்டணப் பற்றுச்சீட்டுகள்',
  noReceiptsYet: 'இன்னும் பற்றுச்சீட்டுகள் உருவாக்கப்படவில்லை.',
  noReceiptsMatch: 'உங்கள் தேடலுக்கு எந்தப் பற்றுச்சீட்டும் பொருந்தவில்லை.',
  createReceiptBtn: 'ரசீதை உருவாக்கு',
  againstInvoiceCol: 'எந்தப் பட்டியலுக்கு',
  modeCol: 'கட்டண முறை',
  clientNameRequiredToast: 'வாடிக்கையாளர் பெயர் அவசியம்',
  enterValidAmountToast: 'சரியான தொகையை உள்ளிடவும்',
  receiptSavedToast: 'பற்றுச்சீட்டு சேமிக்கப்பட்டது',
  deleteReceiptConfirmMsg: 'இந்த ரசீதை நீக்க வேண்டுமா?',
  deletedToast: 'நீக்கப்பட்டது',
  

  // Expenses Page
  expensesSubtitle: 'P&L மற்றும் ITC கோரிக்கைகளுக்கான வணிக செலவுகளைக் கண்காணிக்கவும்',
  exportCsvBtn: 'CSV ஏற்றுமதி செய்',
  addExpenseBtn: 'செலவைச் சேர்',
  totalExpensesCard: 'மொத்த செலவுகள்',
  gstPaidCard: 'செலுத்திய GST (ITC)',
  entriesCard: 'பதிவுகள்',
  searchExpenses: 'செலவுகளைத் தேட...',
  allCategoriesFilter: 'அனைத்து பிரிவுகளும்',
  expenseRecordsTable: 'செலவு பதிவுகள்',
  noExpensesYet: 'இன்னும் செலவுகள் பதிவு செய்யப்படவில்லை.',
  noExpensesMatch: 'உங்கள் வடிகட்டல்களுக்கு எந்த செலவும் பொருந்தவில்லை.',
  editExpenseTitle: 'செலவைத் திருத்து',
  addExpenseTitle: 'செலவைச் சேர்',
  dateLabelStar: 'தேதி *',
  categoryLabel: 'பிரிவு (Category)',
  descriptionLabelStar: 'விளக்கம் *',
  descriptionPlaceholderExp: 'உ.ம். இணையதளப் பராமரிப்பு - ஏப்ரல்',
  amountGstLabelStar: 'தொகை (GST உட்பட) *',
  gstPercentItcLabel: 'GST % (ITC-க்காக)',
  vendorNameLabel: 'விற்பனையாளர் பெயர்',
  vendorNameOptional: 'விருப்பத்திற்குரியது',
  vendorGstinLabel: 'விற்பனையாளர் GSTIN',
  vendorGstinHint: 'ITC கோரிக்கைக்கு',
  invoiceBillNoLabel: 'பட்டியல் எண்',
  descriptionRequiredToast: 'விளக்கம் அவசியம்',
  enterValidAmountToastExp: 'சரியான தொகையை உள்ளிடவும்',
  expenseUpdatedToast: 'செலவு புதுப்பிக்கப்பட்டது',
  expenseAddedToast: 'செலவு சேர்க்கப்பட்டது',
  failedToSaveExpenseToast: 'செலவைச் சேமிக்க முடியவில்லை',
  deleteExpenseConfirmMsg: 'இந்தச் செலவை நீக்க வேண்டுமா?',
  expenseDeletedToast: 'செலவு நீக்கப்பட்டது',
  noExpensesToExportToast: 'ஏற்றுமதி செய்ய எந்த செலவும் இல்லை',
  expensesCsvDownloadedToast: 'செலவுகள் CSV பதிவிறக்கப்பட்டது',
  gstCol: 'GST',
  vendorCol: 'விற்பனையாளர்',
  

  // Purchases Page
  purchasesSubtitle: 'GSTR-3B இல் ITC கோருவதற்கு சப்ளையர் பில்களைக் கண்காணிக்கவும்',
  addPurchaseBtn: 'கொள்முதலைச் சேர்',
  totalPurchasesCard: 'மொத்த கொள்முதல்',
  gstItcEligibleCard: 'GST (ITC தகுதியுடையது)',
  searchSupplierInvoice: 'சப்ளையர், பில் தேட...',
  purchaseRecordsTable: 'கொள்முதல் பதிவுகள்',
  noPurchaseBillsYet: 'இன்னும் கொள்முதல் பட்டியல்கள் பதிவு செய்யப்படவில்லை.',
  noPurchasesMatch: 'உங்கள் வடிகட்டல்களுக்கு எந்த கொள்முதலும் பொருந்தவில்லை.',
  editPurchaseBillTitle: 'கொள்முதல் பட்டியலைத் திருத்து',
  addPurchaseBillTitle: 'கொள்முதல் பட்டியலைச் சேர்',
  paymentStatusLabel: 'பணம் செலுத்தும் நிலை',
  supplierNameLabel: 'சப்ளையர் பெயர் *',
  supplierNamePlaceholder: 'விற்பனையாளர் / சப்ளையர் பெயர்',
  supplierGstinLabel: 'சப்ளையர் GSTIN',
  supplierGstinPlaceholder: '15-இலக்க GSTIN',
  invoiceNumberLabel: 'பட்டியல் எண் (Invoice No) *',
  invoiceNumberPlaceholder: 'சப்ளையர் பட்டியல் எண்',
  interstatePurchaseLabel: 'மாநிலங்களுக்கு இடையேயான கொள்முதல்',
  interstatePurchaseDesc: 'சப்ளையர் IGST வசூலித்துள்ளார் (வேறு மாநிலம்)',
  interstatePurchaseTip: 'CGST + SGST-க்கு பதிலாக GSTR-3B இல் ITC-ஐ IGST-க்கு மாற்றுகிறது. குறிப்பு: சப்ளையர் GSTIN இன் முதல் 2 இலக்கங்கள் = அவர்களின் மாநிலக் குறியீடு.',
  itemsTitle: 'பொருட்கள்',
  qtyCol: 'அளவு',
  taxPercentCol: 'வரி %',
  taxableLabelText: 'வரிக்குட்பட்டது:',
  taxLabelText: 'வரி:',
  totalLabelText: 'மொத்தம்:',
  supplierNameRequiredToast: 'சப்ளையர் பெயர் அவசியம்',
  invoiceNumberRequiredToast: 'பட்டியல் எண் அவசியம்',
  purchaseUpdatedToast: 'கொள்முதல் புதுப்பிக்கப்பட்டது',
  purchaseAddedToast: 'கொள்முதல் சேர்க்கப்பட்டது',
  failedToSavePurchaseToast: 'கொள்முதலைச் சேமிக்க முடியவில்லை',
  failedToLoadPurchasesToast: 'கொள்முதலை ஏற்ற முடியவில்லை',
  deletePurchaseConfirmMsg: 'இந்த கொள்முதல் பட்டியலை நீக்க வேண்டுமா?',
  purchaseDeletedToast: 'கொள்முதல் நீக்கப்பட்டது',
  noPurchasesToExportToast: 'ஏற்றுமதி செய்ய எந்த கொள்முதலும் இல்லை',
  purchasesCsvDownloadedToast: 'கொள்முதல் CSV பதிவிறக்கப்பட்டது',
  supplierCol: 'சப்ளையர்',
  gstinCol: 'GSTIN',
  taxableCol: 'வரிக்குட்பட்டது',
  

  // Recurring Invoices Page
  recurringInvoicesSubtitle: 'நிலையான வாடிக்கையாளர்களுக்கான பட்டியல்களை தானியங்கியாக உருவாக்குங்கள்',
  newTemplateBtn: 'புதிய வார்ப்புரு',
  dueForGeneration: 'உருவாக்குவதற்கான பட்டியல்கள்',
  editTemplateTitle: 'வார்ப்புருவைத் திருத்து',
  newRecurringInvoiceTitle: 'புதிய தொடர் பட்டியல்',
  quickSelectClient: 'வாடிக்கையாளரைத் விரைவாகத் தேர்ந்தெடு',
  frequencyLabel: 'நிகழ்வெண் (Frequency)',
  nextDueDateLabel: 'அடுத்த தேதி',
  invoiceTypeLabel: 'பட்டியல் வகை',
  lineItemsTitle: 'பொருட்கள்',
  recurringTemplatesTable: 'தொடர் வார்ப்புருக்கள்',
  noRecurringYet: 'இன்னும் தொடர் பட்டியல்கள் அமைக்கப்படவில்லை.',
  createTemplateBtn: 'வார்ப்புருவை உருவாக்கு',
  frequencyCol: 'நிகழ்வெண்',
  nextDueCol: 'அடுத்த தேதி',
  addAtLeastOneItemToast: 'விளக்கம் மற்றும் விலையுடன் குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
  templateUpdatedToast: 'வார்ப்புரு புதுப்பிக்கப்பட்டது',
  recurringCreatedToast: 'தொடர் பட்டியல் உருவாக்கப்பட்டது',
  deleteTemplateConfirmMsg: 'இந்தத் தொடர் பட்டியல் வார்ப்புருவை நீக்க வேண்டுமா?',
  pausedToast: 'இடைநிறுத்தப்பட்டது',
  activatedToast: 'செயல்படுத்தப்பட்டது',
  failedToGenerateToast: 'உருவாக்க முடியவில்லை:',
  invoiceGeneratedFor: 'இவருக்காக பட்டியல் உருவாக்கப்பட்டது:',
  freqWeekly: 'வாரம்',
  freqMonthly: 'மாதம்',
  freqQuarterly: 'காலாண்டு',
  freqYearly: 'ஆண்டு',
  statusActive: 'செயலில்',
  statusPaused: 'இடைநிறுத்தம்',
  generateNowTooltip: 'இப்போதே உருவாக்கு',
  pauseTooltip: 'இடைநிறுத்து',
  activateTooltip: 'செயல்படுத்து',
  

  // Reports Page
  reportsSubtitle: 'நிதி அறிக்கைகள் மற்றும் பெற வேண்டியவைகளின் பகுப்பாய்வு',
  profitAndLossTab: 'வருவாய் & இழப்பு',
  outstandingAndAgingTab: 'நிலுவையில் உள்ளவை & பழமை',
  filterByLabel: 'வடிகட்டி',
  fiscalYearLabel: 'பொருளாண்டு (Fiscal Year)',
  monthYearLabel: 'மாதம் / ஆண்டு',
  monthLabel: 'மாதம்',
  yearLabel: 'ஆண்டு',
  currencyLabel: 'நாணயம்',
  revenueExTax: 'வருவாய் (வரி தவிர்த்து)',
  expensesExGst: 'செலவுகள் (GST தவிர்த்து)',
  netProfitLabel: 'நிகர ஈட்டம்',
  netLossLabel: 'நிகர இழப்பு',
  marginLabel: 'ஈட்ட விகிதம் (Margin)',
  plStatementTitle: 'ஈட்ட இழப்பு அறிக்கை',
  showingCurrencyInvoicesOnly: 'பட்டியல்களை மட்டுமே காட்டுகிறது',
  totalRevenueLabel: 'மொத்த வருவாய்',
  lessGstCollectedLabel: 'கழிக்க: வசூலிக்கப்பட்ட GST',
  netRevenueLabel: 'நிகர வருவாய்',
  totalExpensesLabel: 'மொத்த செலவுகள்',
  lessGstOnExpensesLabel: 'கழிக்க: செலவுகள் மீதான GST (ITC)',
  netExpensesLabel: 'நிகர செலவுகள்',
  monthlyBreakdownTitle: 'திங்கள் அறிக்கை',
  revenueCol: 'வருவாய்',
  expensesCol: 'செலவுகள்',
  profitLossCol: 'ஈட்டம்/இழப்பு',
  totalOutstandingLabel: 'மொத்த நிலுவை',
  current0to30d: 'நடப்பு (0-30 நாட்கள்)',
  days31to60: '31-60 நாட்கள்',
  days61to90: '61-90 நாட்கள்',
  days90plus: '90+ நாட்கள்',
  filterByClientName: 'வாடிக்கையாளர் பெயர் மூலம் வடிகட்டவும்...',
  outstandingReceivablesTitle: 'நிலுவையில் உள்ள பெற வேண்டியவைகள்',
  noOutstandingFound: 'நிலுவையில் உள்ள பெற வேண்டியவைகள் எதுவும் காணப்படவில்லை.',
  dueDateCol: 'கெடு தேதி',
  outstandingCol: 'நிலுவை',
  daysOverdueCol: 'காலதாமதமான நாட்கள்',
  currentStatus: 'நடப்பு',
  january: 'ஜனவரி',
  february: 'பிப்ரவரி',
  march: 'மார்ச்',
  april: 'ஏப்ரல்',
  may: 'மே',
  june: 'ஜூன்',
  july: 'ஜூலை',
  august: 'ஆகஸ்ட்',
  september: 'செப்டம்பர்',
  october: 'அக்டோபர்',
  november: 'நவம்பர்',
  december: 'டிசம்பர்',
  

  // GST Returns Page
  gstReturnsTitle: 'GST அறிக்கைகள்',
  gstReturnsSubtitle: 'GST அறிக்கைகள் மற்றும் தாக்கல் நிலையை நிர்வகிக்கவும்',
  monthlyTab: 'திங்கள் தோறும்',
  quarterlyTab: 'காலாண்டு',
  r1Pending: 'R1 நிலுவை',
  b3Pending: '3B நிலுவை',
  gstPortalBtn: 'GST தளம்',
  gstinNotSet: 'உங்கள் வணிக GSTIN அமைக்கப்படவில்லை. அதைச் சேர்க்க அமைப்புகள் → நிறுவன விவரங்களுக்குச் செல்லவும்.',
  invoicesCountLabel: 'பட்டியல்கள்',
  taxableLabel: 'வரிக்குட்பட்டது',
  taxLabel: 'வரி',
  netPayableLabel: 'நிகர செலுத்த வேண்டியவை',
  gstr1Tab: 'GSTR-1',
  gstr3bTab: 'GSTR-3B',
  gstr2bReconTab: 'GSTR-2B ஒப்பீடு',
  tdsTcsTab: 'TDS / TCS அறிக்கை',
  filingGuideTab: 'தாக்கல் வழிகாட்டி',
  jsonExportBtn: 'JSON ஏற்றுமதி',
  docsBtn: 'ஆவணங்கள்',
  markFiledBtn: 'தாக்கல் செய்யப்பட்டதாகக் குறி',
  b2bSalesTable: 'B2B விற்பனை — அட்டவணை 4A',
  b2cSalesTable: 'B2C விற்பனை — அட்டவணை 7',
  hsnSummaryTable: 'HSN சுருக்கம் — அட்டவணை 12',
  docSummaryTable: 'ஆவண சுருக்கம் — அட்டவணை 13',
  gstr1SummaryTotals: 'GSTR-1 சுருக்க மொத்தங்கள்',
  noB2bInvoices: 'இந்த காலத்திற்கு B2B பட்டியல்கள் எதுவும் இல்லை.',
  noB2cInvoices: 'இந்த காலத்திற்கு B2C பட்டியல்கள் எதுவும் இல்லை.',
  cgstCol: 'CGST',
  sgstCol: 'SGST',
  igstCol: 'IGST',
  totalCol: 'மொத்தம்',
  b2cTotal: 'B2C மொத்தம்',
  totalTaxCol: 'மொத்த வரி',
  docTypeCol: 'ஆவண வகை',
  fromCol: 'இருந்து',
  toCol: 'வரை',
  totalIssuedCol: 'மொத்தம் வழங்கப்பட்டது',
  categoryCol: 'வகை',
  grandTotal: 'பெரு மொத்தம்',
  b2bSalesCategory: 'B2B விற்பனை',
  b2cSalesCategory: 'B2C விற்பனை',
  invoiceWord: 'பட்டியல்',
  invoicesWord: 'பட்டியல்கள்',
  codeWord: 'குறியீடு',
  codesWord: 'குறியீடுகள்',
  

  // Notifications
  notificationsTitle: 'அறிவிப்புகள்',
  allClearNotif: 'எல்லாம் சரி ✨ — தற்போது உங்கள் கவனம் தேவைப்படும் எதுவும் இல்லை.',
  recurringAutoFireNotif: 'இன்று தானியங்கியாக உருவாக்கப்பட்ட தொடர் பட்டியல்கள்',
  checkDashboardForNewBills: 'புதிய பட்டியல்களுக்கு முகப்பைப் பார்க்கவும் · தேவைப்பட்டால் PDF பதிவிறக்கவும்',
  overdueInvoicesNotif: 'காலதாமதமான பட்டியல்கள்',
  moreWord: 'மேலும்',
  dueIn3DaysNotif: 'அடுத்த 3 நாட்களில் கெடு தேதி கொண்ட பட்டியல்கள்',
  gstFilingsDueNotif: 'அடுத்த 10 நாட்களில் GST தாக்கல் நிலுவையில் உள்ளன',
  todayWord: 'இன்று',
  lowStockNotif: 'இருப்பு குறைவாக உள்ள பொருட்கள்',
  leftWord: 'மீதம்',
  
};

export type TranslationKey = keyof typeof ta;
