package com.elvan.noolachu.localization.language_keys

import com.elvan.noolachu.localization.K

/**
 * English translations 1:1 matching Flutter's en.dart.
 */
val en: Map<String, String> = mapOf(
    K.aakku to "Make",
    K.aangilam to "en",
    K.adaiyaalam to "Identifier",
    K.aetrugiradhu to "Loading...",
    K.agalamaanaOavuruMattum to "Wide Logo Only",
    K.agalamaanaoavuru to "Vertical / Wide Logo",
    K.alaveeduMurai to "Measurement Method",
    K.alavu to "Quantity",
    K.alavuVagai to "Measure Type",
    K.aluvalkaiyoppam to "Authorized Signatory Name",
    K.anjalKuriyeedu to "Pincode",
    K.appPeyar to "Elvan Niril",
    K.arikkai to "Report",
    K.arikkaigal to "Reports",
    K.arugilSeyalgal to "Recent Activity",
    K.attai to "Card",
    K.azhikkiradhu to "Erasing...",
    K.azhippuvetri to "App data erased.",
    K.chaedhaaram to "Setharam",
    K.chaedhaaramGiraam to "Wastage",
    K.chaemikkaadhaVaraivu to "Unsaved draft. Restore?",
    K.chaemikkappadugiradhu to "Backing up...",
    K.chaemippuNiluvai to "Pending Save",
    K.chaemippuvetri to "Saved successfully",
    K.chaemiththaTharavugal to "Saved Details",
    K.cheyaliPatri to "About App",
    K.cheyaliPatriMaadhiri to "About App (Dummy)",
    K.cheyalipadhippu to "App version and data",
    K.cheyalithTharavaiAzhi to "Erase App Data",
    K.cheyaliyilirundhuVeliyaeravum to "Logout from the application.",
    K.chinnathinVadivam to "Bill Header Style",
    K.chiriyaOavuruPeyar to "Small Logo + Company Name",
    K.chuttruOppu to "Round Off",
    K.edai to "Weight",
    K.elvanNiril to "Elvan Niril",
    K.elvanParthasarathy to "Elvan Parthasarathy",
    K.elvanPatriMaelumAriga to "Learn more about Elvan",
    K.en to "English",
    K.endhachCheyalmurai to "Which workspace?",
    K.english to "English",
    K.ifscKaattu to "Show IFSC",
    K.ifscKuriyeedu to "IFSC Code",
    K.india to "India",
    K.irudhiPeyar to "Last Name",
    K.irulNilai to "Dark Mode",
    K.kaasoalai to "Cheque",
    K.kaiyaalu to "Manage",
    K.kaiyoppam to "Signature / Stamp",
    K.kanakkuEn to "Account Number",
    K.kanakkuKuriyeedu to "A/C No",
    K.kattanaPeyar to "Charge Name",
    K.kilai to "Branch",
    K.kilaipPeyar to "Branch Name",
    K.koriyar to "Courier",
    K.koriyarKattanam to "Courier (₹)",
    K.kurippu to "Remarks",
    K.kurugiyaNiruvanaPeyar to "Short Company Name",
    K.maanilam to "State",
    K.maanilamThaedu to "Search state...",
    K.maanilamThaerodhu to "Select State",
    K.maatru to "Change",
    K.maatruPaesiEn to "Mobile",
    K.maavattam to "District",
    K.meendumThaedu to "Scan Again",
    K.meeteduppuVetri to "Restored successfully",
    K.meetkavum to "Recover",
    K.meetpagam to "Recycle Bin",
    K.meetpagam30Naal to "Items in the recycle bin will be automatically deleted after 30 days",
    K.meetpagamKaaliyanadhu to "Recycle bin is empty",
    K.meetteduppuvetri to "Data restored successfully!",
    K.minnanjal to "Email",
    K.minnanjalMugavari to "Email Address",
    K.minnanjalaiUllidavum to "Enter your email",
    K.minnanjalaiUrudhiseiga to "Confirm Email",
    K.mothaEdai to "Total Weight",
    K.motham to "Total",
    K.mothangal to "Totals",
    K.mudhalPeyar to "First Name",
    K.mudindhadhu to "Done",
    K.mugappu to "Home",
    K.mugavari to "Address",
    K.mugavaritharavugal to "Company address details",
    K.munthogai to "Advance",
    K.munvaraivu to "Proforma",
    K.naadu to "Country",
    K.niraagari to "Dismiss",
    K.nirandharaAzhippu to "Delete Permanently",
    K.niril to "Niril",
    K.nirilthodanga to "Tap \"Get Started\" to continue with Niril.",
    K.niruvanam to "Company",
    K.niruvanathTharavu to "Company Detail",
    K.niruvanangal to "Companies",
    K.niruvanathinOavuru to "Company Logo",
    K.niruvanathinPeyar to "Company Name",
    K.niruvanaththaithThaernhedu to "Select Company",
    K.oliNilai to "Light Mode",
    K.olirIrulThaaniyangu to "Light mode, Dark mode, Auto",
    K.oodhaa to "Violet",
    K.oor to "City",
    K.paadhugaappu to "Security",
    K.pachai to "Green",
    K.padammoolam to "Select Image Source",
    K.padhivaetru to "Upload",
    K.paesiEn to "Phone",
    K.paesiEnkal to "Phone Numbers",
    K.payanar to "User",
    K.payanarVilakkam to "This name will appear on the home screen greeting.",
    K.payanpaduthiyaChaemippu to "Storage Used",
    K.pazhaiyaTharavaiMeettedukkavaa to "Your previous data was found. Would you like to restore it?",
    K.pazhaiyaTharavuKidaikkiradhu to "Old data available",
    K.pdfThoatram to "PDF Theme",
    K.perumMotham to "Grand Total",
    K.perunar to "Billed To",
    K.peyarEarkanavaeUlladhu to "This name already exists.",
    K.peyaraiUlliduga to "Enter name",
    K.pira to "Other",
    K.piraVarivuChaer to "Add Other Charges",
    K.pirandhaThaedhi to "Date of Birth",
    K.pudhiyaAakkam to "Create",
    K.pudhiyaChaerkkai to "Add New",
    K.pugaippadakKaruvi to "Camera",
    K.pugaippadathThoguppu to "Gallery",
    K.ta to "Tamil",
    K.tamil to "Tamil",
    K.tamilLatin to "Thamizh Latin",
    K.thaaniyangki to "Auto-generated",
    K.thaaniyangkiUruvaam to "Auto-generated on save",
    K.thaeduga to "Search...",
    K.thaerndhedu to "Select",
    K.thallupadiChurukkam to "Disc",
    K.thamizh to "ta",
    K.thamizhAangilamThaaniyangu to "Tamil, English, Auto",
    K.tharavaiMeettedukkiradhu to "Restoring data...",
    K.tharavaiazhi to "Permanently erase data.",
    K.tharavugalChaemippuVetri to "Details saved successfully",
    K.tharavugalaiUlliduga to "Enter Company Details",
    K.tharavugalaiUruvaakkuUruvaakkunar to "Seed App (Dev)",
    K.tharpoadhaiyaNiruvanam to "Active Company",
    K.thirai to "Display",
    K.thodarpuVari to "Contact & Tax",
    K.thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum to "Amount must be greater than 0",
    K.thogaiVinmeen to "Amount *",
    K.tholaipaesi to "Phone",
    K.ulmotham to "Subtotal",
    K.ungalCheyalmuraiyaithThaerndhedukkavum to "Select your workspace",
    K.uruvaakkunarTharavugalaiAzhi to "Dev: Erase",
    K.uruvaakkunarTharavugalaiUruvaakku to "Dev: Seed",
    K.vaangunarPeyarThaedu to "Client Name",
    K.vaangunarTharavugal to "Business Details",
    K.vanakkam to "Vanakkam!",
    K.varaivu to "Draft",
    K.varaivuMeetka to "Restore draft?",
    K.variThirattiyavai to "Tax Collected",
    K.vazhangalIdam to "Place of Supply",
    K.velinaadMugavari to "Full Address",
    K.veliyaeraVaendumaa to "Sign Out?",
    K.veliyaeru to "Logout",
    K.veliyaerugiradhu to "Signing out...",
    K.veliyaetramvetri to "Signed out successfully",
    K.vidupattaPulangalaiNirappavum to "Please fill in all fields.",
    K.vilai to "Selling Rate",
    K.vilaiMatrumVari to "Pricing & Tax",
    K.vilaiVeedham to "Rate",
    K.cheyaliyaiAnugaUlnuzhaiyavum to "Login to access your app",
    K.kadavuchol to "Password",
    K.kadavuchollaiUllidavum to "Please enter your password",
    K.nirilirkuNalvaravu to "Welcome to Niril",
    K.niruvanaThannuru to "Company Profile",
    K.niruvanamThaerodhu to "Select a company profile",
    K.perumalavu5thannuru to "Maximum 5 profiles allowed",
    K.pudhiyaThannuruChaer to "Add New Profile",
    K.pudhiyaThannuruvaiUruvaakku to "Create New Profile",
    K.thannuruChaemikkappattadhu to "Profile saved!",
    K.thannuruNeekkappattadhu to "Profile deleted",
    K.thannurukkalIllai to "No saved profiles yet",
    K.thannuruvaiMutrilumNeekkavaa to "Permanently delete this company profile?",
    K.ulnuzhaiga to "Sign In",
    K.anaithaiyumTheriPtn to "Select All",
    K.anaiththaiyumPaarPtn to "See All",
    K.azhikka to "Clear",
    K.chaemiPtn to "Save",
    K.chaer to "Add",
    K.chaerPtn to "Add",
    K.chariPtn to "OK",
    K.kaappuCheiPtn to "Backup Now",
    K.kaividuPtn to "Cancel",
    K.maatriyamai to "Edit",
    K.meeteduppuCheiPtn to "Restore",
    K.meetteduPtn to "Restore Data",
    K.neekkuPtn to "Delete",
    K.orunginaiCheyaliPtn to "Sync App",
    K.payanarTharavugalaiMaetriduPtn to "Save",
    K.porulaichChaerPtn to "Add Product",
    K.pudhiyaPatrucheettuPtn to "New Receipt",
    K.pudhiyaPattiyalPtn to "New Invoice",
    K.pudhiyadhaagaThodanguPtn to "Start Fresh",
    K.purakkaniPtn to "Discard",
    K.thanipPayanPtn to "Custom",
    K.tharavaiAzhiPtn to "Erase Data",
    K.thodangugaPtn to "Get Started",
    K.thodarPtn to "Continue",
    K.thodaravum to "Continue",
    K.uruvaakkuPtn to "Create",
    K.veliyaeruPtn to "Sign Out",
    K.adaimozhi to "Tagline",
    K.amaippugal to "Settings",
    K.chaemippu to "Database",
    K.chaemippuMatrumKaappu to "Storage & Backup",
    K.cheyaliAmaippugal to "App Settings",
    K.cheyaliMozhi to "App Language",
    K.idhuvuraiKaappuIllai to "No Backup Yet",
    K.irandaamMozhi to "Secondary Language",
    K.irumozhiMurai to "Bilingual Mode",
    K.kaappu to "Backup",
    K.kaapputhTharavuIllai to "No backup found, starting fresh.",
    K.kaapputhTharavuKidaithadhu to "Backup found!",
    K.kaapputhTharavuThaedal to "Checking for backups...",
    K.kadaisiThaaniyakkaKaappu to "Last Auto-Backup",
    K.language to "Language",
    K.mozhiThaervu to "Select Language",
    K.mudhanmaiMozhi to "Primary Language",
    K.niruvanaAmaippugal to "Company Settings",
    K.orunginaiCheyaliVilakkam to "Sync recent changes.",
    K.orunginaikkappattadhu to "Synced!",
    K.orunginaikkiRadhu to "Syncing...",
    K.payanarAmaippugal to "User Settings",
    K.pilVadivamaippuViruppangal to "PDF styling options",
    K.thaaniyangiAmaippu to "System Auto",
    K.thaekkagathaiazhi to "Sync, Logout, Clear Data",
    K.tharavuKaappu to "Backup Database",
    K.tharavuKaappuChei to "Backup Data",
    K.tharavuchaemippuvetri to "Backup successfully saved to Documents.",
    K.tharavuthalam to "Database",
    K.tharavuthalangalKaappaikKaiyaalu to "Manage databases and backups",
    K.ungalTharavaiChaemikkavum to "Manually update your backup file.",
    K.viruppaMozhiThaervu to "Choose your preferred language",
    K.azhikkappattaPorulgal to "Deleted Products",
    K.azhikkappattaVaangunargal to "Deleted Customers",
    K.hsnSacKuriyeedu to "HSN/SAC Code",
    K.kuriaindhOruPorul to "Add at least one product",
    K.menporulVadivaalar to "Software Designer",
    K.menporulVadivaalarPatri to "About Developer",
    K.menporulVadivaalarPatriMaadhiri to "About Developer (Dummy)",
    K.pattiyalEnVaangunar to "Invoice No / Customer...",
    K.porul to "Product",
    K.porulAzhikkappattadhu to "Product deleted",
    K.porulChaemikkappattadhu to "Product saved successfully",
    K.porulPeyarThaevai to "Product name is required",
    K.porulTharavugal to "Product Details",
    K.porulaiChaerkkavum to "Add your first product",
    K.porulgalIllai to "No products yet",
    K.porutkal to "Products",
    K.vaangunar to "Customer",
    K.vaangunarAzhikkappattadhu to "Customer deleted",
    K.vaangunarChaemikkappattadhu to "Customer saved successfully",
    K.vaangunarPeyar to "Customer Name",
    K.vaangunarPeyarThaevai to "Customer name is required",
    K.vaangunaraiChaerkkavum to "Add your first customer to get started",
    K.vaangunaraiThaerodhu to "Select a customer",
    K.vaangunaraichChaer to "Add Customer",
    K.vaangunargal to "Customers",
    K.vaangunargalIllai to "No customers yet",
    K.ahimsaiPattu to "Ahimsa Silk",
    K.ahimsaiPattuThogai to "Ahimsa Silk (\\u20b9)",
    K.endhapPattiyalukku to "For which invoice?",
    K.gstVeedham to "GST Rate %",
    K.gstin to "GSTIN",
    K.gstinTavaru to "Invalid GSTIN format",
    K.gstinVariAdaiyaalaEn to "GSTIN / Tax ID",
    K.gstpattiyalukku to "Used for regular GST invoices.",
    K.gstpirippugal to "Show GST splits in table",
    K.kooliMugappupPakkam to "Coolie Home Page",
    K.kooliNiruvanaAdaiyaalangal to "Coolie company identifiers",
    K.kooliNiruvanaPeyar to "Coolie Company Name",
    K.kooliTharavugal to "Coolie Data",
    K.mothaKanakku to "Total Invoiced",
    K.mothaPattiyalgal to "Total Invoices",
    K.muzhuThallupadi to "Global Discount",
    K.nirilKooli to "Niril Coolie",
    K.nirilPattu to "Niril Silk",
    K.pattiyal to "Invoice",
    K.pattiyalEn to "Invoice Number",
    K.pattiyalEnnikai to "Invoice Count",
    K.pattiyalKuriyeedu to "Bill No.",
    K.pattiyalMudhanmozhi to "Select Primary Billing Language",
    K.pattiyalThaervukkuPinVaangunarTharavugalNirappappadum to "Customer details will be auto-filled after selecting an invoice.",
    K.pattiyalTharavugal to "Invoice Details",
    K.pattiyalVagai to "Invoice Type",
    K.pattiyalaiThaernhedu to "Select Invoice",
    K.pattiyalgal to "Invoices",
    K.pattiyalgalaiThaernhedu to "Select Invoices",
    K.pattiyalgstelidhu to "Your Billing & GST, Sorted.",
    K.pattiyalmozhi to "Which language would you like to use for your bills?",
    K.pattuMugappupPakkam to "Silk Home Page",
    K.pattuNiruvanaAdaiyaalangal to "Silk company identifiers",
    K.pattuTharavugal to "Silk Data",
    K.pudhiyaPattiyal to "New Bill",
    K.thallupadi to "Discount",
    K.variArikkai to "GST Return",
    K.variArikkaigal to "GST Returns",
    K.varipPattiyal to "Tax Invoice",
    K.cheluthiyaTharavu to "Payment Details",
    K.cheluthumMuraiThaernhedu to "Select payment mode",
    K.cheluthumMuraiVinmeen to "Payment Mode *",
    K.kaasu to "Cash",
    K.kanakkuEnIfsc to "Bank details",
    K.koolipPatrucheettuThiruthi to "Coolie Receipt Editor",
    K.koolipattiyalukku to "Used for Coolie bills and receipts.",
    K.patrucheettu to "Receipt",
    K.patrucheettuChaemikkappattadhu to "Receipt saved",
    K.patrucheettuEn to "Receipt Number",
    K.patrucheettuEnYaerkanavaeUlladhu to "Receipt number already exists!",
    K.patrucheettuEnnikai to "Receipt Count",
    K.patrucheettuNaal to "Receipt Date",
    K.patrucheettuTharavugal to "Receipt Details",
    K.patrucheettuVagai to "Receipt Type",
    K.patrucheettugal to "Receipts",
    K.pattiyalPatrucheettuMozhi to "Invoice & Receipt Language",
    K.pattupPatrucheettuThiruthi to "Silk Receipt Editor",
    K.pudhiyaKoolipPatrucheettu to "New Coolie Receipt",
    K.pudhiyaPattupPatrucheettu to "New Silk Receipt",
    K.vangi to "Bank",
    K.vangiParimaatram to "Bank Transfer",
    K.vangiTharavuKaattu to "Show Bank Details",
    K.vangiyinPeyar to "Bank Name",
    K.aagast to "Aug",
    K.aepral to "Apr",
    K.aktobar to "Oct",
    K.arivan to "Wednesday",
    K.chevvaay to "Tuesday",
    K.disambar to "December",
    K.janKurugiya to "Jan",
    K.fibKurugiya to "Feb",
    K.maarKurugiya to "Mar",
    K.aepKurugiya to "Apr",
    K.maeKurugiya to "May",
    K.joonKurugiya to "Jun",
    K.joolKurugiya to "Jul",
    K.aagKurugiya to "Aug",
    K.sepKurugiya to "Sep",
    K.akKurugiya to "Oct",
    K.navKurugiya to "Nov",
    K.disKurugiya to "Dec",
    K.fibravari to "Feb",
    K.janavari to "Jan",
    K.joolai to "Jul",
    K.joon to "Jun",
    K.kaari to "Saturday",
    K.maarch to "Mar",
    K.mae to "May",
    K.murpagal to "AM",
    K.naal to "Date",
    K.navambar to "Nov",
    K.nyaayiru to "Sunday",
    K.pirpagal to "PM",
    K.septambar to "Sep",
    K.thingal to "Monday",
    K.velli to "Friday",
    K.viyaazhan to "Thursday",
    K.chaemikkaIyalavillai to "Could not save:",
    K.illai to "None",
    K.kaiyoppamIllai to "No Signature",
    K.kurippuEnParimaatraEn to "Reference No / Transaction No",
    K.nirandharaAzhippuUrudhi to "Delete permanently? This cannot be undone.",
    K.niruvanapeyaraiullidu to "Please enter all required company names.",
    K.oavuruIllai to "No Logo",
    K.patrucheettugalIllai to "No Receipts",
    K.pattiyalgalIllai to "No invoices yet",
    K.pizhai to "Error",
    K.noolachu to "Noolachu",
    K.noolachuKooli to "Noolachu Coolie",
    K.noolachuPattu to "Noolachu Silk",
    K.kooli to "Coolie",
    K.pattu to "Silk",
    K.olirNilai to "Light Mode",
    K.pinchel to "Back",
    K.melum to "More",
    K.thoatram to "Appearance",
    K.kurithu to "About",
    K.alagu to "Unit",
    K.thogai to "Amount",
    K.thalaippu to "Header",
    K.tharavuIllai to "No Data",
    K.thiruthu to "Edit",
    K.chaemi to "Save",
    K.azhi to "Delete",
    K.kaividu to "Cancel",
    K.urudhi to "Confirm",
    K.veliyaeruUrudhi to "Do you want to sign out?",
    K.senthamizh to "Pure Tamil",
    K.elvanSansFont to "Elvan Sans Font",
    K.senthamizhKolkaei to "Pure Tamil Policy",
    K.tharavuKappagam to "Data Repository",
    K.pathippu to "Version",
    K.elvanNavil to "Elvan Navil",
    K.elvanNavilPatri to "Elvan Navil",
    K.elvanNavilDesc to "The studio behind this app",
    K.allRightsReserved to "© All rights reserved",
)
