package com.elvan.noolachu.localization.language_keys

import com.elvan.noolachu.core.navil.NavilMozhimaatri
import com.elvan.noolachu.localization.K

/**
 * Pure Tamil (Senthamizh) translations 1:1 matching Flutter's ta.dart.
 */
val ta: Map<String, String> = mapOf(
    K.aakku to "ஆக்கு",
    K.aangilam to "ஆங்கிலம்",
    K.adaiyaalam to "அடையாளம்",
    K.aetrugiradhu to "ஏற்றுகிறது...",
    K.agalamaanaOavuruMattum to "அகலமான ஓவுரு மட்டும்",
    K.agalamaanaoavuru to "செங்குத்து / அகலமான ஓவுரு",
    K.alaveeduMurai to "அளவீடு முறை",
    K.alavu to "அளவு",
    K.alavuVagai to "அளவு வகை",
    K.aluvalkaiyoppam to "அலுவல் கையொப்பத்தின் பெயர்",
    K.anjalKuriyeedu to "அஞ்சல் குறியீடு",
    K.appPeyar to "Elvan Niril",
    K.arikkai to "அறிக்கை",
    K.arikkaigal to "அறிக்கைகள்",
    K.arugilSeyalgal to "நடப்பு வினைகள்",
    K.attai to "அட்டை",
    K.azhikkiradhu to "அழிக்கிறது...",
    K.azhippuvetri to "தரவு வெற்றிகரமாக அழிக்கப்பட்டது.",
    K.chaedhaaram to "சேதாரம்",
    K.chaedhaaramGiraam to "சேதாரம் (g)",
    K.chaemikkaadhaVaraivu to "சேமிக்காத வரைவு. மீட்டமைக்கவா?",
    K.chaemikkappadugiradhu to "சேமிக்கப்படுகிறது...",
    K.chaemippuNiluvai to "சேமிப்பு நிலுவை",
    K.chaemippuvetri to "வெற்றிகரமாகச் சேமிக்கப்பட்டது",
    K.chaemiththaTharavugal to "சேமித்த தரவுகள்",
    K.cheyaliPatri to "செயலி பற்றி",
    K.cheyaliPatriMaadhiri to "செயலி பற்றி (மாதிரி)",
    K.cheyalipadhippu to "செயலியின் பதிப்பு மற்றும் தரவுகள்",
    K.cheyalithTharavaiAzhi to "செயலித் தரவை அழி",
    K.cheyaliyilirundhuVeliyaeravum to "செயலியிலிருந்து வெளியேறவும்.",
    K.chinnathinVadivam to "ஓவுருவின் வடிவம்",
    K.chiriyaOavuruPeyar to "சிறிய ஓவுரு + பெயர்",
    K.chuttruOppu to "முழுமையாக்கம்",
    K.edai to "எடை",
    K.elvanNiril to "எல்வன் நிறிள்",
    K.elvanParthasarathy to "எல்வன் பார்த்தசாரதி",
    K.elvanPatriMaelumAriga to "எல்வன் பற்றி மேலும் அறிக",
    K.en to "ஆங்கிலம்",
    K.endhachCheyalmurai to "எந்தச் செயல்முறை?",
    K.english to "ஆங்கிலம்",
    K.ifscKaattu to "IFSC காட்டு",
    K.ifscKuriyeedu to "IFSC குறியீடு",
    K.india to "இந்தியா",
    K.irudhiPeyar to "இறுதிப்பெயர்",
    K.irulNilai to "இருள் நிலை",
    K.kaasoalai to "காசோலை",
    K.kaiyaalu to "கையாளு",
    K.kaiyoppam to "கையொப்பம்",
    K.kanakkuEn to "கணக்கு எண்",
    K.kanakkuKuriyeedu to "க/எ எண்",
    K.kattanaPeyar to "கட்டணப் பெயர்",
    K.kilai to "கிளை",
    K.kilaipPeyar to "கிளைப் பெயர்",
    K.koriyar to "கொரியர்",
    K.koriyarKattanam to "கொரியர் (₹)",
    K.koappugal to "கோப்புகள்",
    K.kurippu to "குறிப்பு",
    K.kurugiyaNiruvanaPeyar to "குறுகிய நிறுவனப் பெயர்",
    K.maanilam to "மாநிலம்",
    K.maanilamThaedu to "மாநிலம் தேடுக...",
    K.maanilamThaerodhu to "மாநிலம் தேர்ந்தெடு",
    K.maatru to "மாற்று",
    K.maatruPaesiEn to "மாற்று பேசி எண்",
    K.maavattam to "மாவட்டம்",
    K.meendumThaedu to "மீண்டும் தேடு",
    K.meeteduppuVetri to "வெற்றிகரமாக மீட்கப்பட்டது",
    K.meetkavum to "மீட்கவும்",
    K.meetpagam to "மீட்பகம்",
    K.meetpagam30Naal to "மீட்பகத்தில் உள்ளவை 30 நாள்களுக்குப் பிறகு தானாகவே அழிக்கப்படும்",
    K.meetpagamKaaliyanadhu to "மீட்பகம் காலியானது",
    K.meetteduppuvetri to "தரவு வெற்றிகரமாக மீட்டெடுக்கப்பட்டது!",
    K.minnanjal to "மின்னஞ்சல்",
    K.minnanjalMugavari to "மின்னஞ்சல் முகவரி",
    K.minnanjalaiUllidavum to "மின்னஞ்சலை உள்ளிடவும்",
    K.minnanjalaiUrudhiseiga to "மின்னஞ்சலை உறுதிசெய்க",
    K.mothaEdai to "மொத்த எடை",
    K.motham to "மொத்தம்",
    K.mothangal to "மொத்தங்கள்",
    K.mudhalPeyar to "முதற்பெயர்",
    K.mudindhadhu to "முடிந்தது",
    K.mugappu to "முகப்பு",
    K.mugavari to "முகவரி",
    K.mugavaritharavugal to "நிறுவன முகவரித் தரவுகள்",
    K.munthogai to "முன்தொகை",
    K.munvaraivu to "முன்வரைவு",
    K.naadu to "நாடு",
    K.niraagari to "நிராகரி",
    K.nirandharaAzhippu to "நிரந்தரமாக அழி",
    K.niril to "நிறிள்",
    K.nirilthodanga to "நிறிளை தொடங்க கீழ் உள்ள பொத்தானை தட்டவும்",
    K.niruvanam to "நிறுவனம்",
    K.niruvanathTharavu to "நிறுவனத் தரவு",
    K.niruvanangal to "நிறுவனங்கள்",
    K.niruvanathinOavuru to "நிறுவனத்தின் ஓவுரு",
    K.niruvanathinPeyar to "நிறுவனத்தின் பெயர்",
    K.niruvanaththaithThaernhedu to "நிறுவனத்தைத் தேர்ந்தெடு",
    K.oliNilai to "ஒளி நிலை",
    K.olirIrulThaaniyangu to "ஒளி இருள் தானியங்கு",
    K.oodhaa to "ஊதா",
    K.oor to "ஊர்",
    K.paadhugaappu to "பாதுகாப்பு",
    K.pachai to "பச்சை",
    K.padammoolam to "படத்தின் மூலத்தைத் தேர்ந்தெடுக்கவும்",
    K.padhivaetru to "பதிவேற்று",
    K.paesiEn to "பேசி எண்",
    K.paesiEnkal to "பேசி எண்கள்",
    K.payanar to "பயனர்",
    K.payanarVilakkam to "இப்பெயர் முகப்புத்திரையில் தோன்றும்.",
    K.payanpaduthiyaChaemippu to "பயன்படுத்திய சேமிப்பு",
    K.pazhaiyaTharavaiMeettedukkavaa to "பழைய தரவை மீட்டெடுக்கவா?",
    K.pazhaiyaTharavuKidaikkiradhu to "பழைய தரவு கிடைக்கிறது",
    K.pdfThoatram to "PDF தோற்றம்",
    K.perumMotham to "மொத்தத் தொகை",
    K.perunar to "பெறுநர்",
    K.peyarEarkanavaeUlladhu to "இப்பெயர் ஏற்கனவே உள்ளது.",
    K.peyaraiUlliduga to "பெயரை உள்ளிடுக",
    K.pira to "பிற",
    K.piraVarivuChaer to "பிற கட்டணம் சேர்",
    K.pirandhaThaedhi to "பிறந்த தேதி",
    K.pudhiyaAakkam to "புதிய ஆக்கம்",
    K.pudhiyaChaerkkai to "புதிய சேர்க்கை",
    K.pugaippadakKaruvi to "புகைப்படக் கருவி",
    K.pugaippadathThoguppu to "புகைப்படத் தொகுப்பு",
    K.ta to "தமிழ்",
    K.tamil to "தமிழ்",
    K.tamilLatin to "தமிழ் இலத்தீன்",
    K.thaaniyangki to "தானியங்கி",
    K.thaaniyangkiUruvaam to "சேமிக்கையில் தானே உருவாகும்",
    K.thaeduga to "தேடுக...",
    K.thaerndhedu to "தேர்ந்தெடு",
    K.thallupadiChurukkam to "த.படி",
    K.thamizh to "தமிழ்",
    K.thamizhAangilamThaaniyangu to "தமிழ், ஆங்கிலம், தானியங்கு",
    K.tharavaiMeettedukkiradhu to "தரவை மீட்டெடுக்கிறது...",
    K.tharavaiazhi to "தரவுகளை முற்றிலும் அழிக்கவும்.",
    K.tharavugalChaemippuVetri to "தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன",
    K.tharavugalaiUlliduga to "தரவுகளை உள்ளிடுக",
    K.tharavugalaiUruvaakkuUruvaakkunar to "தரவுகளை உருவாக்கு (உருவாக்குனர்)",
    K.tharpoadhaiyaNiruvanam to "தற்போதைய நிறுவனம்",
    K.thirai to "திரை",
    K.thodarpuVari to "தொடர்பு & வரி",
    K.thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum to "தொகை 0-ஐ விட மிகுதியாக இருக்க வேண்டும்",
    K.thogaiVinmeen to "தொகை *",
    K.tholaipaesi to "தொலைப்பேசி",
    K.ulmotham to "இடைமொத்தம்",
    K.ungalCheyalmuraiyaithThaerndhedukkavum to "உங்கள் செயல்முறையைத் தேர்ந்தெடுக்கவும்",
    K.uruvaakkunarTharavugalaiAzhi to "உருவாக்குனர்: தரவுகளை அழி",
    K.uruvaakkunarTharavugalaiUruvaakku to "உருவாக்குனர்: தரவுகளை உருவாக்கு",
    K.vaangunarPeyarThaedu to "வாங்குநர் பெயர்",
    K.vaangunarTharavugal to "வாங்குநர் தரவுகள்",
    K.vanakkam to "வணக்கம்!",
    K.varaivu to "வரைவு",
    K.varaivuMeetka to "வரைவு மீட்கவா?",
    K.variThirattiyavai to "வரி திரட்டியவை",
    K.vazhangalIdam to "வழங்கல் இடம்",
    K.velinaadMugavari to "முழு முகவரி",
    K.veliyaeraVaendumaa to "வெளியேற வேண்டுமா?",
    K.veliyaeru to "வெளியேறு",
    K.veliyaerugiradhu to "வெளியேறுகிறது...",
    K.veliyaetramvetri to "வெற்றிகரமாக வெளியேற்றப்பட்டது",
    K.vidupattaPulangalaiNirappavum to "விடுபட்ட புலங்களை நிரப்பவும்.",
    K.vilai to "விற்பனை விலை",
    K.vilaiMatrumVari to "விலை மற்றும் வரி",
    K.vilaiVeedham to "விலை",
    K.cheyaliyaiAnugaUlnuzhaiyavum to "செயலியை அணுக உள்நுழையவும்",
    K.kadavuchol to "கடவுச்சொல்",
    K.kadavuchollaiUllidavum to "கடவுச்சொல்லை உள்ளிடவும்",
    K.nirilirkuNalvaravu to "நிறிளிற்கு நல்வரவு",
    K.niruvanaThannuru to "நிறுவனத் தன்னுரு",
    K.niruvanamThaerodhu to "நிறுவனத்தைத் தேர்ந்தெடு",
    K.perumalavu5thannuru to "பெருமளவு 5 தன்னுருக்கள் மட்டுமே",
    K.pudhiyaThannuruChaer to "புதிய தன்னுரு சேர்",
    K.pudhiyaThannuruvaiUruvaakku to "புதிய தன்னுருவை உருவாக்கு",
    K.thannuruChaemikkappattadhu to "தன்னுரு சேமிக்கப்பட்டது!",
    K.thannuruNeekkappattadhu to "தன்னுரு நீக்கப்பட்டது",
    K.thannurukkalIllai to "தன்னுருக்கள் இல்லை",
    K.thannuruvaiMutrilumNeekkavaa to "தன்னுருவை முற்றிலும் நீக்கவா?",
    K.ulnuzhaiga to "உள்நுழைக",
    K.anaithaiyumTheriPtn to "அனைத்தையும் தேர்",
    K.anaiththaiyumPaarPtn to "யாவும்",
    K.azhikka to "அழிக்க",
    K.chaemiPtn to "சேமி",
    K.chaer to "சேர்",
    K.chaerPtn to "சேர்",
    K.chariPtn to "சரி",
    K.kaappuCheiPtn to "காப்பு செய்",
    K.kaividuPtn to "கைவிடு",
    K.maatriyamai to "மாற்றியமை",
    K.meeteduppuCheiPtn to "மீட்டெடு",
    K.meetteduPtn to "மீட்டெடு",
    K.neekkuPtn to "நீக்கு",
    K.orunginaiCheyaliPtn to "செயலியை ஒருங்கிணை",
    K.payanarTharavugalaiMaetriduPtn to "சேமி",
    K.porulaichChaerPtn to "பொருளைச் சேர்",
    K.pudhiyaPatrucheettuPtn to "புதிய பற்றுச்சீட்டு",
    K.pudhiyaPattiyalPtn to "புதிய பட்டியல்",
    K.pudhiyadhaagaThodanguPtn to "புதியதாக தொடங்கு",
    K.purakkaniPtn to "புறக்கணி",
    K.thanipPayanPtn to "தனிப்பயன்",
    K.tharavaiAzhiPtn to "தரவை அழி",
    K.thodangugaPtn to "தொடங்குக",
    K.thodarPtn to "தொடர்",
    K.thodaravum to "தொடரவும்",
    K.uruvaakkuPtn to "உருவாக்கு",
    K.veliyaeruPtn to "வெளியேறு",
    K.adaimozhi to "அடைமொழி",
    K.amaippugal to "அமைப்புகள்",
    K.chaemippu to "சேமிப்பு",
    K.chaemippuMatrumKaappu to "சேமிப்பு & காப்பு",
    K.cheyaliAmaippugal to "செயலி அமைப்புகள்",
    K.cheyaliMozhi to "செயலி மொழி",
    K.idhuvuraiKaappuIllai to "இதுவரை காப்பு இல்லை",
    K.irandaamMozhi to "இரண்டாம் மொழி",
    K.irumozhiMurai to "இருமொழி முறை",
    K.kaappu to "காப்பு",
    K.kaapputhTharavuIllai to "காப்புத் தரவு இல்லை, புதிதாக தொடங்குகிறது.",
    K.kaapputhTharavuKidaithadhu to "காப்புத் தரவு கிடைத்தது!",
    K.kaapputhTharavuThaedal to "காப்புத் தரவு தேடப்படுகிறது...",
    K.kadaisiThaaniyakkaKaappu to "கடைசி தானியக்கக் காப்பு",
    K.language to "மொழி",
    K.languageInfo to "மொழி மாற்றம் அனைத்துப் பக்கங்கள், வழிசெலுத்தல் மற்றும் அமைப்புகளிலும் உடனடியாக நடைமுறைப்படுத்தப்படும்.",
    K.mozhiThaervu to "மொழியைத் தேர்ந்தெடு",
    K.mudhanmaiMozhi to "முதன்மை மொழி",
    K.niruvanaAmaippugal to "நிறுவன அமைப்புகள்",
    K.orunginaiCheyaliVilakkam to "அண்மை மாற்றங்களை ஒத்திசைக்கவும்.",
    K.orunginaikkappattadhu to "ஒருங்கிணைக்கப்பட்டது!",
    K.orunginaikkiRadhu to "ஒருங்கிணைக்கிறது...",
    K.payanarAmaippugal to "பயனர் அமைப்புகள்",
    K.pilVadivamaippuViruppangal to "PDF வடிவமைப்பு விருப்பங்கள்",
    K.thaaniyangiAmaippu to "தானியங்கி அமைப்பு",
    K.thaekkagathaiazhi to "ஒருகிணை, வெளியேறு, தரவு அழி",
    K.tharavuKaappu to "தரவு காப்பு",
    K.tharavuKaappuChei to "தரவு காப்பு செய்",
    K.tharavuchaemippuvetri to "தரவு ஆவணங்களில் சேமிக்கப்பட்டது.",
    K.tharavuthalam to "தரவுத்தளம்",
    K.tharavuthalangalKaappaikKaiyaalu to "தரவுத்தளங்கள் & காப்பைக் கையாளு",
    K.ungalTharavaiChaemikkavum to "உங்கள் தரவை சேமிக்கவும்.",
    K.viruppaMozhiThaervu to "விருப்பமான மொழியைத் தேர்வு செய்க",
    K.azhikkappattaPorulgal to "அழிக்கப்பட்ட பொருள்கள்",
    K.azhikkappattaVaangunargal to "அழிக்கப்பட்ட வாங்குநர்கள்",
    K.azhikkappattaPattiyalgal to "அழிக்கப்பட்ட பட்டியல்கள்",
    K.azhikkappattaPatrucheettugal to "அழிக்கப்பட்ட பற்றுச்சீட்டுகள்",
    K.hsnSacKuriyeedu to "HSN/SAC குறியீடு",
    K.kuriaindhOruPorul to "குறைந்தது ஒரு பொருள் சேர்",
    K.menporulVadivaalar to "மென்பொருள் வடிவாளர்",
    K.menporulVadivaalarPatri to "மென்பொருள் வடிவாளர் பற்றி",
    K.menporulVadivaalarPatriMaadhiri to "மென்பொருள் வடிவாளர் பற்றி (மாதிரி)",
    K.pattiyalEnVaangunar to "பட்டியல் எண் / வாங்குநர்...",
    K.porul to "பொருள்",
    K.porulAzhikkappattadhu to "பொருள் அழிக்கப்பட்டது",
    K.porulChaemikkappattadhu to "பொருள் சேமிக்கப்பட்டது",
    K.porulPeyarThaevai to "பொருள் பெயர் தேவை",
    K.porulTharavugal to "பொருள் தரவுகள்",
    K.porulaiChaerkkavum to "முதல் பொருளைச் சேர்க்கவும்",
    K.porulgalIllai to "பொருட்கள் இல்லை",
    K.porutkal to "பொருட்கள்",
    K.vaangunar to "வாங்குநர்",
    K.vaangunarAzhikkappattadhu to "வாங்குநர் அழிக்கப்பட்டது",
    K.vaangunarChaemikkappattadhu to "வாங்குநர் சேமிக்கப்பட்டது",
    K.vaangunarPeyar to "வாங்குநர் பெயர்",
    K.vaangunarPeyarThaevai to "வாங்குநர் பெயர் தேவை",
    K.vaangunaraiChaerkkavum to "முதல் வணிகரைச் சேர்க்கவும்",
    K.vaangunaraiThaerodhu to "வணிகரைத் தேர்ந்தெடு",
    K.vaangunaraichChaer to "வணிகரைச் சேர்",
    K.vaangunargal to "வாங்குநர்கள்",
    K.vaangunargalIllai to "வாங்குநர்கள் இல்லை",
    K.ahimsaiPattu to "அகிம்சைப் பட்டு",
    K.ahimsaiPattuThogai to "அகிம்சைப் பட்டு (₹)",
    K.endhapPattiyalukku to "எந்தப் பட்டியலுக்கு",
    K.gstVeedham to "GST வீதம் %",
    K.gstin to "GSTIN",
    K.gstinTavaru to "GSTIN வடிவம் தவறானது",
    K.gstinVariAdaiyaalaEn to "GSTIN / வரி அடையாள எண்",
    K.gstpattiyalukku to "வழக்கமான GST பட்டியல்களுக்குப் பயன்படுத்தப்படும்.",
    K.gstpirippugal to "GST பிரிப்புகளைக் காட்டு",
    K.kooliMugappupPakkam to "கூலி முகப்புப் பக்கம்",
    K.kooliNiruvanaAdaiyaalangal to "கூலி நிறுவன அடையாளங்கள்",
    K.kooliNiruvanaPeyar to "கூலி நிறுவனப் பெயர்",
    K.kooliTharavugal to "கூலித் தரவுகள்",
    K.mothaKanakku to "மொத்தத் தொகை",
    K.mothaPattiyalgal to "மொத்தப் பட்டியல்கள்",
    K.muzhuThallupadi to "முழுத் தள்ளுபடி",
    K.nirilKooli to "நிறிள் கூலி",
    K.nirilPattu to "நிறிள் பட்டு",
    K.pattiyal to "பட்டியல்",
    K.pattiyalEn to "பட்டியல் எண்",
    K.pattiyalEnnikai to "பட்டியல் எண்ணிக்கை",
    K.pattiyalKuriyeedu to "பட்டியல் எண்",
    K.pattiyalMudhanmozhi to "பட்டியல் முதன்மொழி",
    K.pattiyalThaervukkuPinVaangunarTharavugalNirappappadum to "பட்டியலைத் தேர்ந்தெடுத்ததும் வாங்குநர் தரவுகள் தானே நிரப்பப்படும்.",
    K.pattiyalTharavugal to "பட்டியல் தரவுகள்",
    K.pattiyalVagai to "பட்டியல் வகை",
    K.pattiyalaiThaernhedu to "பட்டியலைத் தேர்ந்தெடு",
    K.pattiyalgal to "பட்டியல்கள்",
    K.pattiyalgalaiThaernhedu to "பட்டியல்களைத் தேர்ந்தெடு",
    K.pattiyalgstelidhu to "உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.",
    K.pattiyalmozhi to "பட்டியலில் எம்மொழியை பயன்படுத்த வேண்டும்?",
    K.pattuMugappupPakkam to "பட்டு முகப்புப் பக்கம்",
    K.pattuNiruvanaAdaiyaalangal to "பட்டு நிறுவன அடையாளங்கள்",
    K.pattuTharavugal to "பட்டுத் தரவுகள்",
    K.pudhiyaPattiyal to "புதிய பட்டியல்",
    K.thallupadi to "தள்ளுபடி",
    K.variArikkai to "வரி அறிக்கை",
    K.variArikkaigal to "வரி அறிக்கைகள்",
    K.varipPattiyal to "வரிப் பட்டியல்",
    K.cheluthiyaTharavu to "கட்டணத் தரவு",
    K.cheluthumMuraiThaernhedu to "கட்டண முறையைத் தேர்ந்தெடு",
    K.cheluthumMuraiVinmeen to "கட்டண முறை *",
    K.kaasu to "காசு",
    K.kanakkuEnIfsc to "வங்கித் தரவுகள்",
    K.koolipPatrucheettuThiruthi to "கூலிப் பற்றுச்சீட்டு திருத்தி",
    K.koolipattiyalukku to "கூலி பட்டியல்கள் மற்றும் பற்றுச்சீட்டுகளுக்குப் பயன்படுத்தப்படும்.",
    K.patrucheettu to "பற்றுச்சீட்டு",
    K.patrucheettuChaemikkappattadhu to "பற்றுச்சீட்டு சேமிக்கப்பட்டது",
    K.patrucheettuEn to "பற்றுச்சீட்டு எண்",
    K.patrucheettuEnYaerkanavaeUlladhu to "பற்றுச்சீட்டு எண் ஏற்கனவே உள்ளது!",
    K.patrucheettuEnnikai to "பற்றுச்சீட்டு எண்ணிக்கை",
    K.patrucheettuNaal to "பற்றுச்சீட்டு நாள்",
    K.patrucheettuTharavugal to "பற்றுச்சீட்டு தரவுகள்",
    K.patrucheettuVagai to "பற்றுச்சீட்டு வகை",
    K.patrucheettugal to "பற்றுச்சீட்டுகள்",
    K.pattiyalPatrucheettuMozhi to "பட்டியல் & பற்றுச்சீட்டு மொழி",
    K.pattupPatrucheettuThiruthi to "பட்டுப் பற்றுச்சீட்டு திருத்தி",
    K.pudhiyaKoolipPatrucheettu to "புதிய கூலிப் பற்றுச்சீட்டு",
    K.pudhiyaPattupPatrucheettu to "புதிய பட்டுப் பற்றுச்சீட்டு",
    K.vangi to "வங்கி",
    K.vangiParimaatram to "வங்கிப் பரிமாற்றம்",
    K.vangiTharavuKaattu to "வங்கித் தரவு காட்டு",
    K.vangiyinPeyar to "வங்கியின் பெயர்",
    K.aagast to "ஆகஸ்ட்",
    K.aepral to "ஏப்ரல்",
    K.aktobar to "அக்டோபர்",
    K.arivan to "அறிவன்",
    K.chevvaay to "செவ்வாய்",
    K.disambar to "டிசம்பர்",
    K.janKurugiya to "ஜன",
    K.fibKurugiya to "ஃபிப்",
    K.maarKurugiya to "மார்",
    K.aepKurugiya to "ஏப்",
    K.maeKurugiya to "மே",
    K.joonKurugiya to "ஜூன்",
    K.joolKurugiya to "ஜூலை",
    K.aagKurugiya to "ஆக",
    K.sepKurugiya to "செப்",
    K.akKurugiya to "அக்",
    K.navKurugiya to "நவ",
    K.disKurugiya to "டிச",
    K.fibravari to "ஃபிப்ரவரி",
    K.janavari to "ஜனவரி",
    K.joolai to "ஜூலை",
    K.joon to "ஜூன்",
    K.kaari to "காரி",
    K.maarch to "மார்ச்",
    K.mae to "மே",
    K.murpagal to "முற்பகல்",
    K.naal to "நாள்",
    K.navambar to "நவம்பர்",
    K.nyaayiru to "ஞாயிறு",
    K.pirpagal to "பிற்பகல்",
    K.septambar to "செப்டம்பர்",
    K.thingal to "திங்கள்",
    K.velli to "வெள்ளி",
    K.viyaazhan to "வியாழன்",
    K.chaemikkaIyalavillai to "சேமிக்க இயலவில்லை:",
    K.illai to "இல்லை",
    K.kaiyoppamIllai to "கையொப்பம் இல்லை",
    K.kurippuEnParimaatraEn to "குறிப்பு எண் / பரிமாற்ற எண்",
    K.nirandharaAzhippuUrudhi to "நிரந்தரமாக அழிக்கவா? மீட்க இயலாது.",
    K.niruvanapeyaraiullidu to "தேவையான அனைத்து நிறுவனப் பெயர்களையும் உள்ளிடுக.",
    K.oavuruIllai to "ஓவுரு இல்லை",
    K.patrucheettugalIllai to "பற்றுச்சீட்டுகள் இல்லை",
    K.pattiyalgalIllai to "பட்டியல்கள் இல்லை",
    K.pizhai to "பிழை",
    K.noolachu to "நூலச்சு",
    K.noolachuKooli to "நூலச்சு கூலி",
    K.noolachuPattu to "நூலச்சு பட்டு",
    K.kooli to "கூலி",
    K.pattu to "பட்டு",
    K.olirNilai to "ஒளி நிலை",
    K.pinchel to "பின்கட்டளை",
    K.melum to "மேலும்",
    K.thoatram to "தோற்றம்",
    K.kurithu to "குறித்து",
    K.alagu to "அலகு",
    K.thogai to "தொகை",
    K.thalaippu to "தலைப்பு",
    K.tharavuIllai to "தரவு இல்லை",
    K.thiruthu to "திருத்து",
    K.chaemi to "சேமி",
    K.azhi to "அழி",
    K.kaividu to "கைவிடு",
    K.urudhi to "உறுதிசெய்",
    K.veliyaeruUrudhi to "வெளியேற வேண்டுமா?",
    K.senthamizh to "செந்தமிழ்",
    K.elvanSansFont to "எல்வன் சான்ஸ்",
    K.senthamizhKolkaei to "தூய தமிழ் கொள்கை",
    K.tharavuKappagam to "தரவு காப்பகம்",
    K.pathippu to "பதிப்பு",
    K.elvanNavil to "எல்வன் நவில்",
    K.elvanNavilPatri to "எல்வன் நவில்",
    K.elvanNavilDesc to "இச்செயலின் கடைப்பிடியான நிறுவனம்",
    K.allRightsReserved to "© அனைத்து உரிமைகளும் காக்கப்பட்டவை",
    K.navilMozhimatri to "நவில் மொழிமாற்றி",
    K.navilMozhimatriDesc to "தொல்காப்பிய ஒலிபெயர்ப்புப் பொறி",
    K.thamizhUllidu to "தமிழ் உள்ளீடு",
    K.navilVeliyidu to "நவில் வெளியீடு",
    K.asaiPirippu to "அசை பிரித்தல்",
    K.padiedukkappattadhu to "படியெடுக்கப்பட்டது",
    K.eduthukaattugal to "எடுத்துக்காட்டுகள்",
    K.tholkaappiyaNerigal to "தொல்காப்பிய நெறிகள்",
    K.ezhezhuthukkal to "எழுத்துகள்",
    K.cholEnnikkai to "சொற்கள்",
)

/**
 * Dynamically generated Tamil Latin (Tanglish/Romanized) translations
 * using the pure Kotlin Tolkappiyam NavilEngine.
 * Eliminates the need for a separate static TaLatn.kt file.
 */
val taLatn: Map<String, String> by lazy {
    ta.mapValues { (_, tamilText) ->
        NavilMozhimaatri.transliterate(tamilText)
    }
}
