package com.elvan.noolachu.localization.language_keys

import com.elvan.noolachu.localization.K

/**
 * Tamil Latin (Transliterated) translations 1:1 matching Flutter's ta_latn.dart.
 */
val taLatn: Map<String, String> = mapOf(
    K.aakku to "Aakku",
    K.aangilam to "Aangilam",
    K.adaiyaalam to "Adaiyaalam",
    K.aetrugiradhu to "Aetrugiradhu...",
    K.agalamaanaOavuruMattum to "Agalamaana Oavuru Mattum",
    K.agalamaanaoavuru to "Chenguthu / Agalamaana Oavuru",
    K.alaveeduMurai to "Alaveedu Murai",
    K.alavu to "Alavu",
    K.alavuVagai to "Alavu Vagai",
    K.aluvalkaiyoppam to "Aluval Kaiyoppathin Peyar",
    K.anjalKuriyeedu to "Anjal Kuriyeedu",
    K.appPeyar to "Elvan Niril",
    K.arikkai to "Arikkai",
    K.arikkaigal to "Arikkaigal",
    K.arugilSeyalgal to "Nadappu Vinaigal",
    K.attai to "Attai",
    K.azhikkiradhu to "Azhikkiradhu...",
    K.azhippuvetri to "Tharavu Vetrigaramaaga Azhikkappattadhu.",
    K.chaedhaaram to "Chaedhaaram",
    K.chaedhaaramGiraam to "Chaedhaaram (g)",
    K.chaemikkaadhaVaraivu to "Chaemikkaadha varaivu. Meettamaikkavaa?",
    K.chaemikkappadugiradhu to "Chaemikkappadugiradhu...",
    K.chaemippuNiluvai to "Chaemippu Niluvai",
    K.chaemippuvetri to "Vetrigaramaagach Chaemikkappattadhu",
    K.chaemiththaTharavugal to "Chaemitha Tharavugal",
    K.cheyaliPatri to "Cheyali Patri",
    K.cheyaliPatriMaadhiri to "Cheyali Patri (Maadhiri)",
    K.cheyalipadhippu to "Cheyaliyin Padhippu matrum Tharavugal",
    K.cheyalithTharavaiAzhi to "Cheyalith Tharavai Azhi",
    K.cheyaliyilirundhuVeliyaeravum to "Cheyaliyilirundhu Veliyaeravum.",
    K.chinnathinVadivam to "Oavuruvin Vadivam",
    K.chiriyaOavuruPeyar to "Chiriya Oavuru + Peyar",
    K.chuttruOppu to "Muzhumaiyaakkam",
    K.edai to "Edai",
    K.elvanNiril to "Elvan Niril",
    K.elvanParthasarathy to "Elvan Parthasarathy",
    K.elvanPatriMaelumAriga to "Elvan Patri Maelum Ariga",
    K.en to "Aangilam",
    K.endhachCheyalmurai to "Endhach Cheyalmurai?",
    K.english to "Aangilam",
    K.ifscKaattu to "IFSC Kaattu",
    K.ifscKuriyeedu to "IFSC Kuriyeedu",
    K.india to "Indhiya",
    K.irudhiPeyar to "Irudhi Peyar",
    K.irulNilai to "Irul Nilai",
    K.kaasoalai to "Kaasoalai",
    K.kaiyaalu to "Kaiyaalu",
    K.kaiyoppam to "Kaiyoppam",
    K.kanakkuEn to "Kanakku En",
    K.kanakkuKuriyeedu to "Ka/E En",
    K.kattanaPeyar to "Kattana Peyar",
    K.kilai to "Kilai",
    K.kilaipPeyar to "Kilaip Peyar",
    K.koriyar to "Koriyar",
    K.koriyarKattanam to "Koriyar (₹)",
    K.koappugal to "Koappugal",
    K.kurippu to "Kurippu",
    K.kurugiyaNiruvanaPeyar to "Kurugiya Niruvanap Peyar",
    K.maanilam to "Maanilam",
    K.maanilamThaedu to "Maanilam Thaeduga...",
    K.maanilamThaerodhu to "Maanilam Thaerndhedu",
    K.maatru to "Maatru",
    K.maatruPaesiEn to "Maatru Paesi En",
    K.maavattam to "Maavattam",
    K.meendumThaedu to "Meendum Thaedu",
    K.meeteduppuVetri to "Vetrigaramaaga Meetkappattadhu",
    K.meetkavum to "Meetkavum",
    K.meetpagam to "Meetpagam",
    K.meetpagam30Naal to "Meetpagatthil Ullavai 30 Naalgalukku Piragu Thaanaagavae Azhikkapppadum",
    K.meetpagamKaaliyanadhu to "Meetpagam Kaaliyanadhu",
    K.meetteduppuvetri to "Tharavu Vetrigaramaaga Meettedukkappattadhu!",
    K.minnanjal to "Minnanjal",
    K.minnanjalMugavari to "Minnanjal Mugavari",
    K.minnanjalaiUllidavum to "Minnanjalai Ullidavum",
    K.minnanjalaiUrudhiseiga to "Minnanjalai Urudhiseiga",
    K.mothaEdai to "Motha Edai",
    K.motham to "Motham",
    K.mothangal to "Mothangal",
    K.mudhalPeyar to "Mudhal Peyar",
    K.mudindhadhu to "Mudindhadhu",
    K.mugappu to "Mugappu",
    K.mugavari to "Mugavari",
    K.mugavaritharavugal to "Niruvana Mugavarith Tharavugal",
    K.munthogai to "Munthogai",
    K.munvaraivu to "Munvaraivu",
    K.naadu to "Naadu",
    K.niraagari to "Niraagari",
    K.nirandharaAzhippu to "Nirandharamaaga Azhi",
    K.niril to "Niril",
    K.nirilthodanga to "Nirilai Thodanga Keezh Ulla Pothaanai Thattavum",
    K.niruvanam to "Niruvanam",
    K.niruvanathTharavu to "Niruvanath Tharavu",
    K.niruvanangal to "Niruvanangal",
    K.niruvanathinOavuru to "Niruvanathin Oavuru",
    K.niruvanathinPeyar to "Niruvanathin Peyar",
    K.niruvanaththaithThaernhedu to "Niruvanaththaith Thaernhedu",
    K.oliNilai to "Oli Nilai",
    K.olirIrulThaaniyangu to "Oli irul Thaaniyangu",
    K.oodhaa to "Oodhaa",
    K.oor to "Oor",
    K.paadhugaappu to "Paadhugaappu",
    K.pachai to "Pachai",
    K.padammoolam to "Padathin Moolathaith Thaerndhedukkavum",
    K.padhivaetru to "Padhivaetru",
    K.paesiEn to "Paesi En",
    K.paesiEnkal to "Paesi Enkal",
    K.payanar to "Payanar",
    K.payanarVilakkam to "Ippeyar Mugappu Thiraiyil Thoandrum.",
    K.payanpaduthiyaChaemippu to "Payanpaduthiya Chaemippu",
    K.pazhaiyaTharavaiMeettedukkavaa to "Pazhaiya Tharavai Meettedukkavaa?",
    K.pazhaiyaTharavuKidaikkiradhu to "Pazhaiya Tharavu Kidaikkiradhu",
    K.pdfThoatram to "PDF Thoatram",
    K.perumMotham to "Mothath Thogai",
    K.perunar to "Perunar",
    K.peyarEarkanavaeUlladhu to "ippeyar aerkkanavae ulladhu.",
    K.peyaraiUlliduga to "Peyarai Ulliduga",
    K.pira to "Pira",
    K.piraVarivuChaer to "Pira Kattanam Chaer",
    K.pirandhaThaedhi to "Pirandha Naal",
    K.pudhiyaAakkam to "Pudhiya Aakkam",
    K.pudhiyaChaerkkai to "Pudhiya Chaerkkai",
    K.pugaippadakKaruvi to "Pugaippadak Karuvi",
    K.pugaippadathThoguppu to "Pugaippadath Thoguppu",
    K.ta to "Thamizh",
    K.tamil to "Thamizh",
    K.tamilLatin to "Thamizh Latin",
    K.thaaniyangki to "Thaaniyangki",
    K.thaaniyangkiUruvaam to "Thaaniyangki Uruvaam",
    K.thaeduga to "Thaeduga...",
    K.thaerndhedu to "Thaerndhedu",
    K.thallupadiChurukkam to "Tha.Padi",
    K.thamizh to "Thamizh",
    K.thamizhAangilamThaaniyangu to "Thamizh, Aangilam, Thaaniyangu",
    K.tharavaiMeettedukkiradhu to "Tharavai Meettedukkiradhu...",
    K.tharavaiazhi to "Tharavugalai Mutrilum Azhikkavum.",
    K.tharavugalChaemippuVetri to "Tharavugal Vetrigaramaaga Chaemikkappattana",
    K.tharavugalaiUlliduga to "Tharavugalai Ulliduga",
    K.tharavugalaiUruvaakkuUruvaakkunar to "Tharavugalai Uruvaakku (Uruvaakkunar)",
    K.tharpoadhaiyaNiruvanam to "Tharpoadhaiya Niruvanam",
    K.thirai to "Thirai",
    K.thodarpuVari to "Thodarbu & Vari",
    K.thogaiChuzhiyaththaiVidaMigudhiyaagaIrukkaVaendum to "Thogai 0-ai vida migudhiyaaga irukka vaendum",
    K.thogaiVinmeen to "Thogai *",
    K.tholaipaesi to "Tholaippaesi",
    K.ulmotham to "Idaimotham",
    K.ungalCheyalmuraiyaithThaerndhedukkavum to "Ungal Cheyalmuraiyaith Thaerndhedukkavum",
    K.uruvaakkunarTharavugalaiAzhi to "Uruvaakkunar: Tharavugalai Azhi",
    K.uruvaakkunarTharavugalaiUruvaakku to "Uruvaakkunar: Tharavugalai Uruvaakku",
    K.vaangunarPeyarThaedu to "Vaangunar Peyar",
    K.vaangunarTharavugal to "Vanigath Tharavugal",
    K.vanakkam to "Vanakkam!",
    K.varaivu to "Varaivu",
    K.varaivuMeetka to "Varaivu Meetkavaa?",
    K.variThirattiyavai to "Vari Thirattiyavai",
    K.vazhangalIdam to "Vazhangal Idam",
    K.velinaadMugavari to "Muzhu Mugavari",
    K.veliyaeraVaendumaa to "Veliyaera Vaendumaa?",
    K.veliyaeru to "Veliyaeru",
    K.veliyaerugiradhu to "Veliyaerugiradhu...",
    K.veliyaetramvetri to "Vetrigaramaaga Veliyaetrappattadhu",
    K.vidupattaPulangalaiNirappavum to "Vidupatta pulangalai nirappavum.",
    K.vilai to "Vilai",
    K.vilaiMatrumVari to "Vilai matrum Vari",
    K.vilaiVeedham to "Vilai",
    K.cheyaliyaiAnugaUlnuzhaiyavum to "Cheyaliyai Anuga Ulnuzhaiyavum",
    K.kadavuchol to "Kadavuchol",
    K.kadavuchollaiUllidavum to "Kadavuchollai Ullidavum",
    K.nirilirkuNalvaravu to "Nirilirku Nalvaravu",
    K.niruvanaThannuru to "Niruvana Thannuru",
    K.niruvanamThaerodhu to "Niruvanatthai Thaerndhedu",
    K.perumalavu5thannuru to "Perumalavu 5 Thannurukkal Mattumae",
    K.pudhiyaThannuruChaer to "Pudhiya Thannuru Chaer",
    K.pudhiyaThannuruvaiUruvaakku to "Pudhiya Thannuruvai Uruvaakku",
    K.thannuruChaemikkappattadhu to "Thannuru Chaemikkappattadhu!",
    K.thannuruNeekkappattadhu to "Thannuru Neekkappattadhu",
    K.thannurukkalIllai to "Thannurukkal Illai",
    K.thannuruvaiMutrilumNeekkavaa to "Thannuruvai Mutrilum Neekkavaa?",
    K.ulnuzhaiga to "Ulnuzhaiga",
    K.anaithaiyumTheriPtn to "Anaithaiyum Theri",
    K.anaiththaiyumPaarPtn to "Yaavum",
    K.azhikka to "Azhikka",
    K.chaemiPtn to "Chaemi",
    K.chaer to "Chaer",
    K.chaerPtn to "Chaer",
    K.chariPtn to "Chari",
    K.kaappuCheiPtn to "Kaappu Chei",
    K.kaividuPtn to "Kaividu",
    K.maatriyamai to "Maatriyamai",
    K.meeteduppuCheiPtn to "Meetteduppu Chei",
    K.meetteduPtn to "Meettedu",
    K.neekkuPtn to "Neekku",
    K.orunginaiCheyaliPtn to "Cheyaliyai Orunginai",
    K.payanarTharavugalaiMaetriduPtn to "Chaemi",
    K.porulaichChaerPtn to "Porulaich Chaer",
    K.pudhiyaPatrucheettuPtn to "Pudhiya Patrucheettu",
    K.pudhiyaPattiyalPtn to "Pudhiya Pattiyal",
    K.pudhiyadhaagaThodanguPtn to "Pudhiyadhaaga Thodangu",
    K.purakkaniPtn to "Purakkani",
    K.thanipPayanPtn to "Thanippayan",
    K.tharavaiAzhiPtn to "Tharavai Azhi",
    K.thodangugaPtn to "Thodanguga",
    K.thodarPtn to "Thodar",
    K.thodaravum to "Thodaravum",
    K.uruvaakkuPtn to "Uruvaakku",
    K.veliyaeruPtn to "Veliyaeru",
    K.adaimozhi to "Adaimozhi",
    K.amaippugal to "Amaippugal",
    K.chaemippu to "Chaemippu",
    K.chaemippuMatrumKaappu to "Chaemippu & Kaappu",
    K.cheyaliAmaippugal to "Cheyali Amaippugal",
    K.cheyaliMozhi to "Cheyali Mozhi",
    K.idhuvuraiKaappuIllai to "Idhuvarai Kaappu Illai",
    K.irandaamMozhi to "Irandaam Mozhi",
    K.irumozhiMurai to "Irumozhi Murai",
    K.kaappu to "Kaappu",
    K.kaapputhTharavuIllai to "Kaapputh Tharavu Illai, Pudhidhaaga Thodangugiradhu.",
    K.kaapputhTharavuKidaithadhu to "Kaapputh Tharavu Kidaithadhu!",
    K.kaapputhTharavuThaedal to "Kaapputh Tharavu Thaedappadugiradhu...",
    K.kadaisiThaaniyakkaKaappu to "Kadaisi Thaaniyakka Kaappu",
    K.language to "Mozhi",
    K.languageInfo to "Mozhi maattrum anaithup pakkangal, vazhiseluthal matrum amaippugalilum udanadiyaaga nadaimuraipaduthappadum.",
    K.mozhiThaervu to "Mozhiyaith Thaerndhedu",
    K.mudhanmaiMozhi to "Mudhanmai Mozhi",
    K.niruvanaAmaippugal to "Niruvana Amaippugal",
    K.orunginaiCheyaliVilakkam to "Anmai maatrangalai othisaikkavum.",
    K.orunginaikkappattadhu to "Orunginaikkappattadhu!",
    K.orunginaikkiRadhu to "Orunginaikkiradhu...",
    K.payanarAmaippugal to "Payanar Amaippugal",
    K.pilVadivamaippuViruppangal to "PDF Vadivamaippu Viruppangal",
    K.thaaniyangiAmaippu to "Thaaniyangi Amaippu",
    K.thaekkagathaiazhi to "Orunginai, Veliyaeru, Tharavu Azhi",
    K.tharavuKaappu to "Tharavu Kaappu",
    K.tharavuKaappuChei to "Tharavu Kaappu Chei",
    K.tharavuchaemippuvetri to "Tharavu Aavanangalil Chaemikkappattadhu.",
    K.tharavuthalam to "Tharavuthalam",
    K.tharavuthalangalKaappaikKaiyaalu to "Tharavuthalangal & Kaappaik Kaiyaalu",
    K.ungalTharavaiChaemikkavum to "Ungal Tharavai Chaemikkavum.",
    K.viruppaMozhiThaervu to "Viruppamaana Mozhiyaith Thaervu Cheiga",
    K.azhikkappattaPorulgal to "Azhikkappatta Porulgal",
    K.azhikkappattaVaangunargal to "Azhikkappatta Vaangunargal",
    K.hsnSacKuriyeedu to "HSN/SAC Kuriyeedu",
    K.kuriaindhOruPorul to "Kuraindhadhu Oru Porul Chaer",
    K.menporulVadivaalar to "Menporul Vadivaalar",
    K.menporulVadivaalarPatri to "Menporul Vadivaalar Patri",
    K.menporulVadivaalarPatriMaadhiri to "Menporul Vadivaalar Patri (Maadhiri)",
    K.pattiyalEnVaangunar to "Pattiyal en / Vaangunar...",
    K.porul to "Porul",
    K.porulAzhikkappattadhu to "Porul Azhikkappattadhu",
    K.porulChaemikkappattadhu to "Porul Chaemikkappattadhu",
    K.porulPeyarThaevai to "Porul Peyar Thaevai",
    K.porulTharavugal to "Porul Tharavugal",
    K.porulaiChaerkkavum to "Mudhal Porulai Chaerkkavum",
    K.porulgalIllai to "Porutkal Illai",
    K.porutkal to "Porutkal",
    K.vaangunar to "Vaangunar",
    K.vaangunarAzhikkappattadhu to "Vaangunar Azhikkappattadhu",
    K.vaangunarChaemikkappattadhu to "Vaangunar Chaemikkappattadhu",
    K.vaangunarPeyar to "Vaangunar Peyar",
    K.vaangunarPeyarThaevai to "Vaangunar Peyar Thaevai",
    K.vaangunaraiChaerkkavum to "Mudhal Vaangunaraich Chaerkkavum",
    K.vaangunaraiThaerodhu to "Vaangunarai Thaerndhedu",
    K.vaangunaraichChaer to "Vaangunaraich Chaer",
    K.vaangunargal to "Vaangunargal",
    K.vaangunargalIllai to "Vaangunargal Illai",
    K.ahimsaiPattu to "Ahimsai Pattu",
    K.ahimsaiPattuThogai to "Ahimsai Pattu (₹)",
    K.endhapPattiyalukku to "Endhap Pattiyalukku?",
    K.gstVeedham to "GST Veedham %",
    K.gstin to "GSTIN",
    K.gstinTavaru to "GSTIN Vadivam Thavaraanadhu",
    K.gstinVariAdaiyaalaEn to "GSTIN / Vari Adaiyaala En",
    K.gstpattiyalukku to "Vazhakkamaana GST Pattiyalgalukkup Payanbaduthappadum.",
    K.gstpirippugal to "GST Pirippugalaik Kaattu",
    K.kooliMugappupPakkam to "Kooli Mugappup Pakkam",
    K.kooliNiruvanaAdaiyaalangal to "Kooli Niruvana Adaiyaalangal",
    K.kooliNiruvanaPeyar to "Kooli Niruvanap Peyar",
    K.kooliTharavugal to "Koolith Tharavugal",
    K.mothaKanakku to "Mothath Thogai",
    K.mothaPattiyalgal to "Mothap Pattiyalgal",
    K.muzhuThallupadi to "Muzhu Thallupadi",
    K.nirilKooli to "Niril Kooli",
    K.nirilPattu to "Niril Pattu",
    K.pattiyal to "Pattiyal",
    K.pattiyalEn to "Pattiyal En",
    K.pattiyalEnnikai to "Pattiyal Ennikkai",
    K.pattiyalKuriyeedu to "Pattiyal En",
    K.pattiyalMudhanmozhi to "Pattiyal Mudhanmozhi",
    K.pattiyalThaervukkuPinVaangunarTharavugalNirappappadum to "Pattiyalait Thaerndhedutthadhum Vaangunar Tharavugal Thaanae Nirappappadum.",
    K.pattiyalTharavugal to "Pattiyal Tharavugal",
    K.pattiyalVagai to "Pattiyal Vagai",
    K.pattiyalaiThaernhedu to "Pattiyalai Thaernhedu",
    K.pattiyalgal to "Pattiyalgal",
    K.pattiyalgalaiThaernhedu to "Pattiyalgalai thaernhedu",
    K.pattiyalgstelidhu to "Ungal Pattiyalgal & GST, Elidhaakkappattadhu.",
    K.pattiyalmozhi to "Pattiyalil Emmozhiyai Payanbadutha Vaendum?",
    K.pattuMugappupPakkam to "Pattu Mugappup Pakkam",
    K.pattuNiruvanaAdaiyaalangal to "Pattu Niruvana Adaiyaalangal",
    K.pattuTharavugal to "Pattuth Tharavugal",
    K.pudhiyaPattiyal to "Pudhiya Pattiyal",
    K.thallupadi to "Thallupadi",
    K.variArikkai to "Vari Arikkai",
    K.variArikkaigal to "Vari Arikkaigal",
    K.varipPattiyal to "Varip Pattiyal",
    K.cheluthiyaTharavu to "Kattanath Tharavu",
    K.cheluthumMuraiThaernhedu to "Kattana Muraiyai Thaerndhedu",
    K.cheluthumMuraiVinmeen to "Kattana Murai *",
    K.kaasu to "Kaasu",
    K.kanakkuEnIfsc to "Vangi Tharavugal",
    K.koolipPatrucheettuThiruthi to "Koolip Patrucheettu Thiruthi",
    K.koolipattiyalukku to "Kooli Pattiyalgal Matrum Patrucheettugalukkup Payanbaduthappadum.",
    K.patrucheettu to "Patrucheettu",
    K.patrucheettuChaemikkappattadhu to "Patrucheettu chaemikkappattadhu",
    K.patrucheettuEn to "Patrucheettu En",
    K.patrucheettuEnYaerkanavaeUlladhu to "Patrucheettu en yaerkanavae ulladhu!",
    K.patrucheettuEnnikai to "Patrucheettu Ennikkai",
    K.patrucheettuNaal to "Patrucheettu Naal",
    K.patrucheettuTharavugal to "Patrucheettu Tharavugal",
    K.patrucheettuVagai to "Patrucheettu Vagai",
    K.patrucheettugal to "Patrucheettugal",
    K.pattiyalPatrucheettuMozhi to "Pattiyal & Patrucheettu Mozhi",
    K.pattupPatrucheettuThiruthi to "Pattup Patrucheettu Thiruthi",
    K.pudhiyaKoolipPatrucheettu to "Pudhiya Koolip Patrucheettu",
    K.pudhiyaPattupPatrucheettu to "Pudhiya Pattup Patrucheettu",
    K.vangi to "Vangi",
    K.vangiParimaatram to "Vangip Parimaatram",
    K.vangiTharavuKaattu to "Vangi Tharavu Kaattu",
    K.vangiyinPeyar to "Vangiyin Peyar",
    K.aagast to "Aagast",
    K.aepral to "Aepral",
    K.aktobar to "Aktobar",
    K.arivan to "Arivan",
    K.chevvaay to "Chevvaay",
    K.disambar to "Disambar",
    K.janKurugiya to "Jan",
    K.fibKurugiya to "Fib",
    K.maarKurugiya to "Maar",
    K.aepKurugiya to "Aep",
    K.maeKurugiya to "Mae",
    K.joonKurugiya to "Joon",
    K.joolKurugiya to "Jool",
    K.aagKurugiya to "Aag",
    K.sepKurugiya to "Sep",
    K.akKurugiya to "Ak",
    K.navKurugiya to "Nav",
    K.disKurugiya to "Dis",
    K.fibravari to "Fibravari",
    K.janavari to "Janavari",
    K.joolai to "Joolai",
    K.joon to "Joon",
    K.kaari to "Kaari",
    K.maarch to "Maarch",
    K.mae to "Mae",
    K.murpagal to "Murpagal",
    K.naal to "Naal",
    K.navambar to "Navambar",
    K.nyaayiru to "Nyaayiru",
    K.pirpagal to "Pirpagal",
    K.septambar to "Septambar",
    K.thingal to "Thingal",
    K.velli to "Velli",
    K.viyaazhan to "Viyaazhan",
    K.chaemikkaIyalavillai to "Chaemikka iyalavillai:",
    K.illai to "Illai",
    K.kaiyoppamIllai to "Kaiyoppam Illai",
    K.kurippuEnParimaatraEn to "Kurippu En / Parimaatra En",
    K.nirandharaAzhippuUrudhi to "Nirandharamaaga Azhikkavaa? Meetka Iyalaadhu.",
    K.niruvanapeyaraiullidu to "Thaevaiyaana Anaithu Niruvanap Peyargalaiyum Ullidavum.",
    K.oavuruIllai to "Oavuru Illai",
    K.patrucheettugalIllai to "Patrucheettugal illai",
    K.pattiyalgalIllai to "Pattiyalgal Illai",
    K.pizhai to "Pizhai",
    K.noolachu to "Noolachu",
    K.noolachuKooli to "Noolachu Coolie",
    K.noolachuPattu to "Noolachu Silk",
    K.kooli to "Coolie",
    K.pattu to "Silk",
    K.olirNilai to "Oli Nilai",
    K.pinchel to "Pinchel",
    K.melum to "Melum",
    K.thoatram to "Thoatram",
    K.kurithu to "Kurithu",
    K.alagu to "Alagu",
    K.thogai to "Thogai",
    K.thalaippu to "Thalaippu",
    K.tharavuIllai to "Tharavu Illai",
    K.thiruthu to "Thiruthu",
    K.chaemi to "Chaemi",
    K.azhi to "Azhi",
    K.kaividu to "Kaividu",
    K.urudhi to "Urudhi",
    K.veliyaeruUrudhi to "Veliyaera Vaendumaa?",
    K.senthamizh to "Senthamizh",
    K.elvanSansFont to "Elvan Sans",
    K.senthamizhKolkaei to "Senthamizh Kolkaei",
    K.tharavuKappagam to "Tharavu Kappagam",
    K.pathippu to "Pathippu",
    K.elvanNavil to "Elvan Navil",
    K.elvanNavilPatri to "Elvan Navil",
    K.elvanNavilDesc to "Ich Cheyal Kadaippidum Niruvanam",
    K.allRightsReserved to "© Anaithum Urimaigalum Kaakkappattavai",
)
