const Map<String, String> en = {
  'nirilirkuNalvaravu': 'Welcome to Niril',
  'pattiyalgstelidhu': 'Your Billing & GST, Sorted.',
  'nirilthodanga': 'Tap "Get Started" to continue with Niril.',
  'pudhiyadhaagaThodanguPtn': 'Start Fresh',
  'mozhiThaervu': 'Select Language',
  'viruppaMozhiThaervu': 'Choose your preferred language',

  // ========================================
  // Help Center
  // ========================================
  'vanigathinPeyar': 'Business Name',
  'vanigargal': 'Merchants',
  'porutkal': 'Products',
  'pattiyalgal': 'Invoices',
  'patrucheettugal': 'Receipts',
  'arikkai': 'Report',
  'variArikkai': 'GST Return',

  // ========================================
  // Settings & Preferences
  // ========================================
  'amaippugal': 'Settings',
  'veliyaeru': 'Logout',
  'cheyaliMozhi': 'App Language',
  'vangiyinPeyar': 'Bank Name',
  'thannuruNeekkappattadhu': 'Profile deleted',
  'perumalavu5thannuru': 'Maximum 5 profiles allowed',
  'tharpoadhaiyaVanigam': 'Active Profile',
  'pudhiyaThannuruvaiUruvaakku': 'Create New Profile',
  'thannuruvaiMutrilumNeekkavaa': 'Permanently delete this business profile?',
  'pudhiyaThannuruChaer': 'Add New Profile',
  'thannuruChaemikkappattadhu': 'Profile saved!',
  'thannurukkalIllai': 'No saved profiles yet',
  'kanakkuEn': 'Account Number',
  'pdfThoatram': 'PDF Theme',
  'pattiyalPatrucheettuMozhi': 'Invoice & Receipt Language',
  'kadavuchol': 'Password',
  'kadavuchollaiUllidavum': 'Please enter your password',
  'kanakkuEnIfsc': 'Bank details',
  'thamizhAangilamThaaniyangu': 'Tamil, English, Auto',
  'thaekkagathaiazhi': 'Backup, Logout, Clear Data',
  'elvanPatriMaelumAriga': 'Learn more about Elvan',
  'cheyaliyilirundhuVeliyaeravum': 'Logout from the application.',
  'tharavuKaappuChei': 'Backup Data',
  'ungalTharavaiChaemikkavum': 'Manually update your backup file.',
  'tharavuKaappu': 'Backup Database',
  'kaappuCheiPtn': 'Backup Now',
  'tharavuchaemippuvetri': 'Backup successfully saved to Documents.',
  'mudhanmaiMozhi': 'Primary Language',
  'irandaamMozhi': 'Secondary Language',

  // ========================================
  // Merchants & Customers
  // ========================================
  'vanigar': 'Merchant',
  'minnanjal': 'Email',
  'vanigaraichChaer': 'Add Merchant',
  'oor': 'City',
  'maavattam': 'District',
  'maanilam': 'State',
  'naadu': 'Country',
  'paesiEnkal': 'Phone Numbers',
  'anjalKuriyeedu': 'Pincode',
  'minnanjalaiUrudhiseiga': 'Confirm Email',
  'minnanjalMugavari': 'Email Address',
  'minnanjalaiUllidavum': 'Enter your email',
  'mugavaritharavugal': 'Company address details',

  // ========================================
  // Inventory & Items
  // ========================================
  'porul': 'Product',
  'porulaichChaerPtn': 'Add Product',
  'gstpirippugal': 'Show GST splits in table',
  'pattiyal': 'Invoice',
  'pudhiyaPattiyal': 'New Bill',
  'patrucheettu': 'Receipt',
  'chaemippuvetri': 'Saved successfully',
  'pudhiyaPattiyalPtn': 'New Invoice',
  'pudhiyaPatrucheettuPtn': 'New Receipt',
  'veliyaetramvetri': 'Signed out successfully',
  'azhippuvetri': 'App data erased.',
  'pilVadivamaippuViruppangal': 'PDF styling options',
  'chinnathinVadivam': 'Bill Header Style',
  'meetteduppuvetri': 'Data restored successfully!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'arikkaigal': 'Reports',
  'variArikkaigal': 'GST Returns',
  'chaer': 'Add',
  'thaeduga': 'Search...',
  'kaividuPtn': 'Cancel',
  'neekkuPtn': 'Delete',
  'chaemiPtn': 'Save',
  'aakku': 'Make',
  'oavuruIllai': 'No Logo',
  'kaiyoppamIllai': 'No Signature',
  'uruvaakkuPtn': 'Create',
  'illai': 'None',
  'thaerndhedu': 'Select',
  'tharavugalChaemippuVetri': 'Details saved successfully',
  'kanakkuppagudhi': 'Select your operating mode',
  'veliyaeruPtn': 'Sign Out',
  'tharavaiAzhiPtn': 'Erase Data',
  'veliyaeraVaendumaa': 'Sign Out?',
  'thodangugaPtn': 'Get Started',
  'meetteduPtn': 'Restore Data',

  // ========================================
  // Miscellaneous
  // ========================================
  'niril': 'Niril',
  'thodaravum': 'Continue',
  'mugappu': 'Home',
  'mugavari': 'Address',
  'irulNilai': 'Dark Mode',
  'oliNilai': 'Light Mode',
  'ifscKuriyeedu': 'IFSC Code',
  'kilaipPeyar': 'Branch Name',
  'thamizh': 'Tamil',
  'aangilam': 'English',
  'tamil': 'Tamil',
  'english': 'English',
  'tamilLatin': 'Thamizh Latin',
  'niruvanathinOavuru': 'Company Logo',
  'kaiyoppam': 'Signature / Stamp',
  'paesiEn': 'Phone',
  'maatruPaesiEn': 'Mobile',
  'kurugiyaVanigaPeyar': 'Short Business Name',
  'adaimozhi': 'Tagline',
  'nirilKooli': 'Niril Coolie',
  'nirilPattu': 'Niril Silk',
  'meendumThaedu': 'Scan Again',
  'vanakkam': 'Vanakkam!',
  'indruEndhakKanakku': 'Who\'s working today?',
  'veliyaerugiradhu': 'Signing out...',
  'aluvalkaiyoppam': 'Authorized Signatory Name',
  'neriyuga': 'Manage',
  'pachai': 'Green',
  'oodhaa': 'Violet',
  'azhikkiradhu': 'Erasing...',
  'cheyaliyaiAnugaUlnuzhaiyavum': 'Login to access your app',
  'ulnuzhaiga': 'Sign In',
  'tharavugalaiUllidu': 'Please fill in all fields.',
  'pattiyalMudhanmozhi': 'Select Primary Billing Language',
  'pattiyalmozhi': 'Which language would you like to use for your bills?',
  'tharavugalaiUlliduga': 'Enter Business Details',
  'peyaraiUlliduga': 'Enter name',
  'gstpattiyalukku': 'Used for regular GST invoices.',
  'kooliVanigapPeyar': 'Coolie Business Name',
  'koolipattiyalukku': 'Used for Coolie bills and receipts.',
  'vanigam': 'Business',
  'vanigaAmaippugal': 'Business Settings',
  'vangi': 'Bank',
  'cheyaliAmaippugal': 'App Settings',
  'thirai': 'Display',
  'paadhugaappu': 'Security',
  'menporulVadivaalar': 'Software Designer',
  'adaiyaalam': 'Identifier',
  'kooliVanigaAdaiyaalangal': 'Coolie business identifiers',
  'pattuVanigaAdaiyaalangal': 'Silk business identifiers',
  'olirIrulThaaniyangu': 'Light mode, Dark mode, Auto',
  'cheyalithTharavaiAzhi': 'Erase App Data',
  'tharavaiazhi': 'Permanently erase data.',
  'chaemikkappadugiradhu': 'Backing up...',
  'irumozhiMurai': 'Bilingual Mode',
  'thaaniyangiAmaippu': 'System Auto',
  'agalamaanaoavuru': 'Vertical / Wide Logo',
  'chiriyaOavuruPeyar': 'Small Logo + Business Name',
  'agalamaanaOavuruMattum': 'Wide Logo Only',
  'padhivaetru': 'Upload',
  'pazhaiyaTharavuKidaikkiradhu': 'Old data available',
  'pazhaiyaTharavaiMeettedukkavaa': 'Your previous data was found. Would you like to restore it?',
  'tharavaiMeettedukkiradhu': 'Restoring data...',


  // === Auto Added Keys ===
  'pugaippadakKaruvi': 'Camera',
  'pugaippadathThoguppu': 'Gallery',
  'padammoolam': 'Select Image Source',
  'menporulVadivaalarPatri': 'About Developer',

  'cheyaliPatriMaadhiri': 'About App (Dummy)',
  'menporulVadivaalarPatriMaadhiri': 'About Developer (Dummy)',
  'kooliMugappupPakkam': 'Coolie Home Page',
  'koolipattiyalthiruthi': 'Coolie Invoice Editor (Labor Mode)',
  'pudhiyaKoolipPattiyal': 'New Coolie Invoice',
  'koolipPorulThiruthi': 'Coolie Item Editor',
  'pudhiyaKoolipPorul': 'New Coolie Item',
  'kooliVanigarThiruthi': 'Coolie Merchant Editor',
  'pudhiyaKooliVanigar': 'New Coolie Merchant',
  'koolipPatrucheettuThiruthi': 'Coolie Receipt Editor',
  'pudhiyaKoolipPatrucheettu': 'New Coolie Receipt',
  'pattuMugappupPakkam': 'Silk Home Page',
  'pattupattiyalthiruthi': 'Silk Invoice Editor (GST Mode)',
  'pudhiyaPattupPattiyal': 'New Silk Invoice',
  'pattupPorulThiruthi': 'Silk Item Editor',
  'pudhiyaPattupPorul': 'New Silk Item',
  'pattuVanigarThiruthi': 'Silk Merchant Editor',
  'pudhiyaPattuVanigar': 'New Silk Merchant',
  'pattupPatrucheettuThiruthi': 'Silk Receipt Editor',
  'pudhiyaPattupPatrucheettu': 'New Silk Receipt',
  'uruvaakkunarTharavugalaiAzhi': 'Dev: Erase',
  'uruvaakkunarTharavugalaiUruvaakku': 'Dev: Seed',
  'tharavugalaiUruvaakkuUruvaakkunar': 'Seed App (Dev)',
  'vanigapeyaraiullidu': 'Please enter all required business names.',
  'gstinVariAdaiyaalaEn': 'GSTIN / Tax ID',
  'gstin': 'GSTIN',
  'language': 'Language',
  'kaapputhTharavuKidaithadhu': 'Backup found!',
  'kaapputhTharavuThaedal': 'Checking for backups...',
  'kaapputhTharavuIllai': 'No backup found, starting fresh.',
  'cheyaliPatri': 'About App',
  'cheyalipadhippu': 'App version and data',
  'peyarEarkanavaeUlladhu': 'This name already exists.',
  'elvanParthasarathy': 'Elvan Parthasarathy',
  'appPeyar': 'Elvan Niril',
  'elvanNiril': 'Elvan Niril',
};
