const Map<String, String> ta = {
  'nirilirkuNalvaravu': 'நிறிளிற்கு நல்வரவு',
  'pattiyalgstelidhu': 'உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.',
  'nirilthodanga': 'நிறிளை தொடங்க கீழ் உள்ள பொத்தானை தட்டவும்',
  'pudhiyadhaagaThodanguPtn': 'புதியதாக தொடங்கு',
  'mozhiThaervu': 'மொழியைத் தேர்ந்தெடு',
  'viruppaMozhiThaervu': 'விருப்பமான மொழியைத் தேர்வு செய்க',

  // ========================================
  // Help Center
  // ========================================
  'vanigathinPeyar': 'வணிகத்தின் பெயர்',
  'vanigargal': 'வணிகர்கள்',
  'porutkal': 'பொருட்கள்',
  'pattiyalgal': 'பட்டியல்கள்',
  'patrucheettugal': 'பற்றுச்சீட்டுகள்',
  'arikkai': 'அறிக்கை',
  'variArikkai': 'வரி அறிக்கை',

  // ========================================
  // Settings & Preferences
  // ========================================
  'amaippugal': 'அமைப்புகள்',
  'veliyaeru': 'வெளியேறு',
  'cheyaliMozhi': 'செயலி மொழி',
  'vangiyinPeyar': 'வங்கியின் பெயர்',
  'thannuruNeekkappattadhu': 'தன்னுரு நீக்கப்பட்டது',
  'perumalavu5thannuru': 'பெருமளவு 5 தன்னுருக்கள் மட்டுமே',
  'tharpoadhaiyaVanigam': 'தற்போதைய வணிகம்',
  'pudhiyaThannuruvaiUruvaakku': 'புதிய தன்னுருவை உருவாக்கு',
  'thannuruvaiMutrilumNeekkavaa': 'தன்னுருவை முற்றிலும் நீக்கவா?',
  'pudhiyaThannuruChaer': 'புதிய தன்னுரு சேர்',
  'thannuruChaemikkappattadhu': 'தன்னுரு சேமிக்கப்பட்டது!',
  'thannurukkalIllai': 'தன்னுருக்கள் இல்லை',
  'kanakkuEn': 'கணக்கு எண்',
  'pdfThoatram': 'PDF தோற்றம்',
  'pattiyalPatrucheettuMozhi': 'பட்டியல் & பற்றுச்சீட்டு மொழி',
  'kadavuchol': 'கடவுச்சொல்',
  'kadavuchollaiUllidavum': 'கடவுச்சொல்லை உள்ளிடவும்',
  'kanakkuEnIfsc': 'வங்கித் தரவுகள்',
  'thamizhAangilamThaaniyangu': 'தமிழ், ஆங்கிலம், தானியங்கு',
  'thaekkagathaiazhi': 'காப்பு நகல், வெளியேறு, தரவு அழி',
  'elvanPatriMaelumAriga': 'எல்வன் பற்றி மேலும் அறிக',
  'cheyaliyilirundhuVeliyaeravum': 'செயலியிலிருந்து வெளியேறவும்.',
  'tharavuKaappuChei': 'தரவு காப்பு செய்',
  'ungalTharavaiChaemikkavum': 'உங்கள் தரவை சேமிக்கவும்.',
  'tharavuKaappu': 'தரவு காப்பு',
  'kaappuCheiPtn': 'காப்பு செய்',
  'tharavuchaemippuvetri': 'தரவு ஆவணங்களில் சேமிக்கப்பட்டது.',
  'mudhanmaiMozhi': 'முதன்மை மொழி',
  'irandaamMozhi': 'இரண்டாம் மொழி',

  // ========================================
  // Merchants & Customers
  // ========================================
  'vanigar': 'வணிகர்',
  'minnanjal': 'மின்னஞ்சல்',
  'vanigaraichChaer': 'வணிகரைச் சேர்',
  'oor': 'ஊர்',
  'maavattam': 'மாவட்டம்',
  'maanilam': 'மாநிலம்',
  'naadu': 'நாடு',
  'paesiEnkal': 'பேசி எண்கள்',
  'anjalKuriyeedu': 'அஞ்சல் குறியீடு',
  'minnanjalaiUrudhiseiga': 'மின்னஞ்சலை உறுதிசெய்க',
  'minnanjalMugavari': 'மின்னஞ்சல் முகவரி',
  'minnanjalaiUllidavum': 'மின்னஞ்சலை உள்ளிடவும்',
  'mugavaritharavugal': 'வணிக முகவரி தரவுகள்',

  // ========================================
  // Inventory & Items
  // ========================================
  'porul': 'பொருள்',
  'porulaichChaerPtn': 'பொருளைச் சேர்',
  'gstpirippugal': 'GST பிரிப்புகளைக் காட்டு',
  'pattiyal': 'பட்டியல்',
  'pudhiyaPattiyal': 'புதிய பட்டியல்',
  'patrucheettu': 'பற்றுச்சீட்டு',
  'pudhiyaPattiyalPtn': 'புதிய பட்டியல்',
  'pudhiyaPatrucheettuPtn': 'புதிய பற்றுச்சீட்டு',
  'veliyaetramvetri': 'வெற்றிகரமாக வெளியேற்றப்பட்டது',
  'azhippuvetri': 'தரவு வெற்றிகரமாக அழிக்கப்பட்டது.',
  'chaemippuvetri': 'வெற்றிகரமாகச் சேமிக்கப்பட்டது',
  'pilVadivamaippuViruppangal': 'PDF வடிவமைப்பு விருப்பங்கள்',
  'chinnathinVadivam': 'ஓவுருவின் வடிவம்',
  'meetteduppuvetri': 'தரவு வெற்றிகரமாக மீட்டெடுக்கப்பட்டது!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'arikkaigal': 'அறிக்கைகள்',
  'variArikkaigal': 'வரி அறிக்கைகள்',
  'chaer': 'சேர்',
  'thaeduga': 'தேடுக...',
  'kaividuPtn': 'கைவிடு',
  'neekkuPtn': 'நீக்கு',
  'chaemiPtn': 'சேமி',
  'aakku': 'ஆக்கு',
  'oavuruIllai': 'ஓவுரு இல்லை',
  'kaiyoppamIllai': 'கையொப்பம் இல்லை',
  'uruvaakkuPtn': 'உருவாக்கு',
  'illai': 'இல்லை',
  'thaerndhedu': 'தேர்ந்தெடு',
  'tharavugalChaemippuVetri': 'தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன',
  'kanakkuppagudhi': 'உங்கள் கணக்குப் பகுதியைத் தேர்ந்தெடுக்கவும்',
  'veliyaeruPtn': 'வெளியேறு',
  'tharavaiAzhiPtn': 'தரவை அழி',
  'veliyaeraVaendumaa': 'வெளியேற வேண்டுமா?',
  'thodangugaPtn': 'தொடங்குக',
  'meetteduPtn': 'மீட்டெடு',

  // ========================================
  // Miscellaneous
  // ========================================
  'appPeyar': 'Elvan Niril',
  'elvanNiril': 'எல்வன் நிறிள்',
  'niril': 'நிறிள்',
  'thodaravum': 'தொடரவும்',
  'gstin': 'GSTIN',
  'language': 'மொழி',
  'kaapputhTharavuKidaithadhu': 'காப்புத் தரவு கிடைத்தது!',
  'kaapputhTharavuThaedal': 'காப்புத் தரவு தேடப்படுகிறது...',
  'kaapputhTharavuIllai': 'காப்புத் தரவு இல்லை, புதிதாக தொடங்குகிறது.',
  'mugappu': 'முகப்பு',
  'mugavari': 'முகவரி',
  'irulNilai': 'இருள் நிலை',
  'oliNilai': 'ஒளி நிலை',
  'ifscKuriyeedu': 'IFSC குறியீடு',
  'kilaipPeyar': 'கிளைப் பெயர்',
  'thamizh': 'தமிழ்',
  'aangilam': 'ஆங்கிலம்',
  'tamil': 'தமிழ்',
  'english': 'ஆங்கிலம்',
  'tamilLatin': 'தமிழ் இலத்தின்',
  'niruvanathinOavuru': 'வணிகத்தின் ஓவுரு',
  'kaiyoppam': 'கையொப்பம்',
  'paesiEn': 'பேசி எண்',
  'maatruPaesiEn': 'மாற்று பேசி எண்',
  'kurugiyaVanigaPeyar': 'குறுகிய வணிக பெயர்',
  'adaimozhi': 'அடைமொழி',
  'nirilKooli': 'நிறில் கூலி',
  'nirilPattu': 'நிறில் பட்டு',
  'meendumThaedu': 'மீண்டும் தேடு',
  'veliyaerugiradhu': 'வெளியேறுகிறது...',
  'aluvalkaiyoppam': 'அலுவல் கையொப்பத்தின் பெயர்',
  'neriyuga': 'நெறியுக',
  'pachai': 'பச்சை',
  'oodhaa': 'ஊதா',
  'azhikkiradhu': 'அழிக்கிறது...',
  'vanakkam': 'வணக்கம்!',
  'indruEndhakKanakku': 'இன்று எந்தக் கணக்கு?',
  'cheyaliyaiAnugaUlnuzhaiyavum': 'செயலியை அணுக உள்நுழையவும்',
  'ulnuzhaiga': 'உள்நுழைக',
  'tharavugalaiUllidu': 'அனைத்து தரவுகளையும் உள்ளிடவும்.',
  'pattiyalMudhanmozhi': 'பட்டியல் முதன்மொழி',
  'pattiyalmozhi': 'பட்டியலில் எம்மொழியை பயன்படுத்த வேண்டும்?',
  'tharavugalaiUlliduga': 'தரவுகளை உள்ளிடுக',
  'peyaraiUlliduga': 'பெயரை உள்ளிடுக',
  'gstpattiyalukku': 'வழக்கமான GST பட்டியல்களுக்குப் பயன்படுத்தப்படும்.',
  'kooliVanigapPeyar': 'கூலி வணிகப் பெயர்',
  'koolipattiyalukku': 'கூலி பட்டியல்கள் மற்றும் பற்றுச்சீட்டுகளுக்குப் பயன்படுத்தப்படும்.',
  'vanigam': 'வணிகம்',
  'vanigaAmaippugal': 'வணிக அமைப்புகள்',
  'vangi': 'வங்கி',
  'cheyaliAmaippugal': 'செயலி அமைப்புகள்',
  'thirai': 'திரை',
  'paadhugaappu': 'பாதுகாப்பு',
  'menporulVadivaalar': 'மென்பொருள் வடிவாளர்',
  'cheyaliPatri': 'செயலி பற்றி',
  'cheyalipadhippu': 'செயலியின் பதிப்பு மற்றும் தரவுகள்',
  'peyarEarkanavaeUlladhu': 'இப்பெயர் ஏற்கனவே உள்ளது.',
  'adaiyaalam': 'அடையாளம்',
  'kooliVanigaAdaiyaalangal': 'கூலி வணிக அடையாளங்கள்',
  'pattuVanigaAdaiyaalangal': 'பட்டு வணிக அடையாளங்கள்',
  'olirIrulThaaniyangu': 'ஒளி இருள் தானியங்கு',
  'cheyalithTharavaiAzhi': 'செயலித் தரவை அழி',
  'tharavaiazhi': 'தரவுகளை முற்றிலும் அழிக்கவும்.',
  'chaemikkappadugiradhu': 'சேமிக்கப்படுகிறது...',
  'irumozhiMurai': 'இருமொழி முறை',
  'thaaniyangiAmaippu': 'தானியங்கி அமைப்பு',
  'agalamaanaoavuru': 'செங்குத்து / அகலமான ஓவுரு',
  'chiriyaOavuruPeyar': 'சிறிய ஓவுரு + பெயர்',
  'agalamaanaOavuruMattum': 'அகலமான ஓவுரு மட்டும்',
  'padhivaetru': 'பதிவேற்று',
  'pazhaiyaTharavuKidaikkiradhu': 'பழைய தரவு கிடைக்கிறது',
  'pazhaiyaTharavaiMeettedukkavaa': 'பழைய தரவை மீட்டெடுக்கவா?',
  'tharavaiMeettedukkiradhu': 'தரவை மீட்டெடுக்கிறது...',


  // === Auto Added Keys ===
  'pugaippadakKaruvi': 'புகைப்படக் கருவி',
  'pugaippadathThoguppu': 'புகைப்படத் தொகுப்பு',
  'padammoolam': 'படத்தின் மூலத்தைத் தேர்ந்தெடுக்கவும்',
  'menporulVadivaalarPatri': 'மென்பொருள் வடிவாளர் பற்றி',

  'cheyaliPatriMaadhiri': 'செயலி பற்றி (மாதிரி)',
  'menporulVadivaalarPatriMaadhiri': 'மென்பொருள் வடிவாளர் பற்றி (மாதிரி)',
  'kooliMugappupPakkam': 'கூலி முகப்புப் பக்கம்',
  'koolipattiyalthiruthi': 'கூலிப் பட்டியல் திருத்தி (தொழிலாளர் முறை)',
  'pudhiyaKoolipPattiyal': 'புதிய கூலிப் பட்டியல்',
  'koolipPorulThiruthi': 'கூலிப் பொருள் திருத்தி',
  'pudhiyaKoolipPorul': 'புதிய கூலிப் பொருள்',
  'kooliVanigarThiruthi': 'கூலி வணிகர் திருத்தி',
  'pudhiyaKooliVanigar': 'புதிய கூலி வணிகர்',
  'koolipPatrucheettuThiruthi': 'கூலிப் பற்றுச்சீட்டு திருத்தி',
  'pudhiyaKoolipPatrucheettu': 'புதிய கூலிப் பற்றுச்சீட்டு',
  'pattuMugappupPakkam': 'பட்டு முகப்புப் பக்கம்',
  'pattupattiyalthiruthi': 'பட்டுப் பட்டியல் திருத்தி (GST முறை)',
  'pudhiyaPattupPattiyal': 'புதிய பட்டுப் பட்டியல்',
  'pattupPorulThiruthi': 'பட்டுப் பொருள் திருத்தி',
  'pudhiyaPattupPorul': 'புதிய பட்டுப் பொருள்',
  'pattuVanigarThiruthi': 'பட்டு வணிகர் திருத்தி',
  'pudhiyaPattuVanigar': 'புதிய பட்டு வணிகர்',
  'pattupPatrucheettuThiruthi': 'பட்டுப் பற்றுச்சீட்டு திருத்தி',
  'pudhiyaPattupPatrucheettu': 'புதிய பட்டுப் பற்றுச்சீட்டு',
  'mothaKanakku': 'மொத்தக் கணக்கு',
  'niruvanangal': 'நிறுவனங்கள்',
  'mothaPattiyalgal': 'மொத்தப் பட்டியல்கள்',
  'variThirattiyavai': 'வரி திரட்டியவை',
  'pattiyalEnnikai': 'பட்டியல் எண்ணிக்கை',
  'arugilSeyalgal': 'அண்மைச் செயல்கள்',
  'anaiththaiyumPaarPtn': 'அனைத்தையும் பார்',
  'pattiyalgalIllai': 'பட்டியல்கள் இல்லை',
  'uruvaakkunarTharavugalaiAzhi': 'உருவாக்குனர்: தரவுகளை அழி',
  'uruvaakkunarTharavugalaiUruvaakku': 'உருவாக்குனர்: தரவுகளை உருவாக்கு',
  'tharavugalaiUruvaakkuUruvaakkunar': 'தரவுகளை உருவாக்கு (உருவாக்குனர்)',
  'vanigapeyaraiullidu': 'தேவையான அனைத்து வணிகப் பெயர்களையும் உள்ளிடவும்.',
  'gstinVariAdaiyaalaEn': 'GSTIN / வரி அடையாள எண்',
  'elvanParthasarathy': 'எல்வன் பார்த்தசாரதி',

  // === Porul (Product) Keys ===
  'porulTharavugal': 'பொருள் தரவுகள்',
  'vilaiMatrumVari': 'விலை மற்றும் வரி',
  'alavuVagai': 'அளவு வகை',
  'alavu': 'அளவு',
  'edai': 'எடை',
  'hsnSacKuriyeedu': 'HSN/SAC குறியீடு',
  'vilai': 'விற்பனை விலை',
  'gstVeedham': 'GST வீதம் %',
  'porulPeyarThaevai': 'பொருள் பெயர் தேவை',
  'porulChaemikkappattadhu': 'பொருள் சேமிக்கப்பட்டது',
  'porulAzhikkappattadhu': 'பொருள் அழிக்கப்பட்டது',
  'porulgalIllai': 'பொருட்கள் இல்லை',
  'porulaiChaerkkavum': 'முதல் பொருளைச் சேர்க்கவும்',

  // ── Meetpagam (Recycle Bin) ──
  'meetpagam': 'மீட்பகம்',
  'meetpagamKaaliyanadhu': 'மீட்பகம் காலியானது',
  'meeteduppuVetri': 'வெற்றிகரமாக மீட்கப்பட்டது',
  'meeteduppuCheiPtn': 'மீட்டெடு',
  'nirandharaAzhippu': 'நிரந்தரமாக அழி',
  'nirandharaAzhippuUrudhi': 'நிரந்தரமாக அழிக்கவா? மீட்க இயலாது.',
  'azhikkappattaPorulgal': 'அழிக்கப்பட்ட பொருள்கள்',
  'meetpagam30Naal': 'மீட்பகத்தில் உள்ளவை 30 நாள்களுக்குப் பிறகு தானாகவே அழிக்கப்படும்',

  // === Vanigar (Merchant) CRUD Keys ===
  'vanigarTharavugal': 'வணிகத் தரவுகள்',
  'vanigarPeyar': 'வணிகர் பெயர்',
  'vanigarPeyarThaevai': 'வணிகர் பெயர் தேவை',
  'vanigarChaemikkappattadhu': 'வணிகர் சேமிக்கப்பட்டது',
  'vanigarAzhikkappattadhu': 'வணிகர் அழிக்கப்பட்டது',
  'vanigargalIllai': 'வணிகர்கள் இல்லை',
  'vanigaraiChaerkkavum': 'முதல் வணிகரைச் சேர்க்கவும்',
  'azhikkappattaVanigargal': 'அழிக்கப்பட்ட வணிகர்கள்',
  'thodarpuVari': 'தொடர்பு & வரி',
  'velinaadMugavari': 'முழு முகவரி',
  'gstinTavaru': 'GSTIN வடிவம் தவறானது',
  'thanipPayanPtn': 'தனிப்பயன்',
  'tholaipaesi': 'தொலைபேசி',
  'anaithaiyumTheriPtn': 'அனைத்தையும் தேர்',
};
