const Map<String, String> tg = {
  'nirilirkuNalvaravu': 'Nirilirku Nalvaravu',
  'pattiyalgstelidhu': 'Ungal Pattiyalgal & GST, Elidhaakkappattadhu.',
  'nirilthodanga': 'Nirilai Thodanga Keezh Ulla Pothaanai Thattavum',
  'pudhiyadhaagaThodanguPtn': 'Pudhiyadhaaga Thodangu',
  'mozhiThaervu': 'Mozhiyaith Thaerndhedu',
  'viruppaMozhiThaervu': 'Viruppamaana Mozhiyaith Thaervu Cheiga',

  // ========================================
  // Help Center
  // ========================================
  'niruvanathinPeyar': 'Niruvanathin Peyar',
  'vanigargal': 'Vanigargal',
  'porutkal': 'Porutkal',
  'pattiyalgal': 'Pattiyalgal',
  'patrucheettugal': 'Patrucheettugal',
  'arikkai': 'Arikkai',
  'variArikkai': 'Vari Arikkai',

  // ========================================
  // Settings & Preferences
  // ========================================
  'amaippugal': 'Amaippugal',

  'veliyaeru': 'Veliyaeru',
  'cheyaliMozhi': 'Cheyali Mozhi',
  'vangiyinPeyar': 'Vangiyin Peyar',
  'thannuruNeekkappattadhu': 'Thannuru Neekkappattadhu',
  'perumalavu5thannuru': 'Perumalavu 5 Thannurukkal Mattumae',
  'tharpoadhaiyaNiruvanam': 'Tharpoadhaiya Niruvanam',
  'pudhiyaThannuruvaiUruvaakku': 'Pudhiya Thannuruvai Uruvaakku',
  'thannuruvaiMutrilumNeekkavaa': 'Thannuruvai Mutrilum Neekkavaa?',
  'pudhiyaThannuruChaer': 'Pudhiya Thannuru Chaer',
  'thannuruChaemikkappattadhu': 'Thannuru Chaemikkappattadhu!',
  'thannurukkalIllai': 'Thannurukkal Illai',
  'kanakkuEn': 'Kanakku En',
  'pdfThoatram': 'PDF Thoatram',
  'pattiyalPatrucheettuMozhi': 'Pattiyal & Patrucheettu Mozhi',
  'kadavuchol': 'Kadavuchol',
  'kadavuchollaiUllidavum': 'Kadavuchollai Ullidavum',
  'kanakkuEnIfsc': 'Vangi Tharavugal',
  'thamizhAangilamThaaniyangu': 'Thamizh, Aangilam, Thaaniyangu',
  'thaekkagathaiazhi': 'Kaappu Nagal, Veliyaeru, Tharavu Azhi',
  'elvanPatriMaelumAriga': 'Elvan Patri Maelum Ariga',
  'cheyaliyilirundhuVeliyaeravum': 'Cheyaliyilirundhu Veliyaeravum.',
  'tharavuKaappuChei': 'Tharavu Kaappu Chei',
  'ungalTharavaiChaemikkavum': 'Ungal Tharavai Chaemikkavum.',
  'tharavuKaappu': 'Tharavu Kaappu',
  'kaappuCheiPtn': 'Kaappu Chei',
  'tharavuchaemippuvetri': 'Tharavu Aavanangalil Chaemikkappattadhu.',
  'mudhanmaiMozhi': 'Mudhanmai Mozhi',
  'irandaamMozhi': 'Irandaam Mozhi',

  // ========================================
  // Merchants & Customers
  // ========================================
  'vanigar': 'Vanigar',

  'minnanjal': 'Minnanjal',
  'vanigaraichChaer': 'Vanigaraich Chaer',
  'oor': 'Oor',
  'maavattam': 'Maavattam',
  'appPeyar': 'Elvan Niril',
  'elvanNiril': 'Elvan Niril',
  'maanilam': 'Maanilam',
  'naadu': 'Naadu',
  'paesiEnkal': 'Paesi Enkal',
  'anjalKuriyeedu': 'Anjal Kuriyeedu',
  'minnanjalaiUrudhiseiga': 'Minnanjalai Urudhiseiga',
  'minnanjalMugavari': 'Minnanjal Mugavari',
  'minnanjalaiUllidavum': 'Minnanjalai Ullidavum',
  'mugavaritharavugal': 'Niruvana Mugavarith Tharavugal',

  // ========================================
  // Inventory & Items
  // ========================================
  'porul': 'Porul',

  'porulaichChaerPtn': 'Porulaich Chaer',
  'gstpirippugal': 'GST Pirippugalaik Kaattu',
  'pattiyal': 'Pattiyal',
  'pudhiyaPattiyal': 'Pudhiya Pattiyal',
  'patrucheettu': 'Patrucheettu',
  'pudhiyaPattiyalPtn': 'Pudhiya Pattiyal',
  'pudhiyaPatrucheettuPtn': 'Pudhiya Patrucheettu',
  'veliyaetramvetri': 'Vetrigaramaaga Veliyaetrappattadhu',
  'azhippuvetri': 'Tharavu Vetrigaramaaga Azhikkappattadhu.',
  'chaemippuvetri': 'Vetrigaramaagach Chaemikkappattadhu',
  'pilVadivamaippuViruppangal': 'PDF Vadivamaippu Viruppangal',
  'chinnathinVadivam': 'Oavuruvin Vadivam',
  'meetteduppuvetri': 'Tharavu Vetrigaramaaga Meettedukkappattadhu!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'arikkaigal': 'Arikkaigal',
  'variArikkaigal': 'Vari Arikkaigal',
  'chaer': 'Chaer',
  'thaeduga': 'Thaeduga...',
  'kaividuPtn': 'Kaividu',
  'neekkuPtn': 'Neekku',
  'chaemiPtn': 'Chaemi',
  'aakku': 'Aakku',
  'oavuruIllai': 'Oavuru Illai',
  'kaiyoppamIllai': 'Kaiyoppam Illai',
  'uruvaakkuPtn': 'Uruvaakku',
  'illai': 'Illai',
  'thaerndhedu': 'Thaerndhedu',
  'tharavugalChaemippuVetri': 'Tharavugal Vetrigaramaaga Chaemikkappattana',
  'kanakkuppagudhi': 'Ungal Kanakkup Pagudhiyaith Thaerndhedukkavum',
  'veliyaeruPtn': 'Veliyaeru',
  'tharavaiAzhiPtn': 'Tharavai Azhi',
  'veliyaeraVaendumaa': 'Veliyaera Vaendumaa?',
  'thodangugaPtn': 'Thodanguga',
  'meetteduPtn': 'Meettedu',

  // ========================================
  // Miscellaneous
  // ========================================
  'niril': 'Niril',
  'thodaravum': 'Thodaravum',
  'gstin': 'GSTIN',
  'language': 'Mozhi',
  'kaapputhTharavuKidaithadhu': 'Kaapputh Tharavu Kidaithadhu!',
  'kaapputhTharavuThaedal': 'Kaapputh Tharavu Thaedappadugiradhu...',
  'kaapputhTharavuIllai':
      'Kaapputh Tharavu Illai, Pudhidhaaga Thodangugiradhu.',
  'mugappu': 'Mugappu',
  'mugavari': 'Mugavari',
  'irulNilai': 'Irul Nilai',
  'oliNilai': 'Oli Nilai',
  'ifscKuriyeedu': 'IFSC Kuriyeedu',
  'kilaipPeyar': 'Kilaip Peyar',
  'thamizh': 'Thamizh',
  'aangilam': 'Aangilam',
  'tamil': 'Thamizh',
  'english': 'Aangilam',
  'tamilLatin': 'Thamizh Latin',
  'niruvanathinOavuru': 'Niruvanathin Oavuru',
  'kaiyoppam': 'Kaiyoppam',
  'paesiEn': 'Paesi En',
  'maatruPaesiEn': 'Maatru Paesi En',
  'kurugiyaNiruvanaPeyar': 'Kurugiya Niruvanap Peyar',
  'adaimozhi': 'Adaimozhi',
  'nirilKooli': 'Niril Kooli',
  'nirilPattu': 'Niril Pattu',
  'meendumThaedu': 'Meendum Thaedu',
  'veliyaerugiradhu': 'Veliyaerugiradhu...',
  'aluvalkaiyoppam': 'Aluval Kaiyoppathin Peyar',
  'neriyuga': 'Neriyuga',
  'pachai': 'Pachai',
  'oodhaa': 'Oodhaa',
  'azhikkiradhu': 'Azhikkiradhu...',
  'vanakkam': 'Vanakkam!',
  'indruEndhakKanakku': 'Indru Endhak Kanakku?',
  'cheyaliyaiAnugaUlnuzhaiyavum': 'Cheyaliyai Anuga Ulnuzhaiyavum',
  'ulnuzhaiga': 'Ulnuzhaiga',
  'tharavugalaiUllidu': 'Anaithu Tharavugalaiyum Ullidavum.',
  'pattiyalMudhanmozhi': 'Pattiyal Mudhanmozhi',
  'pattiyalmozhi': 'Pattiyalil Emmozhiyai Payanbadutha Vaendum?',
  'tharavugalaiUlliduga': 'Tharavugalai Ulliduga',
  'peyaraiUlliduga': 'Peyarai Ulliduga',
  'gstpattiyalukku': 'Vazhakkamaana GST Pattiyalgalukkup Payanbaduthappadum.',
  'kooliNiruvanaPeyar': 'Kooli Niruvanap Peyar',
  'koolipattiyalukku':
      'Kooli Pattiyalgal Matrum Patrucheettugalukkup Payanbaduthappadum.',
  'niruvanam': 'Niruvanam',
  'niruvanaAmaippugal': 'Niruvana Amaippugal',
  'vangi': 'Vangi',
  'cheyaliAmaippugal': 'Cheyali Amaippugal',
  'thirai': 'Thirai',
  'paadhugaappu': 'Paadhugaappu',
  'menporulVadivaalar': 'Menporul Vadivaalar',
  'cheyaliPatri': 'Cheyali Patri',
  'cheyalipadhippu': 'Cheyaliyin Padhippu matrum Tharavugal',
  'peyarEarkanavaeUlladhu': 'ippeyar aerkkanavae ulladhu.',
  'adaiyaalam': 'Adaiyaalam',
  'kooliNiruvanaAdaiyaalangal': 'Kooli Niruvana Adaiyaalangal',
  'pattuNiruvanaAdaiyaalangal': 'Pattu Niruvana Adaiyaalangal',
  'olirIrulThaaniyangu': 'Oli irul Thaaniyangu',
  'cheyalithTharavaiAzhi': 'Cheyalith Tharavai Azhi',
  'tharavaiazhi': 'Tharavugalai Mutrilum Azhikkavum.',
  'chaemikkappadugiradhu': 'Chaemikkappadugiradhu...',
  'irumozhiMurai': 'Irumozhi Murai',
  'thaaniyangiAmaippu': 'Thaaniyangi Amaippu',
  'agalamaanaoavuru': 'Chenguthu / Agalamaana Oavuru',
  'chiriyaOavuruPeyar': 'Chiriya Oavuru + Peyar',
  'agalamaanaOavuruMattum': 'Agalamaana Oavuru Mattum',
  'padhivaetru': 'Padhivaetru',
  'pazhaiyaTharavuKidaikkiradhu': 'Pazhaiya Tharavu Kidaikkiradhu',
  'pazhaiyaTharavaiMeettedukkavaa': 'Pazhaiya Tharavai Meettedukkavaa?',
  'tharavaiMeettedukkiradhu': 'Tharavai Meettedukkiradhu...',

  // === Auto Added Keys ===
  'pugaippadakKaruvi': 'Pugaippadak Karuvi',
  'pugaippadathThoguppu': 'Pugaippadath Thoguppu',
  'padammoolam': 'Padathin Moolathaith Thaerndhedukkavum',
  'menporulVadivaalarPatri': 'Menporul Vadivaalar Patri',
  'cheyaliPatriMaadhiri': 'Cheyali Patri (Maadhiri)',
  'menporulVadivaalarPatriMaadhiri': 'Menporul Vadivaalar Patri (Maadhiri)',
  'kooliMugappupPakkam': 'Kooli Mugappup Pakkam',
  'koolipattiyalthiruthi': 'Koolip Pattiyal Thiruthi (Thozhilaalar Murai)',
  'pudhiyaKoolipPattiyal': 'Pudhiya Koolip Pattiyal',
  'koolipPorulThiruthi': 'Koolip Porul Thiruthi',
  'pudhiyaKoolipPorul': 'Pudhiya Koolip Porul',
  'kooliVanigarThiruthi': 'Kooli Vanigar Thiruthi',
  'pudhiyaKooliVanigar': 'Pudhiya Kooli Vanigar',
  'koolipPatrucheettuThiruthi': 'Koolip Patrucheettu Thiruthi',
  'pudhiyaKoolipPatrucheettu': 'Pudhiya Koolip Patrucheettu',
  'pattuMugappupPakkam': 'Pattu Mugappup Pakkam',
  'pattupattiyalthiruthi': 'Pattup Pattiyal Thiruthi (GST Murai)',
  'pudhiyaPattupPattiyal': 'Pudhiya Pattup Pattiyal',
  'pattupPorulThiruthi': 'Pattup Porul Thiruthi',
  'pudhiyaPattupPorul': 'Pudhiya Pattup Porul',
  'pattuVanigarThiruthi': 'Pattu Vanigar Thiruthi',
  'pudhiyaPattuVanigar': 'Pudhiya Pattu Vanigar',
  'pattupPatrucheettuThiruthi': 'Pattup Patrucheettu Thiruthi',
  'pudhiyaPattupPatrucheettu': 'Pudhiya Pattup Patrucheettu',
  'mothaKanakku': 'Mothak Kanakku',
  'niruvanangal': 'Niruvanangal',
  'mothaPattiyalgal': 'Mothap Pattiyalgal',
  'variThirattiyavai': 'Vari Thirattiyavai',
  'pattiyalEnnikai': 'Pattiyal Ennikkai',
  'patrucheettuEnnikai': 'Patrucheettu Ennikkai',
  'arugilSeyalgal': 'Nadappu Vinaigal',
  'anaiththaiyumPaarPtn': 'Yaavum',
  'pattiyalgalIllai': 'Pattiyalgal Illai',
  'uruvaakkunarTharavugalaiAzhi': 'Uruvaakkunar: Tharavugalai Azhi',
  'uruvaakkunarTharavugalaiUruvaakku': 'Uruvaakkunar: Tharavugalai Uruvaakku',
  'tharavugalaiUruvaakkuUruvaakkunar': 'Tharavugalai Uruvaakku (Uruvaakkunar)',
  'niruvanapeyaraiullidu':
      'Thaevaiyaana Anaithu Niruvanap Peyargalaiyum Ullidavum.',
  'gstinVariAdaiyaalaEn': 'GSTIN / Vari Adaiyaala En',
  'elvanParthasarathy': 'Elvan Parthasarathy',

  // === Porul (Product) Keys ===
  'porulTharavugal': 'Porul Tharavugal',
  'vilaiMatrumVari': 'Vilai matrum Vari',
  'alavuVagai': 'Alavu Vagai',
  'alavu': 'Alavu',
  'edai': 'Edai',
  'hsnSacKuriyeedu': 'HSN/SAC Kuriyeedu',
  'vilai': 'Vilai',
  'gstVeedham': 'GST Veedham %',
  'porulPeyarThaevai': 'Porul Peyar Thaevai',
  'porulChaemikkappattadhu': 'Porul Chaemikkappattadhu',
  'porulAzhikkappattadhu': 'Porul Azhikkappattadhu',
  'porulgalIllai': 'Porutkal Illai',
  'porulaiChaerkkavum': 'Mudhal Porulai Chaerkkavum',

  // ── Meetpagam (Recycle Bin) ──
  'meetpagam': 'Meetpagam',
  'meetpagamKaaliyanadhu': 'Meetpagam Kaaliyanadhu',
  'meeteduppuVetri': 'Vetrigaramaaga Meetkappattadhu',
  'meeteduppuCheiPtn': 'Meetteduppu Chei',
  'nirandharaAzhippu': 'Nirandharamaaga Azhi',
  'nirandharaAzhippuUrudhi': 'Nirandharamaaga Azhikkavaa? Meetka Iyalaadhu.',
  'azhikkappattaPorulgal': 'Azhikkappatta Porulgal',
  'meetpagam30Naal': 'Meetpagatthil Ullavai 30 Naalgalukku Piragu Thaanaagavae Azhikkapppadum',

  // === Vanigar (Merchant) CRUD Keys ===
  'vanigarTharavugal': 'Vanigath Tharavugal',
  'vanigarPeyar': 'Vanigar Peyar',
  'vanigarPeyarThaevai': 'Vanigar Peyar Thaevai',
  'vanigarChaemikkappattadhu': 'Vanigar Chaemikkappattadhu',
  'vanigarAzhikkappattadhu': 'Vanigar Azhikkappattadhu',
  'vanigargalIllai': 'Vanigargal Illai',
  'vanigaraiChaerkkavum': 'Mudhal Vanigaraich Chaerkkavum',
  'azhikkappattaVanigargal': 'Azhikkappatta Vanigargal',
  'thodarpuVari': 'Thodarbu & Vari',
  'velinaadMugavari': 'Muzhu Mugavari',
  'gstinTavaru': 'GSTIN Vadivam Thavaraanadhu',
  'thanipPayanPtn': 'Thanippayan',
  'tholaipaesi': 'Tholaippaesi',
  'anaithaiyumTheriPtn': 'Anaithaiyum Theri',

  // ── Payanar (User Profile) ──
  'payanar': 'Payanar',
  'payanarAmaippugal': 'Payanar Amaippugal',
  'mudhalPeyar': 'Mudhal Peyar',
  'irudhiPeyar': 'Irudhi Peyar',
  'pirandhaThaedhi': 'Pirandha Thaedhi',
  'payanarTharavugalaiMaetriduPtn': 'Chaemi',
  'payanarVilakkam': 'Ippeyar Mugappu Thiraiyil Thoandrum.',
};
