const Map<String, String> en = {
  // ========================================
  // Setup Wizard & Welcome
  // ========================================
  'welcomeBack': 'Welcome back!',
  'hc_orStartManually': 'Or start manually:',
  'hc_inStartMenu': 'in Start Menu',
  'hc_startingThisPageWillOpen': 'Starting... this page will open automatically.',
  'hc_welcomeToElvanNiril': 'Welcome to Elvan Niril',
  'quickStartTemplate': 'QUICK START TEMPLATES',
  'indiaSpecificStarter': 'India Specific Starter',
  'welcomeTitle': 'Welcome to Niril',
  'welcomeSubtitle': 'Your Billing & GST, Sorted.',
  'welcomeAgreeText': 'Tap "Get Started" to continue with Niril.',
  'startFreshBtn': 'Start Fresh',

  // ========================================
  // Help Center
  // ========================================
  'hc_100Safe': '100% safe',
  'hc_1Doubleclick': '1. Double-click',
  'hc_onYourDesktop': 'on your Desktop',
  'hc_2OrSearch': '2. Or search',
  'hc_typeACommandOrPage': 'Type a command or page name…',
  'hc_yourDataIsSafe': 'Your data is safe.',
  'hc_updatesOnlyRefreshTheApp': 'Updates only refresh the app code and dependencies — your',
  'hc_pdfArchiveAre': 'PDF archive are',
  'hc_neverTouched': 'never touched',
  'hc_githubReleases': 'GitHub Releases',
  'hc_recommended': 'Recommended:',
  'hc_exportBackup': 'Export Backup…',
  'hc_skipThisVersion': 'Skip this version',
  'hc_viewOnGithub': 'View on GitHub',
  'hc_updateNow': 'Update Now',
  'hc_launches': 'launches',
  'hc_devSwitchBilingualLanguage': 'DEV: Switch bilingual language',
  'hc_devLanguageSwitcher': 'DEV: Language Switcher',
  'hc_primaryLanguage': 'Primary Language',
  'hc_secondaryLanguage': 'Secondary Language',
  'hc_bilingualMode': 'Bilingual Mode',
  'hc_uiLanguage': 'UI Language',
  'hc_enterCustomerName': 'Enter Customer Name',
  'hc_enterCountryName': 'Enter country name',
  'hc_active': 'Active',
  'hc_yourExistingBankDetailsAre': 'Your existing bank details are still on this profile.',
  'hc_defaultAccount': 'Default account',
  'hc_inactive': 'Inactive',
  'hc_setAsDefault': 'Set as default',
  'hc_moveUp': 'Move up',
  'hc_moveDown': 'Move down',
  'hc_egAaaaa1234a': 'e.g. AAAAA1234A',
  'hc_egHdfcCurrent1234': 'e.g. HDFC Current — 1234',
  'hc_bankName': 'Bank Name',
  'hc_egHdfcinbb': 'e.g. HDFCINBB',
  'hc_egYourbusinesshdfcbank': 'e.g. yourbusiness@hdfcbank',
  'hc_egUseForExportClients': 'e.g. Use for export clients only',
  'hc_setAsDefaultAccount': '⭐ Set as default account',
  'hc_preview': 'Preview:',
  'hc_formatStyle': 'Format Style',
  'hc_brandPrefix': 'Brand Prefix',
  'hc_egAcmeBk': 'e.g. ACME, BK',
  'hc_separator': 'Separator',
  'hc_prefix': 'Prefix',
  'hc_egRcpR': 'e.g. RCP, R',
  'hc_googleOauthClientId': 'Google OAuth Client ID',
  'hc_openGoogleCloudConsole': 'Open Google Cloud Console',
  'hc_driveFolderName': 'Drive Folder Name',
  'hc_status': 'Status',
  'hc_yourDataWillNotBe': 'Your data will not be affected. Click below to update:',
  'hc_preferences': 'Preferences',
  'hc_uiLanguageDataLanguages': 'UI language, Data languages',
  'hc_accountsInvoiceFormatsTerms': 'Accounts, Invoice formats, Terms',
  'hc_advanced': 'Advanced',
  'hc_appVersionsCache': 'App versions, Cache',
  'hc_selectASetting': 'Select a setting',
  'hc_exportBackup1': 'Export Backup',
  'hc_alsoSaveACopyTo': 'Also save a copy to my Google Drive',
  'hc_downloadBackup': 'Download Backup',
  'hc_restoreFromBackup': 'Restore from Backup',
  'hc_overwriteMatchingRecordsById': 'overwrite matching records by ID',
  'hc_businessDetails': 'Business Details',
  'hc_businessName': 'Business Name',
  'hc_egSharmaConsultantsPvtLtd': 'e.g. Sharma Consultants Pvt. Ltd.',
  'hc_eg42MgRoadSector': 'e.g. 42, MG Road, Sector 15, Gurugram 122001',
  'hc_neededForAutoCgstsgstVs': 'Needed for auto CGST/SGST vs IGST',
  'hc_phoneMobile': 'Phone / Mobile',
  'hc_egHdfcBank': 'e.g. HDFC Bank',
  'hc_accountNumber': 'Account Number',
  'hc_eg12345678901234': 'e.g. 12345678901234',
  'hc_ifscCode': 'IFSC Code',
  'hc_egHdfc0001234': 'e.g. HDFC0001234',
  'hc_upiId': 'UPI ID',
  'hc_egBusinessupi': 'e.g. business@upi',
  'hc_businessLogo': 'Business Logo',
  'hc_pngjpgMax500kb': 'PNG/JPG, max 500KB',
  'hc_digitalSignature': 'Digital Signature',
  'hc_youreAllSet': 'You\'re all set!',
  'hc_openSidebar': 'Open sidebar',
  'hc_closeSidebar': 'Close sidebar',
  'hc_paymentReceipt': 'PAYMENT RECEIPT',
  'hc_egAcmeCorp': 'e.g. Acme Corp',
  'hc_addressInEnglish': 'Address in English',
  'hc_cityInEnglish': 'City in English',
  'hc_countryInEnglish': 'Country in English',
  'hc_taxDataExport': 'Tax Data Export',
  'hc_fullYear': 'Full Year',
  'hc_totalInvoices': 'Total Invoices',
  'hc_taxCollected': 'Tax Collected',
  'hc_netPayable': 'Net Payable',
  'hc_invoicesForThisPeriod': 'Invoices for this Period',
  'hc_noInvoicesFoundForThis': 'No invoices found for this period.',
  'hc_invoiceNo': 'Invoice No',
  'hc_client': 'Client',
  'hc_taxableValue': 'Taxable Value',
  'hc_taxAmount': 'Tax Amount',
  'hc_type': 'Type',
  'hc_b2bTotal': 'B2B Total',
  'hc_creditdebitNotesTable9b': 'Credit/Debit Notes — Table 9B',
  'hc_noteNo': 'Note No',
  'hc_noItemsFound': 'No items found.',
  'hc_noDocumentsIssued': 'No documents issued.',
  'hc_natureOfSupplies': 'Nature of Supplies',
  'hc_na': 'N/A',
  'hc_table32IntermaanilamSuppliesTo': 'Table 3.2 — Inter-maanilam Supplies to Unregistered Persons',
  'hc_placeOfSupply': 'Place of Supply',
  'hc_details': 'Details',
  'hc_netItcAvailable': 'Net ITC Available',
  'hc_table6TaxPaymentSummary': 'Table 6 — Tax Payment Summary',
  'hc_outputTaxLiability': 'Output Tax Liability',
  'hc_lessItcClaimed': 'Less: ITC Claimed',
  'hc_netTaxPayable': 'Net Tax Payable',
  'hc_netGstPayable': 'Net GST Payable',
  'hc_howToUse': 'How to use:',
  'hc_import2bJson': 'Import 2B JSON',
  'hc_purchaseBills': 'Purchase Bills',
  'hc_importYourGstr2bJsonTo': 'Import your GSTR-2B JSON to reconcile against your purchase records.',
  'hc_supplier': 'Supplier',
  'hc_invoiceNo1': 'Invoice No.',
  'hc_2bValue': '2B Value',
  'hc_booksValue': 'Books Value',
  'hc_diff': 'Diff',
  'hc_noEntriesMatchThisFilter': 'No entries match this filter.',
  'hc_whatThisIs': 'What this is:',
  'hc_form26q': 'Form 26Q',
  'hc_form27eq': 'Form 27EQ',
  'hc_invoicesWithTds': 'Invoices with TDS',
  'hc_totalTdsReceivable': 'Total TDS receivable',
  'hc_quarter': 'Quarter',
  'hc_section': 'Section',
  'hc_customizeTds': 'Customize → TDS',
  'hc_invoicesWithTcs': 'Invoices with TCS',
  'hc_totalTcsCollected': 'Total TCS collected',
  'hc_customizeTcs': 'Customize → TCS',
  'hc_steps': 'Steps:',
  'hc_dueR1By11th3b': '| Due: R1 by 11th, 3B by 20th of next month | Late fee: ₹50/day',
  'hc_gstr1ProTips': 'GSTR-1 Pro Tips',
  'hc_fastestMethod': 'Fastest method:',
  'hc_exportGstr1JsonFromThe': 'Export GSTR-1 JSON from the GSTR-1 tab above → Go to GST portal → GSTR-1 → Prepare Offline → Download Offline Tool → Import JSON → Upload. Saves 90% of time.',
  'hc_gstr3bProTips': 'GSTR-3B Pro Tips',
  'hc_fromJuly2025': 'From July 2025:',
  'hc_table3AutopopulatesFromGstr1': 'Table 3 auto-populates from GSTR-1 — just VERIFY, don\'t re-enter values.',
  'hc_itcMatching': 'ITC matching:',
  'hc_alwaysCheckGstr2bStatementBefore': 'Always check GSTR-2B statement BEFORE claiming ITC. Go to Returns → GSTR-2B → Download. Only claim ITC that appears in GSTR-2B.',
  'hc_payment': 'Payment:',
  'hc_interestCalculation': 'Interest calculation:',
  'hc_reverseCharge': 'Reverse charge:',
  'hc_whenToFileNilReturn': 'When to File NIL Return',
  'hc_youHad': 'You had',
  'hc_zeroOutwardSupplies': 'ZERO outward supplies',
  'hc_youHave': 'You have',
  'hc_noInputTaxCredit': 'NO input tax credit',
  'hc_toClaim': 'to claim',
  'hc_noTaxLiability': 'NO tax liability',
  'hc_noInwardSupplies': 'NO inward supplies',
  'hc_liableToReverseCharge': 'liable to reverse charge',
  'hc_ifAnyOfTheAbove': 'If ANY of the above has a value, you MUST file a regular return — not NIL',
  'hc_nilGstr3bFileAfterNil': 'NIL GSTR-3B — File After NIL GSTR-1',
  'hc_nilReturnQuickSummary': 'NIL Return Quick Summary',
  'hc_nilGstr1AndNilGstr3b': 'NIL GSTR-1 and NIL GSTR-3B are',
  'hc_separateReturns': 'separate returns',
  'hc_fileBoth': '— file both',
  'hc_nilFilingTakes23Minutes': 'NIL filing takes 2-3 minutes per return — just login, verify zeros, submit, file',
  'hc_youCanFileNilReturns': 'You can file NIL returns via SMS: Send',
  'hc_nilSpaceGstinSpaceReturn': 'NIL space GSTIN space Return Period',
  'hc_to14409VerifyWithOtp': 'to 14409. Verify with OTP.',
  'hc_qrmpUsersFilingQuarterlyNil': 'QRMP users filing quarterly: NIL return covers the entire quarter',
  'hc_keyGstRulesToRemember': 'Key GST Rules to Remember',
  'hc_itcForAnyInvoiceMust': 'ITC for any invoice must be claimed by the due date of September return of the following FY, or the date of filing annual return — whichever is earlier.',
  'hc_section34': 'Section 34:',
  'hc_creditNotesMustBeIssued': 'Credit notes must be issued before September 30 following the end of FY of the original invoice or annual return filing — whichever is earlier.',
  'hc_section31': 'Section 31:',
  'hc_taxInvoiceMustBeIssued': 'Tax invoice must be issued at or before the time of supply. For services, within 30 days of supply.',
  'hc_section49': 'Section 49:',
  'hc_itcCanOnlyBeClaimed': 'ITC can only be claimed for invoices that appear in GSTR-2B. No provisional ITC beyond GSTR-2B.',
  'hc_section50': 'Section 50:',
  'hc_section7374': 'Section 73/74:',
  'hc_ewayBill': 'E-way Bill:',
  'hc_cannotGenerateEwayBillsIf': 'Cannot generate e-way bills if GSTR-3B not filed for 2+ consecutive months.',
  'hc_bulletList': 'Bullet list',
  'hc_numberedList': 'Numbered list',
  'hc_heading': 'Heading',
  'hc_paragraph': 'Paragraph',
  'hc_insertLink': 'Insert link',
  'hc_clearFormatting': 'Clear formatting',
  'hc_allChangesSaved': 'All changes saved',
  'hc_addAClientNameAnd': 'Add a client name and at least one item to start saving',
  'hc_sacCode': 'SAC code',
  'hc_invoiceTitle': 'Invoice Title',
  'hc_currency': 'Currency',
  'hc_paymentAccountOnThisInvoice': 'Payment account on this invoice',
  'hc_pdfStyle': 'PDF Style',
  'hc_accentColor': 'Accent Color',
  'hc_hideAll': 'Hide all',
  'hc_savedCustomer': 'Saved Customer',
  'hc_tempCustomer': 'Temp Customer',
  'hc_savedClientDetails': 'Saved Client Details',
  'hc_maanilamRegion': 'maanilam / Region',
  'hc_originalInvoiceReference': 'Original Invoice Reference',
  'hc_egInv2025260001': 'e.g. INV/2025-26/0001',
  'hc_savedItem': 'Saved Item',
  'hc_tempItem': 'Temp Item',
  'hc_searchSavedItems': 'Search saved items...',
  'hc_savedItemDetails': 'Saved Item Details',
  'hc_hsnsac': 'HSN/SAC:',
  'hc_unit': 'Unit:',
  'hc_tax': 'Tax:',
  'hc_cess': 'Cess:',
  'hc_addCustom': '＋ Add custom…',
  'hc_remove': 'Remove',
  'hc_saveChangesBeforeClosing': 'Save changes before closing?',
  'hc_forEstimationPurposesOnly': 'For estimation purposes only',
  'hc_against': 'Against:',
  'hc_thisIsNotATax': 'This is not a tax invoice. For estimation purposes only.',
  'hc_againstInvoice': 'Against Invoice:',
  'hc_disc': 'Disc.',
  'hc_subtotal': 'Subtotal',
  'hc_gstCess': 'GST Cess',
  'hc_roundoff': 'Round-off',
  'hc_netReceivable': 'Net Receivable',
  'hc_reverseChargeApplicable': 'Reverse Charge applicable.',
  'hc_exchangeRate': 'EXCHANGE RATE',
  'hc_discardChanges': 'Discard Changes',
  'hc_discardWarning': 'Are you sure you want to discard your unsaved changes?',
  'hc_cancel': 'Cancel',
  'hc_discard': 'Discard',
  'hc_addNewProduct': 'Add New Product',
  'hc_addNewClient': 'Add New Customer',

  // ========================================
  // Navigation & Shell
  // ========================================
  'header_invoices': 'Invoices',
  'accountingGroup': 'Accounting',
  'reportsGroup': 'Reports & GST',
  'coolieBill': 'Coolie Bill',
  'silksBill': 'Grocery Bill',
  'header_merchants': 'Merchants',
  'header_inventory': 'Products',
  'header_receipts': 'Receipts',
  'pill_invoices': 'Invoices',
  'pill_receipts': 'Receipts',
  'reportsSidebar': 'Report',
  'gstReturnsSidebar': 'GST Return',

  // ========================================
  // Settings & Preferences
  // ========================================
  'print': 'Print',
  'settings': 'Settings',
  'logout': 'Logout',
  'appLanguage': 'App Language',
  'businessProfile': 'Business Profile',
  'bankDetails': 'Bank Details',
  'companyName': 'Company Name',
  'accountNo': 'Account No',
  'settingsTitle': 'Settings',
  'settingsSubtitle': 'Business profile, branding, integrations & data',
  'settingsDesc': 'Manage your app settings and preferences.',
  'switchProfile': 'Switch Profile',
  'language': 'Language',
  'appPreferences': 'App Preferences',
  'bankName': 'Bank Name',
  'appLanguageAppearance': 'App language and appearance settings',
  'uiLanguageTheme': 'UI language, Theme',
  'languageChangedTa': 'மொழி தமிழுக்கு மாற்றப்பட்டது',
  'languageChangedEn': 'Language changed to English',
  'appVersionsCache': 'App versions, Backup, Cache',
  'appearance': 'Appearance',
  'account': 'Account',
  'profile': 'Profile',
  'security': 'Security',
  'dataBackup': 'Data Backup',
  'cloudSync': 'Cloud Sync',
  'about': 'About',
  'modulesTitle': 'Modules',
  'modulesDesc': 'Turn off unused features. Your data remains safe.',
  'regionTitle': 'Region Preference',
  'regionDesc': 'Choose how the app behaves. You can change this any time without losing data.',
  'companyDetailsTitle': 'Company Details',
  'paymentAccountsTitle': 'Payment Accounts',
  'paymentAccountsDesc': 'Add bank or UPI accounts. The default (⭐) is preselected on new invoices.',
  'cloudBackupTitle': 'Cloud Backup (Google Drive)',
  'cloudBackupDesc': 'Auto-sync your invoices to Google Drive — no coding or API setup needed.',
  'moduleGroup_sales': 'Sales & Invoicing',
  'moduleDesc_sales': 'Invoice creation, recurring invoices, payment receipts',
  'module_invoicing': 'Tax invoices, proforma, credit notes',
  'module_recurring': 'Recurring invoices',
  'module_receipts': 'Payment receipts',
  'moduleGroup_directory': 'Directory',
  'moduleDesc_directory': 'Clients and product catalog',
  'module_clients': 'Clients',
  'module_inventory': 'Products & Services',
  'moduleGroup_purchases': 'Purchases & Expenses',
  'moduleDesc_purchases': 'Vendor bills, expense tracking, ITC',
  'module_expenses': 'Expense tracker',
  'module_purchases': 'Purchase bills',
  'module_gstr2b': 'GSTR-2B reconciliation (purchase ITC matching)',
  'moduleGroup_gst': 'GST & Tax (India)',
  'moduleDesc_gst': 'GSTR returns, e-Way Bill, TDS/TCS, HSN summaries',
  'module_gstReturns': 'GSTR-1 / GSTR-3B exports + filing guide',
  'module_ewayBill': 'E-Way Bill JSON export',
  'module_tdsTcs': 'TDS / TCS on invoices',
  'moduleGroup_reports': 'Reports',
  'moduleDesc_reports': 'Dashboards and financial reports',
  'module_dashboard': 'Dashboard',
  'module_reports': 'Reports view',
  'moduleGroup_integrations': 'Integrations',
  'moduleDesc_integrations': 'Cloud backup and payment QR codes',
  'module_upiQr': 'UPI QR code on invoices',
  'contactBank': 'Contact & Bank',
  'businessSettings': 'Business Settings',
  'bank': 'Bank',
  'invoiceSettings': 'Invoice Settings',
  'languageSettings': 'Language Settings',
  'companyAddressDetails': 'Company address details',
  'accountNumberIfsc': 'Account number, IFSC',
  'languages': 'Languages',
  'dataEntryLanguages': 'Data entry languages',
  'colorsTheme': 'Colors & Theme',
  'createNewBusinessProfile': 'Create New Business Profile',
  'profileDeleted': 'Profile deleted',
  'maxProfilesReached': 'Maximum 5 profiles allowed',
  'settingsSaved': 'Settings saved!',
  'activeProfile': 'Active Profile',
  'createNewProfileModalTitle': 'Create New Profile',
  'manageBusinessProfilesModalTitle': 'Manage Business Profiles',
  'noSavedProfilesYet': 'No saved profiles yet',
  'permanentlyDeleteProfile': 'Permanently delete this business profile?',
  'saveProfile': 'Save',
  'businessProfilesTitle': 'Business Profiles',
  'addNewProfile': 'Add New Profile',
  'saveAsProfile': 'Save',
  'businessProfilesDesc1': 'Switch instantly between saved business profiles.',
  'businessProfilesDesc2': 'No saved profiles.',
  'exportBackup': 'Export Backup...',
  'importBackup': 'Import Backup...',
  'primaryLanguage': 'Primary Language',
  'secondaryLanguage': 'Secondary Language',
  'languagesUsedForBilling': 'Languages used for billing and data entry',
  'langTamil': 'தமிழ் (Tamil)',
  'langEnglish': 'English',
  'langHindi': 'हिन्दी (Hindi)',
  'langTelugu': 'తెలుగు (Telugu)',
  'langKannada': 'ಕನ್ನಡ (Kannada)',
  'langMalayalam': 'മലയാളം (Malayalam)',
  'langMarathi': 'मराठी (Marathi)',
  'langGujarati': 'ગુજરાતી (Gujarati)',
  'langBengali': 'বাংলা (Bengali)',
  'paymentBank': 'Bank Transfer',
  'allClearNotif': 'All Clear',
  'company': 'Company',
  'bankNameTamil': 'Bank Name (Tamil)',
  'bankNameEnglish': 'Bank Name (English)',
  'profileSaved': 'Profile saved!',
  'createNewProfile': 'Create New Profile',
  'manageBusinessProfiles': 'Manage Business Profiles',
  'noSavedProfiles': 'No saved profiles yet',
  'languageSettingsSaved': 'Language settings saved!',
  'changeTheLanguageOfTheApplicat': 'Change the language of the application.',
  'allowDataEntryInTwoLanguages': 'Allow data entry in two languages',
  'bankDetailsShownOnYourInvoices': 'Bank details shown on your invoices.',
  'accountNumber': 'Account Number',
  'appearanceDescription': 'Configure bill theme color and print languages.',
  'billTheme': 'Bill Theme Color',
  'cooliePdfTheme': 'PDF Theme',
  'defaultPrintLanguage': 'Bill & Receipt Language',
  'cooliePrintLanguage': 'Invoice & Receipt Language',
  'receiptLanguage': 'Receipt Language',
  'accountSecurityTitle': 'Account Security',
  'accountSecurityDesc': 'Lock app access.',
  'systemAndSecurity': 'System & Security',
  'systemSecurityDesc': 'Clear cache, Account security, Updates',
  'clearCacheTitle': 'Clear Cache',
  'clearCacheDesc': 'Fix issues by clearing cache.',
  'clearCacheBtn': 'Clear Cache',
  'clearCacheConfirmDesc': 'This will reload the app. You may need to sign in again.',
  'confirmPassword': 'Confirm',
  'password': 'Password',
  'enterPassword': 'Please enter your password',
  'incorrectPassword': 'Incorrect password.',
  'editPrefix': 'Edit ',
  'settings_mugavari': 'Address',
  'desc_business_profile': 'Business profile mode',
  'desc_bank': 'Account number & IFSC',
  'desc_language': 'Tamil, English, Auto',
  'desc_security': 'Clear cache, Account security',
  'desc_about': 'Learn more about Elvan',
  'logout_desc': 'Logout from the application.',
  'backup_now': 'Backup Now',
  'backup_now_desc': 'Manually update your backup file.',
  'backup_now_title': 'Backup Database',
  'backup_now_btn': 'Backup Now',
  'backup_success': 'Backup successfully saved to Documents.',
  'checking_backups': 'Checking for backups...',
  'backup_found': 'Backup found!',
  'no_backup_found': 'No backup found, starting fresh.',
  'primary_language': 'Primary Language',
  'secondary_language': 'Secondary Language',

  // ========================================
  // Merchants & Customers
  // ========================================
  'merchants': 'Merchants',
  'district': 'District',
  'state': 'State',
  'email': 'Email',
  'addClient': 'Add Merchant',
  'newMerchant': 'New Merchant',
  'merchantName': 'Merchant Name',
  'editClientTitle': 'Edit Merchant',
  'addNewClientTitle': 'Add New Merchant',
  'clientBusinessName': 'Merchant / Business Name',
  'city': 'City',
  'country': 'Country',
  'address': 'Address',
  'oor': 'City',
  'maavattam': 'District',
  'county': 'County',
  'province': 'Province',
  'zipCode': 'Zip Code',
  'clientNamePlaceholder': 'e.g. Elvan Corp',
  'clientNamePlaceholderEn': 'Merchant Name (in English)',
  'streetAddressPlaceholder': 'Street Address',
  'addressPlaceholderEn': 'Address (in English)',
  'cityPlaceholderEn': 'City (in English)',
  'districtPlaceholder': 'District',
  'districtPlaceholderEn': 'District (in English)',
  'countryPlaceholderEn': 'Country (in English)',
  'cityPlaceholder': 'e.g. Chennai',
  'emailPlaceholder': 'merchant@example.com',
  'phoneLabel': 'Phone Number',
  'phonePlaceholder': '+91 98765 43210',
  'updateClientModalBtn': 'Update',
  'saveClientModalBtn': 'Save',
  'noMerchants': 'No merchants yet',
  'deleteMerchantConfirm': 'Delete this merchant?',
  'duplicateCustomersTitle': 'Duplicate Merchants?',
  'duplicateCustomersMessage': 'Duplicate {count} selected merchant(s)?',
  'deleteMerchantsTitle': 'Delete Merchants?',
  'deleteMerchantsMessage': 'Delete {count} merchant(s)? This cannot be undone.',
  'customersDuplicatedSuccess': 'Merchants duplicated successfully',
  'clientName': 'Client Name',
  'billingAddress': 'Billing Address',
  'pinCode': 'PIN Code',
  'maanilam': 'State',
  'countryLabel': 'Country',
  'oorLabel': 'City / Town',
  'emailLabel': 'Email',
  'phoneNumbers': 'Phone Numbers',
  'addressOptional': 'Address (Optional)',
  'Select maanilam': 'Select State',
  'searchClientOrInvoice': 'Search client or invoice...',
  'clientCol': 'Client',
  'typeClientName': 'Type to search client name or add new',
  'selectState': 'Select State',
  'errorLoadingCustomers': 'Error loading customers',
  'clientsTitle': 'Clients',
  'clientsSubtitle': 'Manage clients and view outstandings',
  'searchClients': 'Search Clients',
  'noClientsFound': 'No Clients Found',
  'addFirstClient': 'Add First Client',
  'noInvoicesForClient': 'No Invoices For Client',
  'removeSavedClientConfirm': 'Remove Saved Client Confirm',
  'clientRemoved': 'Client Removed',
  'editClientBtn': 'Edit Client',
  'deleteClientBtn': 'Delete Client',
  'saveAsClientBtn': 'Save',
  'clientNameRequiredToast': 'Client Name Required',
  'interstatePurchaseLabel': 'Interstate Purchase',
  'interstatePurchaseDesc': 'Interstate Purchase Desc',
  'interstatePurchaseTip': 'Interstate Purchase Tip',
  'quickSelectClient': 'Quick Select Client',
  'plStatementTitle': 'Pl Statement',
  'filterByClientName': 'Filter By Client Name',
  'clientDetails': 'Client Details',
  'addressDetails': 'Address Details',
  'customer': 'Customer',
  'addressLabel': 'Address',
  'addressTamil': 'Address (Tamil)',
  'addressEnglish': 'Address (English)',
  'cityTamil': 'City (Tamil)',
  'cityEnglish': 'City (English)',
  'districtTamil': 'District (Tamil)',
  'districtEnglish': 'District (English)',
  'cityLabel': 'City',
  'districtLabel': 'District',
  'pincode': 'Pincode',
  'confirmEmailLabel': 'Confirm Email',
  'incorrectEmail': 'Email does not match.',
  'emailAddress': 'Email Address',
  'enterEmail': 'Enter your email',
  'desc_address': 'Company address details',

  // ========================================
  // Inventory & Items
  // ========================================
  'description': 'Description',
  'inventory': 'Products',
  'itemsList': 'Items',
  'itemName': 'Item Name',
  'rate': 'Rate',
  'addAnotherItem': 'Add Row',
  'lineItems': 'Line Items',
  'hsnSac': 'HSN/SAC',
  'qty': 'Qty',
  'unit': 'Unit',
  'inventoryTitle': 'Products',
  'inventorySubtitle': 'Manage your products and services',
  'productNameLabel': 'Product / Service Name',
  'hsnCodeLabel': 'HSN / SAC Code',
  'addProductBtn': 'Add Product',
  'searchProducts': 'Search Products',
  'stockQuantityLabel': 'Stock Quantity',
  'newItem': 'New Item',
  'noItems': 'No items yet',
  'deleteItemConfirm': 'Are you sure you want to delete this item?',
  'addProductTitle': 'Add New Product',
  'editProductTitle': 'Edit Product',
  'rateLabel': 'Rate (Base Price)',
  'productAddedToast': 'Product Added Successfully',
  'productUpdatedToast': 'Product Updated',
  'failedToSaveProductToast': 'Failed to Save Product',
  'productNameRequiredToast': 'Product Name is Required',
  'totalItems': 'Total',
  'item': 'Item',
  'showItemizedGstTable': 'Show GST splits in table',
  'displayDetailedItemizedGst': 'Display detailed itemized GST breakdown columns on the invoice',
  'duplicateProductsTitle': 'Duplicate Products?',
  'duplicateProductsMessage': 'Are you sure you want to create copies of the selected product(s)?',
  'productsDuplicatedSuccess': 'Products duplicated successfully',
  'deleteProductsTitle': 'Delete Products?',
  'deleteProductsMessage': 'Delete selected product(s)? This cannot be undone.',
  'descriptionCol': 'Description',
  'hsnSacCol': 'HSN/SAC',
  'rateCol': 'Rate',
  'addItemBtn': 'Add Item',
  'sezUnitTitle': 'Sez Unit',
  'productNamePlaceholder': 'Product Name Placeholder',
  'hsnCodePlaceholder': 'Hsn Code Placeholder',
  'unitLabel': 'Unit',
  'descriptionLabelOptional': 'Description Label Optional',
  'descriptionPlaceholder': 'Description Placeholder',
  'productsAndServices': 'Products And Services',
  'noProductsYet': 'No Products Yet',
  'noProductsMatch': 'No Products Match',
  'outOfStock': 'Out Of Stock',
  'deleteProductConfirmMsg': 'Delete Product Confirm',
  'productDeletedToast': 'Product Deleted',
  'failedToLoadProductsToast': 'Failed To Load Products',
  'hsnCol': 'Hsn',
  'stockCol': 'Stock',
  'descriptionLabelStar': 'Description Label',
  'descriptionPlaceholderExp': 'Description Placeholder Exp',
  'descriptionRequiredToast': 'Description Required',
  'itemsTitle': 'Items',
  'qtyCol': 'Qty',
  'lineItemsTitle': 'Line Items',
  'addAtLeastOneItemToast': 'Add At Least One Item',
  'failedToGenerateToast': 'Failed To Generate',
  'invoiceGeneratedFor': 'Invoice Generated For',
  'statusActive': 'Status Active',
  'generateNowTooltip': 'Generate Now Tooltip',
  'hsnSummaryTable': 'HSN Summary',
  'lowStockNotif': 'Low Stock',
  'productDetails': 'Product Details',

  // ========================================
  // Invoices & Billing
  // ========================================
  'invoices': 'Invoices',
  'receipts': 'Receipts',
  'recurring': 'Recurring',
  'newBill': 'New Bill',
  'bills': 'Bills',
  'allBills': 'All Bills',
  'billNo': 'Bill No',
  'invoiceDetails': 'Invoice Details',
  'price': 'Price',
  'amount': 'Amount',
  'total': 'Total',
  'subTotal': 'Sub Total',
  'invoiceNumber': 'Invoice Number',
  'invoiceDate': 'Invoice Date',
  'dueDate': 'Due Date',
  'discount': 'Discount',
  'cess': 'Cess %',
  'invoiceTab': 'Invoice',
  'totalDueLabel': 'Total Due',
  'newPaymentReceiptTitle': 'New Payment Receipt',
  'editReceiptTitle': 'Edit Receipt',
  'receiptNoLabel': 'Receipt No',
  'amountLabelStar': 'Amount Label',
  'paymentModeLabel': 'Payment Mode',
  'againstInvoiceLabel': 'Against Invoice',
  'saveReceiptBtn': 'Save',
  'searchReceipts': 'Search Receipts',
  'paymentReceiptsTableTitle': 'Payment Receipts Table',
  'createReceiptBtn': 'Create Receipt',
  'taxableLabel': 'Taxable',
  'taxLabel': 'Tax',
  'selectInvoices': 'Select Invoices',
  'searchInvoices': 'Search by invoice no. or customer...',
  'receipt': 'Receipt',
  'successSaved': 'Saved successfully!',
  'billedTo': 'Billed To',
  'invoiceDetailsForm': 'Invoice Details',
  'pricesIncludeTax': 'Prices include tax',
  'invoiceNumberFormatTitle': 'Invoice Number Format',
  'invoiceStylingOptions': 'Invoice styling options',
  'termsTemplatesTitle': 'Terms & Conditions Templates',
  'newTemplate': 'New Template',
  'termsTemplatesDesc': 'Create or pick reusable terms.',
  'templateName': 'Template Name',
  'templateContent': 'Content (paste your terms here)',
  'saveTemplate': 'Save',
  'noTemplates': 'No templates yet.',
  'revenueExTax': 'Revenue (ex. Tax)',
  'showingCurrencyInvoicesOnly': 'invoices only',
  'totalRevenueLabel': 'Total Revenue',
  'lessGstCollectedLabel': 'Less: Tax Collected',
  'newInvoice': 'New Invoice',
  'editInvoice': 'Edit Invoice',
  'totalBills': 'Total Bills',
  'bilingualBills': 'Bilingual Bills',
  'enableBilingualBills': 'Enable Bilingual Bills',
  'overviewOfInvoices': 'Overview of your invoices',
  'totalInvoiced': 'Total Invoiced',
  'taxCollected': 'Tax Collected',
  'overdueLabel': 'Overdue',
  'invoiceModeGoods': 'Goods',
  'invoiceModeServices': 'Services',
  'invoiceModeMixed': 'Mixed',
  'paymentCash': 'Cash',
  'paymentUPI': 'UPI',
  'paymentCheque': 'Cheque',
  'paymentCard': 'Card',
  'paymentOther': 'Other',
  'invoicesCount': 'Invoices',
  'allStatus': 'All Status',
  'noInvoicesYet': 'No invoices yet.',
  'noInvoicesMatch': 'No matching invoices.',
  'createInvoiceBtn': 'Create Invoice',
  'invoiceNoCol': 'Invoice No.',
  'amountCol': 'Amount',
  'paidCol': 'Paid',
  'statusCol': 'Status',
  'status_unpaid': 'Unpaid',
  'status_partial': 'Partial',
  'status_paid': 'Paid',
  'status_overdue': 'Overdue',
  'ewayBill': 'E-Way Bill',
  'invoiceType': 'Invoice Type',
  'thisInvoiceIsFor': 'This invoice is for',
  'invoiceTypes_tax_invoice': 'Tax Invoice',
  'invoiceTypes_proforma': 'Proforma Invoice',
  'invoiceTypes_bill_of_supply': 'Bill of Supply',
  'invoiceTypes_composition': 'Composition Invoice',
  'invoiceTypes_credit_note': 'Credit Note',
  'invoiceTypes_delivery_challan': 'Delivery Challan',
  'invoiceDesc_tax_invoice': 'Standard invoice for B2B/B2C sales with tax',
  'invoiceDesc_proforma': 'Estimated invoice or quote before actual sale',
  'invoiceDesc_bill_of_supply': 'For selling tax-exempt items without charging tax',
  'invoiceDesc_composition': 'For businesses under Composition scheme (flat tax)',
  'invoiceDesc_credit_note': 'For sales returns or reducing the invoice amount',
  'invoiceDesc_delivery_challan': 'For sending items on approval, job work, or branch transfer',
  'savedSuccessfully': 'Saved successfully',
  'deletedSuccessfully': 'Deleted successfully',
  'loadSavedTemplate': 'Load Saved Template',
  'termsAppearsOnInvoice': 'Terms Appears On Invoice',
  'newInvoiceBtn': 'New Invoice',
  'invoiceCountSingular': 'Invoice Count Singular',
  'totalLabel': 'Total',
  'paidLabel': 'Paid',
  'deleteInvoiceConfirm': 'Delete Invoice Confirm',
  'invoiceDeleted': 'Invoice Deleted',
  'receiptsSubtitle': 'Manage payment receipts',
  'newReceiptBtn': 'New Receipt',
  'quickSelectUnpaid': 'Quick Select Unpaid',
  'againstInvoicePlaceholder': 'Against Invoice Placeholder',
  'noReceiptsYet': 'No Receipts Yet',
  'noReceiptsMatch': 'No Receipts Match',
  'againstInvoiceCol': 'Against Invoice',
  'enterValidAmountToast': 'Enter Valid Amount',
  'receiptSavedToast': 'Receipt Saved',
  'deleteReceiptConfirmMsg': 'Are you sure you want to delete this receipt?',
  'totalExpensesCard': 'Total Expenses',
  'gstPaidCard': 'Gst Paid',
  'amountGstLabelStar': 'Amount Gst Label',
  'invoiceBillNoLabel': 'Invoice Bill No',
  'enterValidAmountToastExp': 'Enter Valid Amount Toast Exp',
  'totalPurchasesCard': 'Total Purchases',
  'searchSupplierInvoice': 'Search Supplier Invoice',
  'noPurchaseBillsYet': 'No Purchase Bills Yet',
  'editPurchaseBillTitle': 'Edit Purchase Bill',
  'addPurchaseBillTitle': 'Add Purchase Bill',
  'paymentStatusLabel': 'Payment Status',
  'invoiceNumberLabel': 'Invoice Number',
  'invoiceNumberPlaceholder': 'Invoice Number Placeholder',
  'taxPercentCol': 'Tax Percent',
  'taxableLabelText': 'Taxable Label Text',
  'taxLabelText': 'Tax Label Text',
  'totalLabelText': 'Total Label Text',
  'invoiceNumberRequiredToast': 'Invoice Number Required',
  'taxableCol': 'Taxable',
  'recurringInvoicesSubtitle': 'Automate invoices for regular clients',
  'invoiceLimitDesc': 'Total number of invoices you can create across all clients',
  'signOutSuccess': 'Signed out successfully',
  'newTemplateBtn': 'New Template',
  'dueForGeneration': 'Due For Generation',
  'editTemplateTitle': 'Edit Template',
  'newRecurringInvoiceTitle': 'New Recurring Invoice',
  'nextDueDateLabel': 'Next Due Date',
  'invoiceTypeLabel': 'Invoice Type',
  'recurringTemplatesTable': 'Recurring Templates Table',
  'noRecurringYet': 'No Recurring Yet',
  'createTemplateBtn': 'Create Template',
  'nextDueCol': 'Next Due',
  'templateUpdatedToast': 'Template Updated',
  'recurringCreatedToast': 'Recurring Created',
  'deleteTemplateConfirmMsg': 'Delete Template Confirm',
  'statusPaused': 'Status Paused',
  'totalExpensesLabel': 'Total Expenses',
  'lessGstOnExpensesLabel': 'Less Gst On Expenses',
  'totalOutstandingLabel': 'Total Outstanding',
  'dueDateCol': 'Due Date',
  'daysOverdueCol': 'Days Overdue',
  'currentStatus': 'Current Status',
  'invoicesCountLabel': 'Invoices Count',
  'gstr1SummaryTotals': 'GSTR-1 Summary Totals',
  'noB2bInvoices': 'No B2B Invoices',
  'noB2cInvoices': 'No B2C Invoices',
  'cgstCol': 'CGST',
  'sgstCol': 'SGST',
  'igstCol': 'IGST',
  'totalCol': 'Total',
  'b2cTotal': 'B2C Total',
  'totalTaxCol': 'Total Tax',
  'totalIssuedCol': 'Total Issued',
  'grandTotal': 'Grand Total',
  'invoiceWord': 'Invoice',
  'invoicesWord': 'Invoices',
  'recurringAutoFireNotif': 'Recurring Auto Fire',
  'checkDashboardForNewBills': 'Check Dashboard For New Bills',
  'overdueInvoicesNotif': 'Overdue Invoices',
  'dueIn3DaysNotif': 'Due In 3 Days',
  'gstFilingsDueNotif': 'Gst Filings Due',
  'receiptDetails': 'Receipt Details',
  'invoiceData': 'Invoice Data',
  'receiptData': 'Receipt Data',
  'invoicesSelected': 'invoice(s) selected',
  'paymentDetails': 'Payment Details',
  'pricingAndTax': 'Pricing & Tax',
  'contactAndTaxDetails': 'Contact & Tax Details',
  'deleteInvoiceConfirmMsg': 'Are you sure you want to delete this invoice?',
  'totalWeight': 'Total Weight',
  'searchBillsPlaceholder': 'Search anything...',
  'savingStatus': 'Saving...',
  'invoiceCount': 'Invoice Count',
  'totals': 'Totals',
  'subtotal': 'Subtotal',
  'totalDiscountAmt': 'Total Discount Amount',
  'roundOff': 'Round Off',
  'noInvoicesFound': 'No Invoices Found',
  'dataErasedSuccess': 'App data erased.',
  'desc_invoice': 'Invoice styling options',
  'billHeaderStyle': 'Bill Header Style',
  'restoreSuccess': 'Data restored successfully!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'expenses': 'Expenses',
  'purchases': 'Purchases',
  'expensesSubtitle': 'Track business expenses',
  'addExpenseBtn': 'Add Expense',
  'searchExpenses': 'Search Expenses',
  'expenseRecordsTable': 'Expense Records Table',
  'noExpensesYet': 'No Expenses Yet',
  'noExpensesMatch': 'No Expenses Match',
  'editExpenseTitle': 'Edit Expense',
  'addExpenseTitle': 'Add Expense',
  'gstPercentItcLabel': 'Gst Percent Itc',
  'vendorNameLabel': 'Vendor Name',
  'vendorNameOptional': 'Vendor Name Optional',
  'vendorGstinLabel': 'Vendor Gstin',
  'vendorGstinHint': 'Vendor Gstin Hint',
  'expenseUpdatedToast': 'Expense Updated',
  'expenseAddedToast': 'Expense Added',
  'failedToSaveExpenseToast': 'Failed To Save Expense',
  'deleteExpenseConfirmMsg': 'Delete Expense Confirm',
  'expenseDeletedToast': 'Expense Deleted',
  'noExpensesToExportToast': 'No Expenses To Export',
  'expensesCsvDownloadedToast': 'Expenses Csv Downloaded',
  'vendorCol': 'Vendor',
  'purchasesSubtitle': 'Track supplier bills for ITC',
  'addPurchaseBtn': 'Add Purchase',
  'gstItcEligibleCard': 'Gst Itc Eligible',
  'purchaseRecordsTable': 'Purchase Records Table',
  'noPurchasesMatch': 'No Purchases Match',
  'supplierNameLabel': 'Supplier Name',
  'supplierNamePlaceholder': 'Supplier Name Placeholder',
  'supplierGstinLabel': 'Supplier Gstin',
  'supplierGstinPlaceholder': 'Supplier Gstin Placeholder',
  'supplierNameRequiredToast': 'Supplier Name Required',
  'purchaseUpdatedToast': 'Purchase Updated',
  'purchaseAddedToast': 'Purchase Added',
  'failedToSavePurchaseToast': 'Failed To Save Purchase',
  'failedToLoadPurchasesToast': 'Failed To Load Purchases',
  'deletePurchaseConfirmMsg': 'Delete Purchase Confirm',
  'purchaseDeletedToast': 'Purchase Deleted',
  'noPurchasesToExportToast': 'No Purchases To Export',
  'purchasesCsvDownloadedToast': 'Purchases Csv Downloaded',
  'supplierCol': 'Supplier',
  'expensesExGst': 'Expenses Ex Gst',
  'netExpensesLabel': 'Net Expenses',
  'expensesCol': 'Expenses',

  // ========================================
  // Reports & GST
  // ========================================
  'reports': 'Reports',
  'dashboard': 'Dashboard',
  'gstReturns': 'GST Returns',
  'gstr1Tab': 'GSTR-1',
  'gstr3bTab': 'GSTR-3B',
  'gstin': 'GSTIN',
  'gstinOptional': 'GSTIN (Optional)',
  'GSTIN': 'GSTIN',
  'includeFinancialYear': 'Include Financial Year',
  'reportsTitle': 'Reports',
  'reportsSubtitle': 'Overview of your sales revenue and taxes collected',
  'salesSummaryTitle': 'Sales Summary',
  'importCSV': 'Import CSV',
  'exportCsvBtn': 'Export CSV',
  'gstinCol': 'Gstin',
  'outstandingReceivablesTitle': 'Outstanding Receivables',
  'gstReturnsTitle': 'GST Returns',
  'gstReturnsSubtitle': 'Manage your GST Returns and filing status',
  'gstinNotSet': 'GSTIN not set. Please add it in Settings.',
  'gstr2bReconTab': 'GSTR-2B Recon',
  'tdsTcsTab': 'Tds Tcs',
  'docSummaryTable': 'Document Summary',

  // ========================================
  // Actions, Alerts & Common
  // ========================================
  'error': 'Error',
  'save': 'Save',
  'cancel': 'Cancel',
  'edit': 'Edit',
  'delete': 'Delete',
  'add': 'Add',
  'search': 'Search...',
  'yes': 'Yes',
  'no': 'No',
  'selected': 'Selected',
  'notes': 'Notes',
  'closeBtn': 'Close',
  'cancelBtn': 'Cancel',
  'deleteBtn': 'Delete',
  'saveBtn': 'Save',
  'addNew': 'Add New',
  'notifications': 'Notifications',
  'referenceNoLabel': 'Reference No',
  'systemUpdates': 'System & Updates',
  'preview': 'Preview',
  'copyDuplicate': 'Copy / Duplicate',
  'connected': 'Connected',
  'offlineMode': 'Offline mode',
  'connecting': 'Connecting...',
  'aakku': 'Create',
  'uruvakku': 'Create',
  'noLogo': 'No Logo',
  'noSignature': 'No Signature',
  'cancelModalBtn': 'Cancel',
  'confirmModalBtn': 'Confirm',
  'errorSaveFailed': 'Failed to save:',
  'noDataAvailable': 'No Data Available',
  'createBtn': 'Create',
  'unsavedChangesContinue': 'You have unsaved changes. Continue without saving?',
  'manageBtn': 'Manage',
  'addNewBtn': 'Add New',
  'currentlyEditing': 'Currently Editing',
  'confirmDeleteModalTitle': 'Confirm Delete',
  'yesFinYear': 'Yes (2026-27)',
  'numberPadding': 'Number Padding',
  'saveNumberFormat': 'Save',
  'appUpdatesTitle': 'App Updates',
  'appUpdatesDesc': 'Check if a newer version is available.',
  'checkingUpdate': 'Checking...',
  'checkForUpdates': 'Check for Updates',
  'noneLabel': 'None',
  'selectLabelGeneric': 'Select',
  'pdfPreviewHeader': 'PDF Preview',
  'saveDuplicate': 'Save (Duplicate)',
  'errorDuplicating': 'Error duplicating',
  'errorDeleting': 'Error deleting',
  'emptyKey': 'பண ரசீது',
  'privateNote': 'Private Note',
  'privateNoteEg': 'Private Note Eg',
  'additionalPages': 'Additional Pages',
  'addSectionBtn': 'Add Section',
  'addExtraSectionsDesc': 'Add Extra Sections Desc',
  'noExtraSections': 'No Extra Sections',
  'failedToDelete': 'Failed To Delete',
  'selectLabel': 'Select',
  'emptyCsvWarningToast': 'Empty Csv Warning',
  'failedToParseCsvToast': 'Failed To Parse Csv',
  'noteOptionalLabel': 'Note Optional',
  'deletedToast': 'Deleted',
  'noOutstandingFound': 'No Outstanding Found',
  'november': 'November',
  'gstPortalBtn': 'Gst Portal',
  'jsonExportBtn': 'Json Export',
  'docsBtn': 'Docs',
  'markFiledBtn': 'Mark Filed',
  'notificationsTitle': 'Notifications',
  'notesAndTerms': 'Notes / Terms',
  'addOtherCharges': 'Add Other Charges',
  'detailsSaved': 'Details saved successfully',
  'unsavedChangesWarning': 'You have unsaved changes. Continue without saving?',
  'unsavedChanges': 'Unsaved changes',
  'discardBtn': 'Discard',
  'confirmDeleteTitle': 'Confirm Delete',
  'selectYourOperatingMode': 'Select your operating mode',
  'addAlternateMobile': 'Add Alternate Mobile',
  'featureNotSupported': 'Feature Not Supported',
  'signOutBtn': 'Sign Out',
  'eraseDataBtn': 'Erase Data',
  'signOutConfirmTitle': 'Sign Out?',
  'signOutConfirmDesc': 'Are you sure you want to sign out? You will need your password to access your data again.',
  'eraseConfirmDesc': 'Permanently deletes all cloud data. This cannot be undone.',
  'errorOccurred': 'Failed to erase data.',
  'agreeAndContinueBtn': 'Get Started',
  'uruvakku_amaippugal': 'Creation Settings',
  'restoreBtn': 'Restore Data',

  // ========================================
  // Miscellaneous
  // ========================================
  'appName': 'Niril',
  'appNameFull': 'Elvan Niril',
  'loading': 'Loading...',
  'back': 'Back',
  'actions': 'Actions',
  'done': 'Done',
  'date': 'Date',
  'terms': 'Terms',
  'continue': 'Continue',
  'manage': 'Manage',
  'home': 'Home',
  'userGuide': 'User Guide',
  'companies': 'Companies',
  'weight': 'Weight',
  'placeOfSupply': 'Place of Supply',
  'receivedFromLabel': 'Received From',
  'mugavari': 'Address',
  'tholaipesi': 'Phone',
  'darkMode': 'Dark Mode',
  'lightMode': 'Light Mode',
  'storageCloud': 'Storage & Cloud',
  'ifscCode': 'IFSC Code',
  'kilai': 'Branch',
  'netPayableLabel': 'Net Payable',
  'logoUploaded': 'Logo Uploaded',
  'wideLogoUploaded': 'Wide Logo Uploaded',
  'branchName': 'Branch Name',
  'systemStorage': 'System Storage',
  'name': 'Name',
  'postcode': 'Postcode',
  'tamil': 'Tamil',
  'english': 'English',
  'hindi': 'Hindi',
  'telugu': 'Telugu',
  'kannada': 'Kannada',
  'malayalam': 'Malayalam',
  'marathi': 'Marathi',
  'gujarati': 'Gujarati',
  'bengali': 'Bengali',
  'brandingTitle': 'Branding',
  'businessLogo': 'Business Logo',
  'signature': 'Signature / Stamp',
  'exportImportTitle': 'Export & Import Data',
  'exportImportDesc': 'Backup your data locally or restore from a previous backup file.',
  'resetToDefault': 'Reset to default',
  'businessNameLabel': 'Business Name',
  'gstPercentLabel': 'GST %',
  'mugavariLabel': 'Address',
  'tholaipesiLabel': 'Phone',
  'mobileLabel': 'Mobile',
  'orgNameEn': 'Organization Name (English)',
  'shortBusinessName': 'Short Business Name',
  'shortBusinessNameHint': 'Used as the default prefix for your invoice numbers.',
  'adaimozhi': 'Tagline',
  'branding': 'Branding',
  'nirilCoolie': 'Niril Coolie',
  'nirilSilk': 'Niril Silk',
  'logoSignatures': 'Logo & Signatures',
  'businessName': 'Business Name',
  'fillDetailsLater': 'You can fill in the rest of the details later from Settings.',
  'creating': 'Creating...',
  'scanAgain': 'Scan Again',
  'changesDiscarded': 'Changes discarded',
  'businessNameStar': 'Business Name *',
  'businessNameEnglish': 'Business Name (English)',
  'PIN Code': 'PIN Code',
  'e.g. Mumbai': 'e.g. Mumbai',
  'digits3': '3 digits (001)',
  'digits4': '4 digits (0001)',
  'digits5': '5 digits (00001)',
  'digits6': '6 digits (000001)',
  'saving': 'Saving...',
  'uploadLogo': 'Upload Logo',
  'logoHint': 'PNG or JPG, square or wide (max 500KB)',
  'uploadSignature': 'Upload Signature',
  'sigHint': 'PNG, JPG (max 500KB)',
  'appStorageDesc': 'App cache memory',
  'dataManagementTitle': 'Data Management',
  'filterByLabel': 'Filter By',
  'fiscalYearLabel': 'Fiscal Year',
  'monthYearLabel': 'Month / Year',
  'monthLabel': 'Month',
  'yearLabel': 'Year',
  'currencyLabel': 'Currency',
  'netRevenueLabel': 'Net Revenue',
  'monthlySalesTitle': 'Monthly Sales Breakdown',
  'revenueCol': 'Revenue',
  'recentActivity': 'Recent Activity',
  'seeAll': 'See All',
  'greeting': 'Hello',
  'enabled': 'Enabled',
  'disabled': 'Disabled',
  'outstanding': 'Outstanding',
  'allYears': 'All Years',
  'allTypes': 'All Types',
  'dateCol': 'Date',
  'typeCol': 'Type',
  'actionsCol': 'Actions',
  'draftOnly': 'Draft',
  'downloadPdf': 'Download PDF',
  'whatsapp': 'WhatsApp',
  'customize': 'Customize',
  'goods': 'Goods',
  'services': 'Services',
  'mixed': 'Mixed',
  'egMumbai': 'e.g. Mumbai',
  'optionalLabel': 'Optional',
  'termsAndConditionsLabel': 'Terms & Conditions',
  'vanakkamTitle': 'Vanakkam!',
  'whoIsWorkingToday': 'Who\'s working today?',
  'termsHeading': 'Terms Heading',
  'insertPreset': 'Insert Preset',
  'pickBusinessType': 'Pick Business Type',
  'outstandingLabel': 'Outstanding',
  'hideLabel': 'Hide',
  'viewLabel': 'View',
  'nameCol': 'Name',
  'dateLabel': 'Date',
  'modeCol': 'Mode',
  'entriesCard': 'Entries',
  'allCategoriesFilter': 'All Categories Filter',
  'dateLabelStar': 'Date Label',
  'categoryLabel': 'Category',
  'gstCol': 'Gst',
  'signing_out': 'Signing out...',
  'frequencyLabel': 'Frequency',
  'frequencyCol': 'Frequency',
  'pausedToast': 'Paused',
  'activatedToast': 'Activated',
  'freqWeekly': 'Freq Weekly',
  'freqMonthly': 'Freq Monthly',
  'freqQuarterly': 'Freq Quarterly',
  'freqYearly': 'Freq Yearly',
  'pauseTooltip': 'Pause Tooltip',
  'activateTooltip': 'Activate Tooltip',
  'profitAndLossTab': 'Profit And Loss',
  'outstandingAndAgingTab': 'Outstanding And Aging',
  'netProfitLabel': 'Net Profit',
  'netLossLabel': 'Net Loss',
  'marginLabel': 'Margin',
  'monthlyBreakdownTitle': 'Monthly Breakdown',
  'profitLossCol': 'Profit Loss',
  'current0to30d': 'Current 0 to 30 Days',
  'days31to60': 'Days 31 to 60',
  'days61to90': 'Days 61 to 90',
  'days90plus': 'Days 90 plus',
  'outstandingCol': 'Outstanding',
  'january': 'January',
  'february': 'February',
  'march': 'March',
  'april': 'April',
  'may': 'May',
  'june': 'June',
  'july': 'July',
  'august': 'August',
  'september': 'September',
  'october': 'October',
  'december': 'December',
  'monthlyTab': 'Monthly',
  'quarterlyTab': 'Quarterly',
  'r1Pending': 'R1 Pending',
  'b3Pending': '3B Pending',
  'filingGuideTab': 'Filing Guide',
  'b2bSalesTable': 'B2B Sales',
  'b2cSalesTable': 'B2C Sales',
  'docTypeCol': 'Doc Type',
  'fromCol': 'From',
  'toCol': 'To',
  'categoryCol': 'Category',
  'b2bSalesCategory': 'B2B Sales Category',
  'b2cSalesCategory': 'B2C Sales Category',
  'codeWord': 'Code',
  'codesWord': 'Codes',
  'moreWord': 'More',
  'todayWord': 'Today',
  'leftWord': 'Left',
  'quantity': 'Quantity',
  'chargeName': 'Charge Name',
  'otherCharges': 'Other Charges',
  'setharam': 'Setharam',
  'ahimsaSilk': 'Ahimsa Silk',
  'courier': 'Courier',
  'grams': 'Grams',
  'branchNameTamil': 'Branch Name (Tamil)',
  'branchNameEnglish': 'Branch Name (English)',
  'shortBusinessNameLabel': 'Short Business Name (for Bill No)',
  'shortBusinessNameHelper': 'Used as the default prefix for your invoice numbers.',
  'authorizedSignatoryName': 'Authorized Signatory Name',
  'businessNameAsterisk': 'Business Name *',
  'vaniga_nirvagam': 'Manage',
  'english1': 'English',
  'all': 'All',
  'measureType': 'Measure Type',
  'appUserName': 'App User Name',
  'thisNameWillAppearOnTheAppHome': 'This name will appear on the app home screen profile pill.',
  'userName': 'User Name',
  'uPIIDOptional': 'UPI ID (optional)',
  'organizationLogo': 'Organization Logo',
  'upcomingFeature': 'Upcoming Feature',
  'branchTamil': 'Branch (Tamil)',
  'branchEnglish': 'Branch (English)',
  'pachai': 'Green',
  'uudha': 'Violet',
  'eraseAppDataTitle': 'Erase App Data',
  'eraseAppDataDesc': 'Permanently wipe all records.',
  'erasing': 'Erasing...',
  'tooManyRequests': 'Too many attempts. Try later.',
  'nirilBrand': 'Niril',
  'loginSubtitle': 'Login to access your app',
  'signIn': 'Sign In',
  'pleaseFillAllFields': 'Please fill in all fields.',
  'muzhiyayTherthde': 'Select Language',
  'viruppamanaMozhiyayThervuSeiga': 'Choose your preferred language',
  'pattiyalMuthanmozhi': 'Select Primary Billing Language',
  'pattiyalilEmmozhiyayPayanpaduttaVendum': 'Which language would you like to use for your bills?',
  'tharavugalaiUlliduga': 'Enter Business Details',
  'peyaraiUlliduga': 'Enter name',
  'gstPattiyalukkuPayanpadum': 'Used for regular GST invoices.',
  'coolieVanigaPeyar': 'Coolie Business Name',
  'cooliePattiyalMatrumRaseethukkuPayanpadum': 'Used for Coolie bills and receipts.',
  'vanigam': 'Business',
  'vaniga_amaippugal': 'Business Settings',
  'vangi': 'Bank',
  'seyali_amaippugal': 'App Settings',
  'pathugappu_amaippugal': 'Security Settings',
  'thirai': 'Display',
  'pathugappu': 'Security',
  'menporul_vadivalar': 'Software Designer',
  'adaiyalam': 'Identifier',
  'desc_coolie_identifiers': 'Coolie business identifiers',
  'desc_silk_identifiers': 'Silk business identifiers',
  'desc_display': 'Light mode, Dark mode, Auto',
  'erase_data': 'Erase App Data',
  'erase_data_desc': 'Permanently erase data.',
  'backing_up': 'Backing up...',
  'bilingual_entry': 'Bilingual Mode',
  'system_auto': 'System Auto',
  'wideLogoLabel': 'Vertical / Wide Logo',
  'smallLogoBusinessName': 'Small Logo + Business Name',
  'wideLogoOnly': 'Wide Logo Only',
  'upload': 'Upload',
  'oldDataFound': 'Old data available',
  'restoreOldDataSubtitle': 'Your previous data was found. Would you like to restore it?',
  'restoring': 'Restoring data...',

};
