const Map<String, String> en = {
  'welcomeTitle': 'Welcome to Niril',
  'welcomeSubtitle': 'Your Billing & GST, Sorted.',
  'welcomeAgreeText': 'Tap "Get Started" to continue with Niril.',
  'startFreshBtn': 'Start Fresh',

  // ========================================
  // Help Center
  // ========================================
  'hc_businessName': 'Business Name',
  'header_merchants': 'Merchants',
  'header_inventory': 'Products',
  'pill_invoices': 'Invoices',
  'pill_receipts': 'Receipts',
  'reportsSidebar': 'Report',
  'gstReturnsSidebar': 'GST Return',

  // ========================================
  // Settings & Preferences
  // ========================================
  'settings': 'Settings',
  'logout': 'Logout',
  'appLanguage': 'App Language',
  'bankName': 'Bank Name',
  'profileDeleted': 'Profile deleted',
  'maxProfilesReached': 'Maximum 5 profiles allowed',
  'activeProfile': 'Active Profile',
  'createNewProfileModalTitle': 'Create New Profile',
  'permanentlyDeleteProfile': 'Permanently delete this business profile?',
  'addNewProfile': 'Add New Profile',
  'profileSaved': 'Profile saved!',
  'noSavedProfiles': 'No saved profiles yet',
  'accountNumber': 'Account Number',
  'cooliePdfTheme': 'PDF Theme',
  'cooliePrintLanguage': 'Invoice & Receipt Language',
  'password': 'Password',
  'enterPassword': 'Please enter your password',
  'desc_bank': 'Account number & IFSC',
  'desc_language': 'Tamil, English, Auto',
  'desc_security': 'Clear cache, Account security',
  'desc_about': 'Learn more about Elvan',
  'logout_desc': 'Logout from the application.',
  'backup_now': 'Backup Now',
  'backup_now_desc': 'Manually update your backup file.',
  'backup_now_title': 'Backup Database',
  'backup_now_btn': 'Backup Now',
  'backup_success': 'Backup successfully saved to Documents.',
  'primary_language': 'Primary Language',
  'secondary_language': 'Secondary Language',

  // ========================================
  // Merchants & Customers
  // ========================================
  'merchants': 'Merchants',
  'email': 'Email',
  'addClient': 'Add Merchant',
  'oor': 'City',
  'maavattam': 'District',
  'maanilam': 'State',
  'countryLabel': 'Country',
  'phoneNumbers': 'Phone Numbers',
  'pincode': 'Pincode',
  'confirmEmailLabel': 'Confirm Email',
  'emailAddress': 'Email Address',
  'enterEmail': 'Enter your email',
  'desc_address': 'Company address details',

  // ========================================
  // Inventory & Items
  // ========================================
  'inventory': 'Products',
  'addProductBtn': 'Add Product',
  'showItemizedGstTable': 'Show GST splits in table',
  'invoices': 'Invoices',
  'newBill': 'New Bill',
  'receipt': 'Receipt',
  'savedSuccessfully': 'Saved successfully',
  'newInvoiceBtn': 'New Invoice',
  'newReceiptBtn': 'New Receipt',
  'signOutSuccess': 'Signed out successfully',
  'dataErasedSuccess': 'App data erased.',
  'desc_invoice': 'Invoice styling options',
  'billHeaderStyle': 'Bill Header Style',
  'restoreSuccess': 'Data restored successfully!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'reports': 'Reports',
  'gstReturns': 'GST Returns',
  'add': 'Add',
  'search': 'Search...',
  'cancelBtn': 'Cancel',
  'deleteBtn': 'Delete',
  'saveBtn': 'Save',
  'aakku': 'Create',
  'noLogo': 'No Logo',
  'noSignature': 'No Signature',
  'createBtn': 'Create',
  'noneLabel': 'None',
  'selectLabel': 'Select',
  'detailsSaved': 'Details saved successfully',
  'selectYourOperatingMode': 'Select your operating mode',
  'signOutBtn': 'Sign Out',
  'eraseDataBtn': 'Erase Data',
  'signOutConfirmTitle': 'Sign Out?',
  'agreeAndContinueBtn': 'Get Started',
  'restoreBtn': 'Restore Data',

  // ========================================
  // Miscellaneous
  // ========================================
  'appName': 'Niril',
  'continue': 'Continue',
  'home': 'Home',
  'mugavari': 'Address',
  'darkMode': 'Dark Mode',
  'lightMode': 'Light Mode',
  'ifscCode': 'IFSC Code',
  'branchName': 'Branch Name',
  'tamil': 'Tamil',
  'english': 'English',
  'businessLogo': 'Business Logo',
  'signature': 'Signature / Stamp',
  'tholaipesiLabel': 'Phone',
  'mobileLabel': 'Mobile',
  'shortBusinessName': 'Short Business Name',
  'adaimozhi': 'Tagline',
  'nirilCoolie': 'Niril Coolie',
  'nirilSilk': 'Niril Silk',
  'scanAgain': 'Scan Again',
  'vanakkamTitle': 'Vanakkam!',
  'whoIsWorkingToday': 'Who\'s working today?',
  'signing_out': 'Signing out...',
  'authorizedSignatoryName': 'Authorized Signatory Name',
  'vaniga_nirvagam': 'Manage',
  'pachai': 'Green',
  'uudha': 'Violet',
  'erasing': 'Erasing...',
  'loginSubtitle': 'Login to access your app',
  'signIn': 'Sign In',
  'pleaseFillAllFields': 'Please fill in all fields.',
  'pattiyalMuthanmozhi': 'Select Primary Billing Language',
  'pattiyalilEmmozhiyayPayanpaduttaVendum': 'Which language would you like to use for your bills?',
  'tharavugalaiUlliduga': 'Enter Business Details',
  'peyaraiUlliduga': 'Enter name',
  'gstPattiyalukkuPayanpadum': 'Used for regular GST invoices.',
  'coolieVanigaPeyar': 'Coolie Business Name',
  'cooliePattiyalMatrumRaseethukkuPayanpadum': 'Used for Coolie bills and receipts.',
  'vanigam': 'Business',
  'vaniga_amaippugal': 'Business Settings',
  'vangi': 'Bank',
  'seyali_amaippugal': 'App Settings',
  'thirai': 'Display',
  'pathugappu': 'Security',
  'menporul_vadivalar': 'Software Designer',
  'adaiyalam': 'Identifier',
  'desc_coolie_identifiers': 'Coolie business identifiers',
  'desc_silk_identifiers': 'Silk business identifiers',
  'desc_display': 'Light mode, Dark mode, Auto',
  'erase_data': 'Erase App Data',
  'erase_data_desc': 'Permanently erase data.',
  'backing_up': 'Backing up...',
  'bilingual_entry': 'Bilingual Mode',
  'system_auto': 'System Auto',
  'wideLogoLabel': 'Vertical / Wide Logo',
  'smallLogoBusinessName': 'Small Logo + Business Name',
  'wideLogoOnly': 'Wide Logo Only',
  'upload': 'Upload',
  'oldDataFound': 'Old data available',
  'restoreOldDataSubtitle': 'Your previous data was found. Would you like to restore it?',
  'restoring': 'Restoring data...',


  // === Auto Added Keys ===
  'camera': 'Camera',
  'gallery': 'Gallery',
  'selectImageSource': 'Select Image Source',
  'about_developer': 'About Developer',

  'dummyAboutApp': 'About App (Dummy)',
  'dummyAboutDeveloper': 'About Developer (Dummy)',
  'dummyCoolieHome': 'Coolie Home Page',
  'coolieInvoiceEditorLabel': 'Coolie Invoice Editor (Labor Mode)',
  'newCoolieInvoiceTitle': 'New Coolie Invoice',
  'coolieItemEditorLabel': 'Coolie Item Editor',
  'newCoolieItemTitle': 'New Coolie Item',
  'coolieMerchantEditorLabel': 'Coolie Merchant Editor',
  'newCoolieMerchantTitle': 'New Coolie Merchant',
  'coolieReceiptEditorLabel': 'Coolie Receipt Editor',
  'newCoolieReceiptTitle': 'New Coolie Receipt',
  'dummySilkHome': 'Silk Home Page',
  'silkInvoiceEditorLabel': 'Silk Invoice Editor (GST Mode)',
  'newSilkInvoiceTitle': 'New Silk Invoice',
  'silkItemEditorLabel': 'Silk Item Editor',
  'newSilkItemTitle': 'New Silk Item',
  'silkMerchantEditorLabel': 'Silk Merchant Editor',
  'newSilkMerchantTitle': 'New Silk Merchant',
  'silkReceiptEditorLabel': 'Silk Receipt Editor',
  'newSilkReceiptTitle': 'New Silk Receipt',
  'devEraseData': 'Dev: Erase',
  'devSeedData': 'Dev: Seed',
  'seedAppDev': 'Seed App (Dev)',
  'pleaseEnterRequiredBusinessNames': 'Please enter all required business names.',
  'gstinTaxId': 'GSTIN / Tax ID',
};
