const Map<String, String> ta = {
  'welcomeTitle': 'நிறிளிற்கு நல்வரவு',
  'welcomeSubtitle': 'உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.',
  'welcomeAgreeText': 'நிறிளை தொடங்க கீழ் உள்ள பொத்தானை தட்டவும்',
  'startFreshBtn': 'புதியதாக தொடங்கு',

  // ========================================
  // Help Center
  // ========================================
  'hc_businessName': 'வணிகத்தின் பெயர்',
  'header_merchants': 'வணிகர்கள்',
  'header_inventory': 'பொருட்கள்',
  'pill_invoices': 'பட்டியல்கள்',
  'pill_receipts': 'பற்றுச்சீட்டுகள்',
  'reportsSidebar': 'அறிக்கை',
  'gstReturnsSidebar': 'வரி அறிக்கை',

  // ========================================
  // Settings & Preferences
  // ========================================
  'settings': 'அமைப்புகள்',
  'logout': 'வெளியேறு',
  'appLanguage': 'செயலி மொழி',
  'bankName': 'வங்கியின் பெயர்',
  'profileDeleted': 'தன்னுரு நீக்கப்பட்டது',
  'maxProfilesReached': 'பெருமளவு 5 தன்னுருக்கள் மட்டுமே',
  'activeProfile': 'தற்போதைய வணிகம்',
  'createNewProfileModalTitle': 'புதிய தன்னுருவை உருவாக்கு',
  'permanentlyDeleteProfile': 'தன்னுருவை முற்றிலும் நீக்கவா?',
  'addNewProfile': 'புதிய தன்னுரு சேர்',
  'profileSaved': 'தன்னுரு சேமிக்கப்பட்டது!',
  'noSavedProfiles': 'தன்னுருக்கள் இல்லை',
  'accountNumber': 'கணக்கு எண்',
  'cooliePdfTheme': 'PDF தோற்றம்',
  'cooliePrintLanguage': 'பட்டியல் & பற்றுச்சீட்டு மொழி',
  'password': 'கடவுச்சொல்',
  'enterPassword': 'கடவுச்சொல்லை உள்ளிடவும்',
  'desc_bank': 'கணக்கு எண் & IFSC',
  'desc_language': 'தமிழ், ஆங்கிலம், தானியங்கு',
  'desc_security': 'தேக்ககத்தை அழி, கணக்கு பாதுகாப்பு',
  'desc_about': 'எல்வன் பற்றி மேலும் அறிக',
  'logout_desc': 'செயலியிலிருந்து வெளியேறவும்.',
  'backup_now': 'தரவு காப்பு செய்',
  'backup_now_desc': 'உங்கள் தரவை சேமிக்கவும்.',
  'backup_now_title': 'தரவு காப்பு',
  'backup_now_btn': 'காப்பு செய்',
  'backup_success': 'தரவு ஆவணங்களில் சேமிக்கப்பட்டது.',
  'primary_language': 'முதன்மை மொழி',
  'secondary_language': 'இரண்டாம் மொழி',

  // ========================================
  // Merchants & Customers
  // ========================================
  'merchants': 'வணிகர்',
  'email': 'மின்னஞ்சல்',
  'addClient': 'வணிகரைச் சேர்',
  'oor': 'ஊர்',
  'maavattam': 'மாவட்டம்',
  'maanilam': 'மாநிலம்',
  'countryLabel': 'நாடு',
  'phoneNumbers': 'பேசி எண்கள்',
  'pincode': 'அஞ்சல் குறியீடு',
  'confirmEmailLabel': 'மின்னஞ்சலை உறுதிசெய்க',
  'emailAddress': 'மின்னஞ்சல் முகவரி',
  'enterEmail': 'மின்னஞ்சலை உள்ளிடவும்',
  'desc_address': 'நிறுவன முகவரி தரவுகள்',

  // ========================================
  // Inventory & Items
  // ========================================
  'inventory': 'பொருள்',
  'addProductBtn': 'பொருளைச் சேர்',
  'showItemizedGstTable': 'GST பிரிப்புகளைக் காட்டு',
  'invoices': 'பட்டியல்',
  'newBill': 'புதிய பட்டியல்',
  'receipt': 'பற்றுச்சீட்டு',
  'newInvoiceBtn': 'புதிய பட்டியல்',
  'newReceiptBtn': 'புதிய பற்றுச்சீட்டு',
  'signOutSuccess': 'வெற்றிகரமாக வெளியேற்றப்பட்டது',
  'dataErasedSuccess': 'தரவு வெற்றிகரமாக அழிக்கப்பட்டது.',
  'savedSuccessfully': 'வெற்றிகரமாகச் சேமிக்கப்பட்டது',
  'desc_invoice': 'பில் வடிவமைப்பு விருப்பங்கள்',
  'billHeaderStyle': 'சின்னத்தின் வடிவம்',
  'restoreSuccess': 'தரவு வெற்றிகரமாக மீட்டெடுக்கப்பட்டது!',

  // ========================================
  // Expenses & Purchases
  // ========================================
  'reports': 'அறிக்கைகள்',
  'gstReturns': 'வரி அறிக்கைகள்',
  'add': 'சேர்',
  'search': 'தேடுக...',
  'cancelBtn': 'கைவிடு',
  'deleteBtn': 'நீக்கு',
  'saveBtn': 'சேமி',
  'aakku': 'ஆக்கு',
  'noLogo': 'ஓவுரு இல்லை',
  'noSignature': 'கையொப்பம் இல்லை',
  'createBtn': 'உருவாக்கு',
  'noneLabel': 'இல்லை',
  'selectLabel': 'தேர்ந்தெடு',
  'detailsSaved': 'தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன',
  'selectYourOperatingMode': 'உங்கள் கணக்குப் பகுதியைத் தேர்ந்தெடுக்கவும்',
  'signOutBtn': 'வெளியேறு',
  'eraseDataBtn': 'தரவை அழி',
  'signOutConfirmTitle': 'வெளியேற வேண்டுமா?',
  'agreeAndContinueBtn': 'தொடங்குக',
  'restoreBtn': 'மீட்டெடு',

  // ========================================
  // Miscellaneous
  // ========================================
  'appName': 'நிறிள்',
  'continue': 'தொடரவும்',
  'home': 'முகப்பு',
  'mugavari': 'முகவரி',
  'darkMode': 'இருள் நிலை',
  'lightMode': 'ஒளி நிலை',
  'ifscCode': 'IFSC குறியீடு',
  'branchName': 'கிளைப் பெயர்',
  'tamil': 'தமிழ்',
  'english': 'ஆங்கிலம்',
  'businessLogo': 'நிறுவனத்தின் ஓவுரு',
  'signature': 'கையொப்பம்',
  'tholaipesiLabel': 'பேசி எண்',
  'mobileLabel': 'மாற்று பேசி எண்',
  'shortBusinessName': 'குறுகிய வணிக பெயர்',
  'adaimozhi': 'அடைமொழி',
  'nirilCoolie': 'நிறில் கூலி',
  'nirilSilk': 'நிறில் பட்டு',
  'scanAgain': 'மீண்டும் தேடு',
  'signing_out': 'வெளியேறுகிறது...',
  'authorizedSignatoryName': 'அலுவல் கையொப்பத்தின் பெயர்',
  'vaniga_nirvagam': 'நெறியுக',
  'pachai': 'பச்சை',
  'uudha': 'ஊதா',
  'erasing': 'அழிக்கிறது...',
  'vanakkamTitle': 'வணக்கம்!',
  'whoIsWorkingToday': 'இன்று எந்தக் கணக்கு?',
  'loginSubtitle': 'செயலியை அணுக உள்நுழையவும்',
  'signIn': 'உள்நுழைக',
  'pleaseFillAllFields': 'அனைத்து விவரங்களையும் உள்ளிடவும்.',
  'pattiyalMuthanmozhi': 'பட்டியல் முதன்மொழி',
  'pattiyalilEmmozhiyayPayanpaduttaVendum': 'பட்டியலில் எம்மொழியை பயன்படுத்த வேண்டும்?',
  'tharavugalaiUlliduga': 'தரவுகளை உள்ளிடுக',
  'peyaraiUlliduga': 'பெயரை உள்ளிடுக',
  'gstPattiyalukkuPayanpadum': 'வழக்கமான GST பட்டியல்களுக்குப் பயன்படுத்தப்படும்.',
  'coolieVanigaPeyar': 'கூலி வணிகப் பெயர்',
  'cooliePattiyalMatrumRaseethukkuPayanpadum': 'கூலி பட்டியல்கள் மற்றும் பற்றுச்சீட்டுகளுக்குப் பயன்படுத்தப்படும்.',
  'vanigam': 'வணிகம்',
  'vaniga_amaippugal': 'வணிக அமைப்புகள்',
  'vangi': 'வங்கி',
  'seyali_amaippugal': 'செயலி அமைப்புகள்',
  'thirai': 'திரை',
  'pathugappu': 'பாதுகாப்பு',
  'menporul_vadivalar': 'மென்பொருள் வடிவாளர்',
  'seyali_patri': 'செயலி பற்றி',
  'desc_seyali_patri': 'செயலியின் பதிப்பு மற்றும் தரவுகள்',
  'adaiyalam': 'அடையாளம்',
  'desc_coolie_identifiers': 'கூலி வணிக அடையாளங்கள்',
  'desc_silk_identifiers': 'பட்டு வணிக அடையாளங்கள்',
  'desc_display': 'ஒளிர், இருள், தானியங்கு',
  'erase_data': 'செயலித் தரவை அழி',
  'erase_data_desc': 'தரவுகளை முற்றிலும் அழிக்கவும்.',
  'backing_up': 'சேமிக்கப்படுகிறது...',
  'bilingual_entry': 'இருமொழி முறை',
  'system_auto': 'தானியங்கி அமைப்பு',
  'wideLogoLabel': 'செங்குத்து / அகலமான ஓவுரு',
  'smallLogoBusinessName': 'சிறிய ஓவுரு + பெயர்',
  'wideLogoOnly': 'அகலமான ஓவுரு மட்டும்',
  'upload': 'பதிவேற்று',
  'oldDataFound': 'பழைய தரவு கிடைக்கிறது',
  'restoreOldDataSubtitle': 'பழைய தரவை மீட்டெடுக்கவா?',
  'restoring': 'தரவை மீட்டெடுக்கிறது...',


  // === Auto Added Keys ===
  'camera': 'புகைப்படக் கருவி',
  'gallery': 'புகைப்படத் தொகுப்பு',
  'selectImageSource': 'படத்தின் மூலத்தைத் தேர்ந்தெடுக்கவும்',
  'about_developer': 'மென்பொருள் வடிவாளர் பற்றி',

  'dummyAboutApp': 'செயலி பற்றி (மாதிரி)',
  'dummyAboutDeveloper': 'மென்பொருள் வடிவாளர் பற்றி (மாதிரி)',
  'dummyCoolieHome': 'கூலி முகப்புப் பக்கம்',
  'coolieInvoiceEditorLabel': 'கூலிப் பட்டியல் திருத்தி (தொழிலாளர் முறை)',
  'newCoolieInvoiceTitle': 'புதிய கூலிப் பட்டியல்',
  'coolieItemEditorLabel': 'கூலிப் பொருள் திருத்தி',
  'newCoolieItemTitle': 'புதிய கூலிப் பொருள்',
  'coolieMerchantEditorLabel': 'கூலி வணிகர் திருத்தி',
  'newCoolieMerchantTitle': 'புதிய கூலி வணிகர்',
  'coolieReceiptEditorLabel': 'கூலி ரசீது திருத்தி',
  'newCoolieReceiptTitle': 'புதிய கூலி ரசீது',
  'dummySilkHome': 'பட்டு முகப்புப் பக்கம்',
  'silkInvoiceEditorLabel': 'பட்டுப் பட்டியல் திருத்தி (GST முறை)',
  'newSilkInvoiceTitle': 'புதிய பட்டுப் பட்டியல்',
  'silkItemEditorLabel': 'பட்டுப் பொருள் திருத்தி',
  'newSilkItemTitle': 'புதிய பட்டுப் பொருள்',
  'silkMerchantEditorLabel': 'பட்டு வணிகர் திருத்தி',
  'newSilkMerchantTitle': 'புதிய பட்டு வணிகர்',
  'silkReceiptEditorLabel': 'பட்டு ரசீது திருத்தி',
  'newSilkReceiptTitle': 'புதிய பட்டு ரசீது',
  'devEraseData': 'உருவாக்குனர்: தரவுகளை அழி',
  'devSeedData': 'உருவாக்குனர்: தரவுகளை உருவாக்கு',
  'seedAppDev': 'தரவுகளை உருவாக்கு (உருவாக்குனர்)',
  'pleaseEnterRequiredBusinessNames': 'தேவையான அனைத்து வணிகப் பெயர்களையும் உள்ளிடவும்.',
  'gstinTaxId': 'GSTIN / வரி அடையாள எண்',
};
