const Map<String, String> ta = {
  'PIN Code': 'அஞ்சல் குறியீடு',
  'GSTIN': 'GSTIN',
  'Select maanilam': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
  'e.g. Mumbai': 'எ.கா. சென்னை',
  'appName': 'நிறிள்',
  'appNameFull': 'எல்வன் நிறிள்',
  'welcomeBack': 'நல்வரவு!',
  'loading': 'ஏற்றுகிறது...',
  'error': 'பிழை',
  'save': 'சேமி',
  'cancel': 'கைவிடு',
  'back': 'பின்செல்',
  'edit': 'திருத்து',
  'editPrefix': 'திருத்து ',
  'delete': 'நீக்கு',
  'add': 'சேர்',
  'search': 'தேடுக...',
  'print': 'அச்சிடு',
  'done': 'முடிந்தது',
  'selectInvoices': 'பட்டியலைத் தேர்ந்தெடு',
  'searchInvoices': 'தேடவும்...',
  'preview': 'முன்னோட்டம்',
  'actions': 'செயல்கள்',
  'yes': 'ஆம்',
  'no': 'இல்லை',
  'selected': 'தேர்வு',
  'copyDuplicate': 'நகலெடு',
  'connected': 'இணைக்கப்பட்டது',
  'offlineMode': 'இணையமின்றி',
  'connecting': 'இணைகிறது...',
  'home': 'முகப்பு',
  'invoices': 'பட்டியல்',
  'aakku': 'ஆக்கு',
  'uruvakku': 'உருவாக்கு',
  'header_invoices': 'பட்டியல்கள்',
  'accountingGroup': 'கணக்கியல்',
  'reportsGroup': 'அறிக்கைகள்',
  'coolieBill': 'கூலிப் பட்டியல்',
  'silksBill': 'மளிகைப் பட்டியல்',
  'newBill': 'புதிய பட்டியல்',
  'bills': 'பட்டியல்கள்',
  'allBills': 'அனைத்து பட்டியல்கள்',
  'merchants': 'வணிகர்',
  'header_merchants': 'வணிகர்கள்',
  'inventory': 'பொருள்',
  'header_inventory': 'பொருட்கள்',
  'receipts': 'சான்று',
  'receipt': 'பற்றுச்சீட்டு',
  'header_receipts': 'சான்றுகள்',
  'pill_invoices': 'பட்டியல்கள்',
  'pill_receipts': 'பற்றுச்சீட்டுகள்',
  'expenses': 'செலவுகள்',
  'purchases': 'கொள்முதல்',
  'recurring': 'தொடர் பட்டியல்கள்',
  'reports': 'அறிக்கைகள்',
  'gstReturns': 'வரி அறிக்கைகள்',
  'settings': 'அமைப்புகள்',
  'userGuide': 'கையேடு',
  'notifications': 'அறிவிப்புகள்',
  'logout': 'வெளியேறு',
  'darkMode': 'இருள் நிலை',
  'hc_bilingualMode': 'இருமொழி முறை',
  'hc_uiLanguage': 'பயனர் இடைமுக மொழி',
  'hc_enterCustomerName': 'வாடிக்கையாளர் பெயரை உள்ளிடவும்',
  'hc_enterCountryName': 'நாட்டின் பெயரை உள்ளிடுக',
  'lightMode': 'ஒளி நிலை',
  'language': 'மொழி',
  'appPreferences': 'பயன்பாட்டு அமைப்புகள்',
  'bankName': 'வங்கியின் பெயர்',
  'branchName': 'கிளை பெயர்',
  'appLanguage': 'பயன்பாட்டு மொழி',
  'appLanguageAppearance': 'செயலியின் தோற்றம் மற்றும் மொழி அமைப்புகள்',
  'uiLanguageTheme': 'செயலி மொழி, தோற்றம்',
  'languageChangedTa': 'மொழி தமிழுக்கு மாற்றப்பட்டது',
  'languageChangedEn': 'Language changed to English',
  'storageCloud': 'சேமிப்பகம் & முகில்',
  'systemUpdates': 'அமைப்பு & புதுப்பிப்புகள்',
  'systemStorage': 'அமைப்பு நினைவகம்',
  'appVersionsCache': 'செயலி பதிப்புகள், காப்புநகல், தற்காலிக நினைவகம்',
  'name': 'பெயர்',
  'mugavari': 'முகவரி',
  'oor': 'ஊர்',
  'maavattam': 'மாவட்டம்',
  'city': 'ஊர்',
  'district': 'மாவட்டம்',
  'state': 'மாநிலம்',
  'county': 'கவுண்டி',
  'province': 'மாகாணம்',
  'postcode': 'அஞ்சல் குறியீடு',
  'zipCode': 'அஞ்சல் குறியீடு',
  'tamil': 'தமிழ்',
  'english': 'ஆங்கிலம்',
  'hindi': 'இந்தி',
  'telugu': 'தெலுங்கு',
  'kannada': 'கன்னடம்',
  'malayalam': 'மலையாளம்',
  'marathi': 'மராத்தி',
  'gujarati': 'குஜராத்தி',
  'bengali': 'வங்காளம்',
  'tholaipesi': 'தொலைபேசி',
  'email': 'மின்னஞ்சல்',
  'date': 'நாள்',
  'description': 'விளக்கம்',
  'billNo': 'பட்டியல் எண்',
  'invoiceDetails': 'பட்டியல் தரவுகள்',
  'itemsList': 'பொருட்கள்',
  'itemName': 'பொருள் பெயர்',
  'weight': 'எடை',
  'rate': 'கூலி',
  'price': 'விலை',
  'amount': 'தொகை',
  'total': 'மொத்தம்',
  'subTotal': 'உள் மொத்தம்',
  'addAnotherItem': 'புதிய வரிசை',
  'notes': 'குறிப்புகள்',
  'terms': 'வரையறைகள்',
  'newMerchant': 'புதிய வணிகர்',
  'merchantName': 'வணிகர் பெயர்',
  'noMerchants': 'வணிகர்கள் இல்லை',
  'deleteMerchantConfirm': 'இந்த வணிகரை உறுதியாக நீக்க வேண்டுமா?',
  'duplicateCustomersTitle': 'வணிகர்களை நகலெடுக்கவா?',
  'duplicateCustomersMessage': 'தேர்ந்தெடுக்கப்பட்ட {count} வணிகர்களின் நகல்களை உருவாக்க வேண்டுமா?',
  'deleteMerchantsTitle': 'வணிகர்களை நீக்க வேண்டுமா?',
  'deleteMerchantsMessage': 'தேர்ந்தெடுக்கப்பட்ட {count} வணிகரை(களை) நீக்க வேண்டுமா? இதை மாற்ற இயலாது.',
  'customersDuplicatedSuccess': 'வணிகர்கள் வெற்றிகரமாக நகலெடுக்கப்பட்டனர்',
  'newItem': 'புதிய பொருள்',
  'noItems': 'பொருட்கள் இல்லை',
  'deleteItemConfirm': 'இந்த பொருளை உறுதியாக நீக்க வேண்டுமா?',
  'appearance': 'தோற்றம்',
  'account': 'கணக்கு',
  'profile': 'தன்குறிப்பு',
  'security': 'பாதுகாப்பு',
  'dataBackup': 'தரவு காப்பு',
  'cloudSync': 'ஒத்திசைவு',
  'about': 'பற்றி',
  'businessProfile': 'நிறுவனத் தரவுகள்',
  'bankDetails': 'வங்கித் தரவுகள்',
  'companyName': 'நிறுவன பெயர்',
  'accountNo': 'கணக்கு எண்',
  'ifscCode': 'IFSC குறியீடு',
  'kilai': 'கிளை',
  'successSaved': 'வெற்றிகரமாக சேமிக்கப்பட்டது!',
  'errorSaveFailed': 'சேமிப்பதில் தோல்வி:',
  'noDataAvailable': 'தகவல் இல்லை',
  'billedTo': 'வணிகர்',
  'clientName': 'வணிகர் பெயர்',
  'billingAddress': 'பட்டியல் முகவரி',
  'country': 'நாடு',
  'pinCode': 'அஞ்சல் குறியீடு',
  'maanilam': 'மாநிலம்',
  'gstin': 'GSTIN',
  'invoiceDetailsForm': 'பட்டியல் தரவுகள்',
  'invoiceNumber': 'பட்டியல் எண்',
  'invoiceDate': 'பட்டியல் நாள்',
  'dueDate': 'கெடு நாள்',
  'placeOfSupply': 'வழங்கும் இடம்',
  'lineItems': 'பொருட்கள்',
  'pricesIncludeTax': 'வரிகள் அடங்கும்',
  'hsnSac': 'HSN/SAC',
  'qty': 'அளவு',
  'unit': 'அலகு',
  'discount': 'தள்ளுபடி',
  'cess': 'செஸ் %',
  'settingsTitle': 'அமைப்புகள்',
  'settingsSubtitle': 'நிறுவனத் தரவுகள், வணிக அடையாளம் & தரவுகள்',
  'modulesTitle': 'தொகுதிகள்',
  'settingsDesc': 'உங்கள் செயலி அமைப்புகள் மற்றும் விருப்பங்களை நிர்வகிக்கவும்.',
  'switchProfile': 'தன்னுருவை மாற்றவும்',
  'noLogo': 'சின்னம் இல்லை',
  'logoUploaded': 'சின்னம் பதிவேற்றப்பட்டது',
  'wideLogoUploaded': 'நீண்ட சின்னம் பதிவேற்றப்பட்டது',
  'noSignature': 'கையொப்பம் இல்லை',
  'modulesDesc': 'உங்களுக்குத் தேவையில்லாத அம்சங்களை முடக்கலாம்.',
  'regionTitle': 'பகுதி முன்னுரிமை',
  'regionDesc': 'பயன்பாடு எவ்வாறு செயல்பட வேண்டும் என்பதைத் தேர்ந்தெடுக்கவும்.',
  'companyDetailsTitle': 'நிறுவனத் தரவுகள்',
  'paymentAccountsTitle': 'கட்டணக் கணக்குகள்',
  'paymentAccountsDesc': 'ஒரு தன்னுருவிற்கு பல வங்கி/UPI கணக்குகள்.',
  'invoiceNumberFormatTitle': 'பட்டியல் எண் வடிவம்',
  'brandingTitle': 'வணிக அடையாளம்',
  'businessLogo': 'நிறுவனத்தின் சின்னம்',
  'signature': 'கையொப்பம்',
  'cloudBackupTitle': 'கிளவுட் காப்பு (Google Drive)',
  'cloudBackupDesc': 'உங்கள் பட்டியல்களை Google Drive உடன் தானாக ஒத்திசைக்கலாம்.',
  'exportImportTitle': 'தரவு ஏற்றுமதி & இறக்குமதி',
  'exportImportDesc': 'உங்கள் தரவை உள்ளூரில் பாதுகாப்பாக காப்பு எடுக்கலாம்.',
  'resetToDefault': 'இயல்புநிலைக்கு மீட்டமை',
  'moduleGroup_sales': 'விற்பனை & பட்டியல்கள்',
  'moduleDesc_sales': 'பட்டியல் உருவாக்கம், தொடர் பட்டியல்கள், கட்டணப் பற்றுச்சீட்டுகள்',
  'module_invoicing': 'வரி பட்டியல்கள், மதிப்பீட்டுப் பட்டியல்கள், கடன் குறிப்புகள்',
  'module_recurring': 'தொடர் பட்டியல்கள்',
  'module_receipts': 'கட்டணப் பற்றுச்சீட்டுகள்',
  'moduleGroup_directory': 'அடைவு',
  'moduleDesc_directory': 'வணிகர்கள் மற்றும் பொருள் பட்டியல்',
  'module_clients': 'வணிகர்கள்',
  'module_inventory': 'பொருட்கள் & சேவைகள்',
  'moduleGroup_purchases': 'கொள்முதல் & செலவுகள்',
  'moduleDesc_purchases': 'விற்பனையாளர் பட்டியல்கள், செலவு கண்காணிப்பு, ITC',
  'module_expenses': 'செலவு கண்காணிப்பு',
  'module_purchases': 'கொள்முதல் பட்டியல்கள்',
  'module_gstr2b': 'GSTR-2B பொருத்தம்',
  'moduleGroup_gst': 'GST & வரி',
  'moduleDesc_gst': 'GSTR தாக்கல், e-Way Bill, TDS/TCS, HSN சுருக்கம்',
  'module_gstReturns': 'GSTR-1 / GSTR-3B ஏற்றுமதி & வழிகாட்டி',
  'module_ewayBill': 'E-Way Bill JSON ஏற்றுமதி',
  'module_tdsTcs': 'பட்டியல்களில் TDS / TCS',
  'moduleGroup_reports': 'அறிக்கைகள்',
  'moduleDesc_reports': 'முகப்பு பலகை மற்றும் நிதி அறிக்கைகள்',
  'module_dashboard': 'முகப்பு பலகை',
  'module_reports': 'அறிக்கைகள் பார்வை',
  'moduleGroup_integrations': 'ஒருங்கிணைப்புகள்',
  'moduleDesc_integrations': 'கிளவுட் காப்பு & QR குறியீடுகள்',
  'module_upiQr': 'பட்டியல்களில் UPI QR குறியீடு',
  'businessNameLabel': 'நிறுவனத்தின் பெயர்',
  'countryLabel': 'நாடு',
  'mugavariLabel': 'முகவரி',
  'oorLabel': 'ஊர் / நகரம்',
  'emailLabel': 'மின்னஞ்சல்',
  'tholaipesiLabel': 'தொலைபேசி',
  'mobileLabel': 'கைபேசி',
  'orgNameEn': 'நிறுவனத்தின் பெயர் (ஆங்கிலத்தில்)',
  'shortBusinessName': 'குறுகிய வணிக பெயர்',
  'shortBusinessNameHint': 'இது தானியங்கி பில் எண்ணில் முன்னொட்டாக பயன்படுத்தப்படும்.',
  'phoneNumbers': 'தொலைபேசி எண்கள்',
  'address': 'முகவரி',
  'contactBank': 'தொடர்பு & வங்கி',
  'businessSettings': 'வணிக அமைப்புகள்',
  'bank': 'வங்கி',
  'branding': 'வணிக அடையாளம்',
  'invoiceSettings': 'பட்டியல் அமைப்புகள்',
  'languageSettings': 'மொழி அமைப்புகள்',
  'nirilCoolie': 'நிறில் கூலி',
  'nirilSilk': 'நிறில் பட்டு',
  'companyAddressDetails': 'நிறுவனத்தின் முகவரி தரவுகள்',
  'logoSignatures': 'சின்னம் & கையொப்பம்',
  'accountNumberIfsc': 'கணக்கு எண், IFSC',
  'invoiceTab': 'பட்டியல்',
  'invoiceStylingOptions': 'பட்டியல் வடிவமைப்பு அமைப்புகள்',
  'languages': 'மொழிகள்',
  'dataEntryLanguages': 'தரவு உள்ளீடு மொழிகள்',
  'colorsTheme': 'நிறங்கள் & கருப்பொருள்',
  'createNewBusinessProfile': 'புதிய வணிக தன்னுருவை உருவாக்கு',
  'businessName': 'நிறுவனத்தின் பெயர் (Business Name)',
  'gstinOptional': 'GSTIN (விரும்பினால்)',
  'addressOptional': 'முகவரி (Address)',
  'fillDetailsLater': 'பிற விவரங்களை பின்னர் அமைப்புகள் மூலம் சேர்க்கலாம்.',
  'creating': 'உருவாக்குகிறது...',
  'createBtn': 'உருவாக்கு',
  'unsavedChangesContinue': 'சேமிக்கப்படாத மாற்றங்கள் உள்ளன. தொடரவா?',
  'continue': 'தொடரவும்',
  'profileDeleted': 'தன்னுரு நீக்கப்பட்டது',
  'changesDiscarded': 'மாற்றங்கள் நிராகரிக்கப்பட்டன',
  'settingsSaved': 'அமைப்புகள் சேமிக்கப்பட்டன',
  'activeProfile': 'தற்போதைய வணிகம்',
  'closeBtn': 'மூடுக',
  'manageBtn': 'நெறி',
  'addNewBtn': 'புதிய',
  'createNewProfileModalTitle': 'புதிய தன்னுருவை உருவாக்கு',
  'businessNameStar': 'நிறுவனத்தின் பெயர் *',
  'businessNameEnglish': 'நிறுவனத்தின் பெயர் (ஆங்கிலத்தில்)',
  'cancelBtn': 'கைவிடு',
  'manageBusinessProfilesModalTitle': 'வணிக தன்னுருக்களை நெறி',
  'noSavedProfilesYet': 'தன்னுருக்கள் இல்லை',
  'currentlyEditing': 'தற்போது திருத்தப்படுகிறது',
  'deleteBtn': 'நீக்கு',
  'confirmDeleteModalTitle': 'உறுதிப்படுத்தவும்',
  'permanentlyDeleteProfile': 'தன்னுருவை நிரந்தரமாக நீக்கவா?',
  'includeFinancialYear': 'பொருளாண்டை சேர்க்கவா',
  'yesFinYear': 'ஆம் (2026-27)',
  'numberPadding': 'எண் இலக்கங்கள்',
  'digits3': '3 இலக்கங்கள் (001)',
  'digits4': '4 இலக்கங்கள் (0001)',
  'digits5': '5 இலக்கங்கள் (00001)',
  'digits6': '6 இலக்கங்கள் (000001)',
  'saving': 'சேமிக்கப்படுகிறது...',
  'saveNumberFormat': 'சேமி',
  'uploadLogo': 'சின்னத்தை பதிவேற்று',
  'logoHint': 'PNG அல்லது JPG, (அதிகபட்சம் 500KB)',
  'uploadSignature': 'கையொப்பத்தை பதிவேற்று',
  'sigHint': 'PNG, JPG (அதிகபட்சம் 500KB)',
  'saveProfile': 'சேமி',
  'termsTemplatesTitle': 'விதிமுறைகள் & வரையறைகள் வார்ப்புருக்கள்',
  'newTemplate': 'புதிய வார்ப்புரு',
  'termsTemplatesDesc': 'மீண்டும் பயன்படுத்தக்கூடிய வார்ப்புருக்களை உருவாக்கவும் அல்லது கீழேயுள்ளவற்றிலிருந்து தேர்ந்தெடுக்கவும்.',
  'quickStartTemplate': 'விரைவான தொடக்கம் — உங்கள் வணிகத்திற்கான வார்ப்புருவைத் தேர்ந்தெடுக்கவும்:',
  'templateName': 'வார்ப்புரு பெயர்',
  'templateContent': 'உள்ளடக்கம் (உங்கள் விதிமுறைகளை இங்கே ஒட்டவும்)',
  'saveTemplate': 'சேமி',
  'noTemplates': 'வார்ப்புருக்கள் இல்லை',
  'businessProfilesTitle': 'வணிக தன்னுருக்கள்',
  'addNewProfile': 'புதிய தன்னுரு சேர்',
  'saveAsProfile': 'சேமி',
  'businessProfilesDesc1': 'பல வணிக தன்னுருக்களைச் சேமித்து, அவற்றை உடனடியாக மாற்றிக் கொள்ளலாம்.',
  'businessProfilesDesc2': 'தன்னுருக்கள் இல்லை',
  'appUpdatesTitle': 'பயன்பாட்டு புதுப்பிப்புகள்',
  'appStorageDesc': 'தற்காலிக நினைவகம்',
  'appUpdatesDesc': 'புதிய பதிப்பு உள்ளதா என சரிபார்க்கவும்.',
  'checkingUpdate': 'சரிபார்க்கப்படுகிறது...',
  'checkForUpdates': 'புதுப்பிப்புகளை சரிபார்',
  'dataManagementTitle': 'தரவு மேலாண்மை (Data Management)',
  'dataNoticeText': '<strong>உங்கள் தரவு இந்தக் கணினியில் மட்டுமே உள்ளது.</strong> எங்களுக்கு, எங்கள் சேவையகங்களுக்கு அல்லது எந்த மூன்றாம் தரப்பினருக்கும் எதுவும் பதிவேற்றப்படவில்லை. நீங்கள் வெளிப்படையாகக் கோரும்போது மட்டுமே தரவு உங்கள் சொந்த Google Drive-க்குச் செல்லும்.',
  'dataManagementDesc': 'எதை காப்புப் பிரதி எடுக்க வேண்டும் அல்லது மீட்டெடுக்க வேண்டும் என்பதைத் தேர்வுசெய்க. காப்பு கோப்புகளை USB டிரைவ் அல்லது Google Drive-ல் பாதுகாப்பாக வைக்கலாம்.',
  'exportBackup': 'காப்புப் பிரதியை ஏற்றுமதி செய்...',
  'importBackup': 'காப்புப் பிரதியை இறக்குமதி செய்...',
  'recentActivity': 'நடப்பு வினைகள்',
  'totalItems': 'மொத்தம்',
  'seeAll': 'யாவும்',
  'newInvoice': 'புதிய பட்டியல்',
  'editInvoice': 'பட்டியலைத் திருத்து',
  'item': 'பொருள்',
  'dashboard': 'முகப்பு',
  'companies': 'நிறுவனங்கள்',
  'totalBills': 'பட்டியல் எண்ணிக்கை',
  'greeting': 'வணக்கம்',
  'primaryLanguage': 'முதன்மை மொழி',
  'secondaryLanguage': 'இரண்டாம் மொழி',
  'bilingualBills': 'இருமொழிப் பதிவு',
  'enabled': 'ஆம்',
  'disabled': 'இல்லை',
  'languagesUsedForBilling': 'பட்டியல் உருவாக்கத்தில் பயன்படுத்தப்படும் மொழிகள்',
  'enableBilingualBills': 'இருமொழிப் பதிவு',
  'showItemizedGstTable': 'GST பிரிப்புகளைக் காட்டு',
  'displayDetailedItemizedGst': 'ஒவ்வொரு பொருளுக்கும் தனித்தனியாக ஜிஎஸ்டி விவரங்களை காண்பி',
  'overviewOfInvoices': 'உங்கள் பட்டியல்களின் சுருக்கம்',
  'totalInvoiced': 'மொத்த பட்டியல்',
  'taxCollected': 'வசூலித்த வரி',
  'outstanding': 'நிலுவை',
  'invoicesCount': 'பட்டியல்கள்',
  'searchClientOrInvoice': 'வணிகர் அல்லது பட்டியலைத் தேடுக...',
  'allYears': 'அனைத்து ஆண்டுகளும்',
  'allTypes': 'அனைத்து வகைகளும்',
  'allStatus': 'அனைத்து நிலைகளும்',
  'noInvoicesYet': 'பட்டியல்கள் இல்லை',
  'noInvoicesMatch': 'பொருத்தமான பட்டியல்கள் இல்லை',
  'createInvoiceBtn': 'பட்டியலை உருவாக்கு',
  'dateCol': 'நாள்',
  'invoiceNoCol': 'பட்டியல் எண்',
  'typeCol': 'வகை',
  'clientCol': 'வணிகர்',
  'amountCol': 'தொகை',
  'paidCol': 'செலுத்தப்பட்டது',
  'statusCol': 'நிலை',
  'actionsCol': 'செயல்கள்',
  'status_unpaid': 'செலுத்தப்படாதவை',
  'status_partial': 'பகுதி செலுத்தியவை',
  'status_paid': 'செலுத்தியவை',
  'status_overdue': 'காலக்கெடு முடிந்தது',
  'draftOnly': 'சேமிக்கப்படவில்லை',
  'downloadPdf': 'PDF பதிவிறக்கு',
  'whatsapp': 'வாட்ஸ்அப்',
  'ewayBill': 'E-Way Bill',
  'invoiceType': 'பட்டியல் வகை',
  'customize': 'தனிப்பயனாக்கு',
  'thisInvoiceIsFor': 'இந்த பட்டியல் இதற்கானது:',
  'goods': 'பொருட்கள்',
  'services': 'சேவைகள்',
  'mixed': 'இரண்டும்',
  'typeClientName': 'வணிகரைத் தேடுக அல்லது சேர்க்க',
  'egMumbai': 'எ.கா. சென்னை',
  'selectState': 'மாநிலத்தை தேர்வு செய்க',
  'optionalLabel': 'விருப்பத்திற்குரியது',
  'pdfPreviewHeader': 'PDF முன்னோட்டம் — உங்கள் பட்டியல் இப்படித்தான் இருக்கும்',
  'termsAndConditionsLabel': 'விதிமுறைகள் & வரையறைகள்',
  'invoiceTypes_tax_invoice': 'வரிப் பட்டியல்',
  'invoiceTypes_proforma': 'மதிப்பீட்டுப் பட்டியல்',
  'invoiceTypes_bill_of_supply': 'வழங்கல் சீட்டு',
  'invoiceTypes_composition': 'கலவை வரிப் பட்டியல்',
  'invoiceTypes_credit_note': 'வரவுக் குறிப்பு',
  'invoiceTypes_delivery_challan': 'வழங்கல் சீட்டு',
  'invoiceDesc_tax_invoice': 'பொருட்கள் விற்பனைக்கான சாதாரண வரிப் பட்டியல்',
  'invoiceDesc_proforma': 'விற்பனைக்கு முந்தைய மதிப்பீடு',
  'invoiceDesc_bill_of_supply': 'வரி விலக்கு அளிக்கப்பட்ட பொருட்களுக்கான பட்டியல்',
  'invoiceDesc_composition': 'காம்போசிஷன் திட்டத்தின் கீழ் உள்ள வணிகங்களுக்கானது',
  'invoiceDesc_credit_note': 'விற்பனைத் திருப்பம் அல்லது தொகையைக் குறைக்க',
  'invoiceDesc_delivery_challan': 'பொருட்களை வேலைக்கு அல்லது வேறு கிளைக்கு அனுப்ப',
  'totalDueLabel': 'செலுத்த வேண்டிய மொத்தத் தொகை',
  'descriptionCol': 'விளக்கம்',
  'hsnSacCol': 'HSN/SAC',
  'rateCol': 'விலை',
  'addItemBtn': 'சேர்',
  'termsHeading': 'விதிமுறைகள் & வரையறைகள்',
  'insertPreset': 'முன்-அமைப்பைச் செருகு',
  'pickBusinessType': 'வணிக வகையைத் தேர்ந்தெடு',
  'indiaSpecificStarter': 'இந்திய வணிகங்களுக்கான மாதிரி வரிகள். தேவைக்கேற்ப திருத்தலாம்.',
  'loadSavedTemplate': 'வார்ப்புருவை ஏற்று',
  'termsAppearsOnInvoice': 'விதிமுறைகள் (பட்டியலில் தோன்றும் — rich formatting ஆதரவு)',
  'privateNote': 'தனிப்பட்ட குறிப்பு (பட்டியலில் தோன்றாது)',
  'privateNoteEg': 'எ.கா. வணிகர் 15 நாள் கடன் கேட்டார், ரவியால் பரிந்துரைக்கப்பட்டது...',
  'additionalPages': 'கூடுதல் பக்கங்கள் / பிரிவுகள்',
  'addSectionBtn': 'பிரிவைச் சேர்',
  'addExtraSectionsDesc': 'பட்டியல் அடிக்குறிப்புக்குப் பிறகு தோன்றும் கூடுதல் பிரிவுகளைச் சேர்க்கவும். (HTML உள்ளடக்கத்தை ஒட்டலாம்).',
  'noExtraSections': 'பிரிவுகள் இல்லை',
  'clientsTitle': 'வணிகர்கள்',
  'clientsSubtitle': 'வணிகர் வாரியான பட்டியல் மற்றும் நிலுவை',
  'importCSV': 'CSV ஐ இறக்குமதி செய்',
  'addClient': 'வணிகரைச் சேர்',
  'newInvoiceBtn': 'புதிய பட்டியல்',
  'searchClients': 'வணிகர்களைத் தேட...',
  'noClientsFound': 'வணிகர்கள் இல்லை',
  'addFirstClient': '',
  'invoiceCountSingular': 'பட்டியல்',
  'totalLabel': 'மொத்தம்',
  'paidLabel': 'செலுத்தப்பட்டது',
  'overdueLabel': 'காலதாமதம்',
  'invoiceModeGoods': 'பொருட்கள்',
  'invoiceModeServices': 'சேவைகள்',
  'invoiceModeMixed': 'இரண்டும்',
  'noneLabel': 'இல்லை',
  'selectLabelGeneric': 'தேர்ந்தெடு',
  'langTamil': 'தமிழ்',
  'langEnglish': 'ஆங்கிலம்',
  'langHindi': 'இந்தி',
  'langTelugu': 'தெலுங்கு',
  'langKannada': 'கன்னடம்',
  'langMalayalam': 'மலையாளம்',
  'langMarathi': 'மராத்தி',
  'langGujarati': 'குஜராத்தி',
  'langBengali': 'வங்காளம்',
  'paymentCash': 'பணம்',
  'paymentUPI': 'UPI',
  'paymentBank': 'வங்கிப் பரிமாற்றம்',
  'paymentCheque': 'காசோலை',
  'paymentCard': 'கார்டு',
  'paymentOther': 'மற்றவை',
  'outstandingLabel': 'நிலுவை',
  'hideLabel': 'மறை',
  'viewLabel': 'காண்பி',
  'noInvoicesForClient': 'பட்டியல்கள் இல்லை',
  'removeSavedClientConfirm': 'இந்த வணிகரை அகற்ற வேண்டுமா?',
  'clientRemoved': 'வணிகர் அகற்றப்பட்டார்',
  'deleteInvoiceConfirm': 'இந்த பட்டியலை நீக்க வேண்டுமா? இதை மாற்ற இயலாது.',
  'invoiceDeleted': 'பட்டியல் நீக்கப்பட்டது',
  'failedToDelete': 'நீக்க முடியவில்லை',
  'editClientBtn': 'திருத்து',
  'deleteClientBtn': 'நீக்கு',
  'saveAsClientBtn': 'சேமி',
  'editClientTitle': 'வணிகரைத் திருத்து',
  'addNewClientTitle': 'புதிய வணிகரைச் சேர்',
  'clientBusinessName': 'வணிகர் / நிறுவனத்தின் பெயர்',
  'clientNamePlaceholder': 'எ.கா. எல்வன் நிறுவனம்',
  'clientNamePlaceholderEn': 'வணிகர் பெயர் (ஆங்கிலத்தில்)',
  'streetAddressPlaceholder': 'தெரு முகவரி, பகுதி',
  'addressPlaceholderEn': 'முகவரி (ஆங்கிலத்தில்)',
  'cityPlaceholder': 'எ.கா. சென்னை',
  'cityPlaceholderEn': 'நகரம் (ஆங்கிலத்தில்)',
  'districtPlaceholder': 'மாவட்டம்',
  'districtPlaceholderEn': 'மாவட்டம் (ஆங்கிலத்தில்)',
  'countryPlaceholderEn': 'நாடு (ஆங்கிலத்தில்)',
  'selectLabel': 'தேர்ந்தெடு',
  'emailPlaceholder': 'client@example.com',
  'phoneLabel': 'தொலைபேசி',
  'phonePlaceholder': '+91 98765 43210',
  'sezUnitTitle': 'SEZ / Developer — மாநிலத்தைப் பொருட்படுத்தாமல் IGST விதிக்கப்படும் (பிரிவு 16, IGST சட்டம்).',
  'updateClientModalBtn': 'புதுப்பி',
  'saveClientModalBtn': 'சேமி',
  'cancelModalBtn': 'கைவிடு',
  'confirmModalBtn': 'உறுதி செய்',
  'inventoryTitle': 'பொருட்கள்',
  'inventorySubtitle': 'உங்கள் பொருட்கள் மற்றும் சேவைகளை நெறியுக',
  'addProductBtn': 'பொருளைச் சேர்',
  'searchProducts': 'தேடுக...',
  'editProductTitle': 'பொருளைத் திருத்து',
  'addProductTitle': 'புதிய பொருளைச் சேர்',
  'productNameLabel': 'பொருள் / சேவை பெயர்',
  'productNamePlaceholder': 'எ.கா. இணையதளம் உருவாக்குதல்',
  'hsnCodeLabel': 'HSN / SAC குறியீடு',
  'hsnCodePlaceholder': 'எ.கா. 998314',
  'rateLabel': 'விலை (அடிப்படை விலை)',
  'gstPercentLabel': 'GST %',
  'unitLabel': 'அலகு',
  'stockQuantityLabel': 'கையிருப்பு அளவு',
  'descriptionLabelOptional': 'விளக்கம் (விரும்பினால்)',
  'descriptionPlaceholder': 'சுருக்கமான விளக்கம்...',
  'productsAndServices': 'பொருட்கள் & சேவைகள்',
  'noProductsYet': 'பொருட்கள் இல்லை',
  'noProductsMatch': 'பொருத்தமான பொருட்கள் இல்லை',
  'outOfStock': 'கையிருப்பு இல்லை',
  'productUpdatedToast': 'பொருள் புதுப்பிக்கப்பட்டது',
  'productAddedToast': 'பொருள் சேர்க்கப்பட்டது',
  'productNameRequiredToast': 'பொருளின் பெயர் அவசியம்',
  'deleteProductConfirmMsg': 'இந்தப் பொருளை நீக்க வேண்டுமா? இதை மாற்ற இயலாது.',
  'productDeletedToast': 'பொருள் நீக்கப்பட்டது',
  'failedToSaveProductToast': 'பொருளைச் சேமிக்க முடியவில்லை',
  'failedToLoadProductsToast': 'பொருட்களை ஏற்ற முடியவில்லை',
  'emptyCsvWarningToast': 'CSV கோப்பு காலியாக உள்ளது',
  'failedToParseCsvToast': 'CSV கோப்பைப் படிக்க முடியவில்லை',
  'nameCol': 'பெயர்',
  'hsnCol': 'HSN',
  'stockCol': 'கையிருப்பு',
  'receiptsSubtitle': 'வணிகர்களுக்கான கட்டணப் பற்றுச்சீட்டுகளை உருவாக்கவும்',
  'newReceiptBtn': 'புதிய பற்றுச்சீட்டு',
  'newPaymentReceiptTitle': 'புதிய கட்டணப் பற்றுச்சீட்டு',
  'editReceiptTitle': 'பற்றுச்சீட்டைத் திருத்து',
  'quickSelectUnpaid': 'நிலுவைப் பட்டியல்கள்',
  'receiptNoLabel': 'பற்றுச்சீட்டு எண்',
  'dateLabel': 'நாள்',
  'receivedFromLabel': 'பெறப்பட்டது (வணிகர் பெயர்)',
  'amountLabelStar': 'தொகை',
  'paymentModeLabel': 'கட்டண முறை',
  'referenceNoLabel': 'குறிப்பு எண்',
  'againstInvoiceLabel': 'எந்தப் பட்டியலுக்கு',
  'againstInvoicePlaceholder': 'எ.கா. INV/2025-26/0001',
  'noteOptionalLabel': 'குறிப்பு (விரும்பினால்)',
  'saveReceiptBtn': 'சேமி',
  'searchReceipts': 'பற்றுச்சீட்டுகளைத் தேட...',
  'paymentReceiptsTableTitle': 'கட்டணப் பற்றுச்சீட்டுகள்',
  'noReceiptsYet': 'பற்றுச்சீட்டுகள் இல்லை',
  'noReceiptsMatch': 'பொருத்தமான பற்றுச்சீட்டுகள் இல்லை',
  'createReceiptBtn': 'ரசீதை உருவாக்கு',
  'againstInvoiceCol': 'எந்தப் பட்டியலுக்கு',
  'modeCol': 'கட்டண முறை',
  'clientNameRequiredToast': 'வணிகர் பெயர் அவசியம்',
  'enterValidAmountToast': 'சரியான தொகையை உள்ளிடவும்',
  'receiptSavedToast': 'பற்றுச்சீட்டு சேமிக்கப்பட்டது',
  'deleteReceiptConfirmMsg': 'இந்த ரசீதை நீக்க வேண்டுமா?',
  'deletedToast': 'நீக்கப்பட்டது',
  'expensesSubtitle': 'P&L மற்றும் ITC கோரிக்கைகளுக்கான வணிக செலவுகளைக் கண்காணிக்கவும்',
  'exportCsvBtn': 'CSV ஏற்றுமதி செய்',
  'addExpenseBtn': 'செலவைச் சேர்',
  'totalExpensesCard': 'மொத்த செலவுகள்',
  'gstPaidCard': 'செலுத்திய GST (ITC)',
  'entriesCard': 'பதிவுகள்',
  'searchExpenses': 'செலவுகளைத் தேட...',
  'allCategoriesFilter': 'அனைத்து பிரிவுகளும்',
  'expenseRecordsTable': 'செலவு பதிவுகள்',
  'noExpensesYet': 'செலவுகள் இல்லை',
  'noExpensesMatch': 'பொருத்தமான செலவுகள் இல்லை',
  'editExpenseTitle': 'செலவைத் திருத்து',
  'addExpenseTitle': 'செலவைச் சேர்',
  'dateLabelStar': 'நாள்',
  'categoryLabel': 'பிரிவு',
  'descriptionLabelStar': 'விளக்கம்',
  'descriptionPlaceholderExp': 'எ.கா. இணையதளப் பராமரிப்பு - ஏப்ரல்',
  'amountGstLabelStar': 'தொகை (GST உட்பட)',
  'gstPercentItcLabel': 'GST %',
  'vendorNameLabel': 'விற்பனையாளர் பெயர்',
  'vendorNameOptional': 'விருப்பத்திற்குரியது',
  'vendorGstinLabel': 'விற்பனையாளர் GSTIN',
  'vendorGstinHint': 'ITC கோரிக்கைக்கு',
  'invoiceBillNoLabel': 'பட்டியல் எண்',
  'descriptionRequiredToast': 'விளக்கம் அவசியம்',
  'enterValidAmountToastExp': 'சரியான தொகையை உள்ளிடவும்',
  'expenseUpdatedToast': 'செலவு புதுப்பிக்கப்பட்டது',
  'expenseAddedToast': 'செலவு சேர்க்கப்பட்டது',
  'failedToSaveExpenseToast': 'செலவைச் சேமிக்க முடியவில்லை',
  'deleteExpenseConfirmMsg': 'இந்தச் செலவை நீக்க வேண்டுமா?',
  'expenseDeletedToast': 'செலவு நீக்கப்பட்டது',
  'noExpensesToExportToast': 'ஏற்றுமதி செய்ய எந்த செலவும் இல்லை',
  'expensesCsvDownloadedToast': 'செலவுகள் CSV பதிவிறக்கப்பட்டது',
  'gstCol': 'GST',
  'vendorCol': 'விற்பனையாளர்',
  'purchasesSubtitle': 'GSTR-3B இல் ITC கோருவதற்கு சப்ளையர் பில்களைக் கண்காணிக்கவும்',
  'addPurchaseBtn': 'கொள்முதலைச் சேர்',
  'totalPurchasesCard': 'மொத்த கொள்முதல்',
  'gstItcEligibleCard': 'GST (ITC தகுதியுடையது)',
  'searchSupplierInvoice': 'சப்ளையர், பில் தேட...',
  'purchaseRecordsTable': 'கொள்முதல் பதிவுகள்',
  'noPurchaseBillsYet': 'கொள்முதல் இல்லை',
  'noPurchasesMatch': 'பொருத்தமான கொள்முதல் இல்லை',
  'editPurchaseBillTitle': 'கொள்முதல் பட்டியலைத் திருத்து',
  'addPurchaseBillTitle': 'கொள்முதல் பட்டியலைச் சேர்',
  'paymentStatusLabel': 'பணம் செலுத்தும் நிலை',
  'supplierNameLabel': 'சப்ளையர் பெயர்',
  'supplierNamePlaceholder': 'விற்பனையாளர் / சப்ளையர் பெயர்',
  'supplierGstinLabel': 'சப்ளையர் GSTIN',
  'supplierGstinPlaceholder': '15-இலக்க GSTIN',
  'invoiceNumberLabel': 'பட்டியல் எண்',
  'invoiceNumberPlaceholder': 'சப்ளையர் பட்டியல் எண்',
  'interstatePurchaseLabel': 'மாநிலங்களுக்கு இடையேயான கொள்முதல்',
  'interstatePurchaseDesc': 'சப்ளையர் IGST வசூலித்துள்ளார் (வேறு மாநிலம்)',
  'interstatePurchaseTip': 'CGST + SGST-க்கு பதிலாக GSTR-3B இல் ITC-ஐ IGST-க்கு மாற்றுகிறது. குறிப்பு: சப்ளையர் GSTIN இன் முதல் 2 இலக்கங்கள் = அவர்களின் மாநிலக் குறியீடு.',
  'itemsTitle': 'பொருட்கள்',
  'qtyCol': 'அளவு',
  'taxPercentCol': 'வரி %',
  'taxableLabelText': 'வரிக்குட்பட்டது:',
  'taxLabelText': 'வரி:',
  'totalLabelText': 'மொத்தம்:',
  'supplierNameRequiredToast': 'சப்ளையர் பெயர் அவசியம்',
  'invoiceNumberRequiredToast': 'பட்டியல் எண் அவசியம்',
  'purchaseUpdatedToast': 'கொள்முதல் புதுப்பிக்கப்பட்டது',
  'purchaseAddedToast': 'கொள்முதல் சேர்க்கப்பட்டது',
  'failedToSavePurchaseToast': 'கொள்முதலைச் சேமிக்க முடியவில்லை',
  'failedToLoadPurchasesToast': 'கொள்முதலை ஏற்ற முடியவில்லை',
  'deletePurchaseConfirmMsg': 'இந்த கொள்முதல் பட்டியலை நீக்க வேண்டுமா?',
  'purchaseDeletedToast': 'கொள்முதல் நீக்கப்பட்டது',
  'noPurchasesToExportToast': 'ஏற்றுமதி செய்ய எந்த கொள்முதலும் இல்லை',
  'purchasesCsvDownloadedToast': 'கொள்முதல் CSV பதிவிறக்கப்பட்டது',
  'supplierCol': 'சப்ளையர்',
  'gstinCol': 'GSTIN',
  'taxableCol': 'வரிக்குட்பட்டது',
  'recurringInvoicesSubtitle': 'நிலையான வணிகர்களுக்கான பட்டியல்களை தானியங்கியாக உருவாக்குங்கள்',
  'invoiceLimitDesc': 'அனைத்து வணிகர்களுக்கான மொத்தப் பட்டியல்கள்',
  'signing_out': 'வெளியேறுகிறது...',
  'signOutSuccess': 'வெற்றிகரமாக வெளியேற்றப்பட்டது',

  'newTemplateBtn': 'புதிய வார்ப்புரு',
  'dueForGeneration': 'உருவாக்கப்பட வேண்டியவை',
  'editTemplateTitle': 'வார்ப்புருவைத் திருத்து',
  'newRecurringInvoiceTitle': 'புதிய தொடர் பட்டியல்',
  'quickSelectClient': 'வணிகரைத் விரைவாகத் தேர்ந்தெடு',
  'frequencyLabel': 'நிகழ்வெண்',
  'nextDueDateLabel': 'அடுத்த நாள்',
  'invoiceTypeLabel': 'பட்டியல் வகை',
  'lineItemsTitle': 'பொருட்கள்',
  'recurringTemplatesTable': 'தொடர் வார்ப்புருக்கள்',
  'noRecurringYet': 'தொடர் பட்டியல்கள் இல்லை',
  'createTemplateBtn': 'புதிய வார்ப்புரு',
  'frequencyCol': 'நிகழ்வெண்',
  'nextDueCol': 'அடுத்த தேதி',
  'addAtLeastOneItemToast': 'விளக்கம் மற்றும் விலையுடன் குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
  'templateUpdatedToast': 'வார்ப்புரு புதுப்பிக்கப்பட்டது',
  'recurringCreatedToast': 'தொடர் பட்டியல் உருவாக்கப்பட்டது',
  'deleteTemplateConfirmMsg': 'இந்தத் தொடர் பட்டியல் வார்ப்புருவை நீக்க வேண்டுமா?',
  'pausedToast': 'இடைநிறுத்தப்பட்டது',
  'activatedToast': 'செயல்படுத்தப்பட்டது',
  'failedToGenerateToast': 'உருவாக்க முடியவில்லை:',
  'invoiceGeneratedFor': 'இவருக்காக பட்டியல் உருவாக்கப்பட்டது:',
  'freqWeekly': 'கிழமை',
  'freqMonthly': 'திங்கள்',
  'freqQuarterly': 'காலாண்டு',
  'freqYearly': 'ஆண்டு',
  'statusActive': 'செயலில்',
  'statusPaused': 'இடைநிறுத்தம்',
  'generateNowTooltip': 'இப்போதே உருவாக்கு',
  'pauseTooltip': 'இடைநிறுத்து',
  'activateTooltip': 'செயல்படுத்து',
  'reportsTitle': 'அறிக்கைகள்',
  'salesSummaryTitle': 'விற்பனை சுருக்கம்',
  'monthlySalesTitle': 'மாதாந்திர அறிக்கை',
  'reportsSubtitle': 'நிதி அறிக்கைகள் மற்றும் பெற வேண்டியவைகளின் பகுப்பாய்வு',
  'profitAndLossTab': 'வருவாய் & இழப்பு',
  'outstandingAndAgingTab': 'நிலுவையில் உள்ளவை & பழமை',
  'filterByLabel': 'வடிகட்டி',
  'fiscalYearLabel': 'பொருளாண்டு',
  'monthYearLabel': 'திங்கள் / ஆண்டு',
  'monthLabel': 'திங்கள்',
  'yearLabel': 'ஆண்டு',
  'currencyLabel': 'நாணயம்',
  'revenueExTax': 'வருவாய் (வரி தவிர்த்து)',
  'expensesExGst': 'செலவுகள் (GST தவிர்த்து)',
  'netProfitLabel': 'நிகர ஈட்டம்',
  'netLossLabel': 'நிகர இழப்பு',
  'marginLabel': 'ஈட்ட விகிதம்',
  'plStatementTitle': 'ஈட்ட இழப்பு அறிக்கை',
  'showingCurrencyInvoicesOnly': 'பட்டியல்களை மட்டுமே காட்டுகிறது',
  'totalRevenueLabel': 'மொத்த வருவாய்',
  'lessGstCollectedLabel': 'கழிக்க: வசூலிக்கப்பட்ட GST',
  'netRevenueLabel': 'நிகர வருவாய்',
  'totalExpensesLabel': 'மொத்த செலவுகள்',
  'lessGstOnExpensesLabel': 'கழிக்க: செலவுகள் மீதான GST (ITC)',
  'netExpensesLabel': 'நிகர செலவுகள்',
  'monthlyBreakdownTitle': 'திங்கள் அறிக்கை',
  'revenueCol': 'வருவாய்',
  'expensesCol': 'செலவுகள்',
  'profitLossCol': 'ஈட்டம்/இழப்பு',
  'totalOutstandingLabel': 'மொத்த நிலுவை',
  'current0to30d': 'நடப்பு (0-30 நாட்கள்)',
  'days31to60': '31-60 நாட்கள்',
  'days61to90': '61-90 நாட்கள்',
  'days90plus': '90+ நாட்கள்',
  'filterByClientName': 'வணிகர் பெயர் மூலம் வடிகட்டவும்...',
  'outstandingReceivablesTitle': 'நிலுவையில் உள்ள பெற வேண்டியவைகள்',
  'noOutstandingFound': 'நிலுவைகள் இல்லை',
  'dueDateCol': 'கெடு நாள்',
  'outstandingCol': 'நிலுவை',
  'daysOverdueCol': 'காலதாமதமான நாட்கள்',
  'currentStatus': 'நடப்பு',
  'january': 'ஜனவரி',
  'february': 'பிப்ரவரி',
  'march': 'மார்ச்',
  'april': 'ஏப்ரல்',
  'may': 'மே',
  'june': 'ஜூன்',
  'july': 'ஜூலை',
  'august': 'ஆகஸ்ட்',
  'september': 'செப்டம்பர்',
  'october': 'அக்டோபர்',
  'november': 'நவம்பர்',
  'december': 'டிசம்பர்',
  'gstReturnsTitle': 'GST அறிக்கைகள்',
  'gstReturnsSubtitle': 'GST அறிக்கைகள் மற்றும் தாக்கல் நிலையை நெறியுக',
  'monthlyTab': 'திங்கள் தோறும்',
  'quarterlyTab': 'காலாண்டு',
  'r1Pending': 'R1 நிலுவை',
  'b3Pending': '3B நிலுவை',
  'gstPortalBtn': 'GST தளம்',
  'gstinNotSet': 'GSTIN அமைக்கப்படவில்லை. அமைப்புகளில் சேர்க்கவும்.',
  'invoicesCountLabel': 'பட்டியல்கள்',
  'taxableLabel': 'வரிக்குட்பட்டது',
  'taxLabel': 'வரி',
  'netPayableLabel': 'நிகர செலுத்த வேண்டியவை',
  'gstr1Tab': 'GSTR-1',
  'gstr3bTab': 'GSTR-3B',
  'gstr2bReconTab': 'GSTR-2B ஒப்பீடு',
  'tdsTcsTab': 'TDS / TCS அறிக்கை',
  'filingGuideTab': 'தாக்கல் வழிகாட்டி',
  'jsonExportBtn': 'JSON ஏற்றுமதி',
  'docsBtn': 'ஆவணங்கள்',
  'markFiledBtn': 'தாக்கல் செய்யப்பட்டதாகக் குறி',
  'b2bSalesTable': 'B2B விற்பனை',
  'b2cSalesTable': 'B2C விற்பனை',
  'hsnSummaryTable': 'HSN சுருக்கம்',
  'docSummaryTable': 'ஆவண சுருக்கம்',
  'gstr1SummaryTotals': 'GSTR-1 சுருக்க மொத்தங்கள்',
  'noB2bInvoices': 'B2B பட்டியல்கள் இல்லை',
  'noB2cInvoices': 'B2C பட்டியல்கள் இல்லை',
  'cgstCol': 'CGST',
  'sgstCol': 'SGST',
  'igstCol': 'IGST',
  'totalCol': 'மொத்தம்',
  'b2cTotal': 'B2C மொத்தம்',
  'totalTaxCol': 'மொத்த வரி',
  'docTypeCol': 'ஆவண வகை',
  'fromCol': 'இருந்து',
  'toCol': 'வரை',
  'totalIssuedCol': 'மொத்தம் வழங்கப்பட்டது',
  'categoryCol': 'வகை',
  'grandTotal': 'பெரு மொத்தம்',
  'b2bSalesCategory': 'B2B விற்பனை',
  'b2cSalesCategory': 'B2C விற்பனை',
  'invoiceWord': 'பட்டியல்',
  'invoicesWord': 'பட்டியல்கள்',
  'codeWord': 'குறியீடு',
  'codesWord': 'குறியீடுகள்',
  'notificationsTitle': 'அறிவிப்புகள்',
  'allClearNotif': 'எல்லாம் சரி ✨',
  'recurringAutoFireNotif': 'இன்று தானியங்கியாக உருவாக்கப்பட்ட தொடர் பட்டியல்கள்',
  'checkDashboardForNewBills': 'பட்டியல்களுக்கு முகப்பைப் பார்க்கவும்',
  'overdueInvoicesNotif': 'காலதாமதமான பட்டியல்கள்',
  'moreWord': 'மேலும்',
  'dueIn3DaysNotif': 'அடுத்த 3 நாட்களில் கெடு நாள் கொண்ட பட்டியல்கள்',
  'gstFilingsDueNotif': 'அடுத்த 10 நாட்களில் GST தாக்கல் நிலுவையில் உள்ளன',
  'todayWord': 'இன்று',
  'lowStockNotif': 'இருப்பு குறைவாக உள்ள பொருட்கள்',
  'leftWord': 'மீதம்',
  'duplicateProductsTitle': 'பொருட்களை நகலெடுக்கவா?',
  'duplicateProductsMessage': 'தேர்ந்தெடுக்கப்பட்ட பொருட்களை நகலெடுக்க விரும்புகிறீர்களா?',
  'saveDuplicate': 'நகலெடு',
  'productsDuplicatedSuccess': 'பொருட்கள் வெற்றிகரமாக நகலெடுக்கப்பட்டன',
  'errorDuplicating': 'நகலெடுப்பதில் பிழை',
  'deleteProductsTitle': 'பொருட்களை நீக்கவா?',
  'deleteProductsMessage': 'தேர்ந்தெடுக்கப்பட்ட பொருட்களை நீக்க விரும்புகிறீர்களா? இதை மாற்ற முடியாது.',
  'deletedSuccessfully': 'வெற்றிகரமாக நீக்கப்பட்டது',
  'errorDeleting': 'நீக்குவதில் பிழை',
  'hc_100Safe': '100% பாதுகாப்பானது',
  'hc_orStartManually': 'அல்லது நீங்களே தொடங்கலாம்:',
  'hc_1Doubleclick': '1. இருமுறை சொடுக்கவும்',
  'hc_onYourDesktop': 'திரையகத்தில்',
  'hc_2OrSearch': '2. அல்லது தேடுங்கள்',
  'hc_inStartMenu': 'தொடக்கப் பட்டியலில்',
  'hc_startingThisPageWillOpen': 'தொடங்குகிறது... இந்தப் பக்கம் தானாகவே திறக்கப்படும்.',
  'hc_typeACommandOrPage': 'கட்டளை அல்லது பக்கப் பெயரை உள்ளிடுக…',
  'hc_yourDataIsSafe': 'உங்கள் தரவு பாதுகாப்பானது.',
  'hc_updatesOnlyRefreshTheApp': 'புதுப்பிப்புகள் செயலி நிரலை மட்டுமே புதுப்பிக்கும் — உங்கள்',
  'hc_pdfArchiveAre': 'PDF காப்பகங்கள்',
  'hc_neverTouched': 'மாற்றப்படாது',
  'hc_githubReleases': 'GitHub வெளியீடுகள்',
  'hc_recommended': 'பரிந்துரைக்கப்படுவது:',
  'hc_exportBackup': 'காப்புநகலை ஏற்றுமதி செய்…',
  'hc_skipThisVersion': 'இந்தப் பதிப்பைத் தவிர்',
  'hc_viewOnGithub': 'GitHub-இல் காண்',
  'hc_updateNow': 'இப்போதே புதுப்பி',
  'hc_launches': 'தொடங்குகிறது',
  'hc_devSwitchBilingualLanguage': 'DEV: இருமொழி நிலை மாற்று',
  'hc_devLanguageSwitcher': 'DEV: மொழி மாற்றி',
  'hc_primaryLanguage': 'முதன்மை மொழி',
  'hc_secondaryLanguage': 'இரண்டாம் நிலை மொழி',
  'hc_active': 'செயலில்',
  'hc_yourExistingBankDetailsAre': 'உங்கள் தற்போதைய வங்கி தரவுகள் இந்தத் தன்னுருவில் உள்ளன.',
  'hc_clickBelowToImportThem': 'அவற்றை முதல் கட்டணக் கணக்காக இறக்குமதி செய்யக் கீழே சொடுக்கவும், பின்னர் மேலும் சேர்க்கவும்.',
  'hc_defaultAccount': 'இயல்புநிலைக் கணக்கு',
  'hc_inactive': 'செயலற்றது',
  'hc_setAsDefault': 'இயல்புநிலையாக அமை',
  'hc_moveUp': 'மேலே நகர்த்து',
  'hc_moveDown': 'கீழே நகர்த்து',
  'hc_egAaaaa1234a': 'எ.கா. AAAAA1234A',
  'hc_egHdfcCurrent1234': 'எ.கா. HDFC Current — 1234',
  'hc_bankName': 'வங்கியின் பெயர்',
  'hc_egHdfcinbb': 'எ.கா. HDFCINBB',
  'hc_egYourbusinesshdfcbank': 'எ.கா. yourbusiness@hdfcbank',
  'hc_egUseForExportClients': 'எ.கா. ஏற்றுமதி வாடிக்கையாளர்களுக்கு மட்டும்',
  'hc_setAsDefaultAccount': '⭐ இயல்புநிலைக் கணக்காக அமை',
  'hc_preview': 'முன்னோட்டம்:',
  'hc_formatStyle': 'வடிவமைப்பு முறை',
  'hc_brandPrefix': 'முன்னொட்டு',
  'hc_egAcmeBk': 'எ.கா. ACME, BK',
  'hc_separator': 'பிரிப்பான்',
  'hc_prefix': 'முன்னொட்டு',
  'hc_egRcpR': 'எ.கா. RCP, R',
  'hc_googleOauthClientId': 'Google OAuth Client ID',
  'hc_openGoogleCloudConsole': 'Google Cloud Console-ஐத் திற',
  'hc_driveFolderName': 'Drive கோப்புறையின் பெயர்',
  'hc_status': 'நிலை',
  'hc_yourDataWillNotBe': 'உங்கள் தரவு பாதிக்கப்படாது. புதுப்பிக்கக் கீழே சொடுக்கவும்:',
  'hc_preferences': 'விருப்பங்கள்',
  'hc_uiLanguageDataLanguages': 'பயனர் இடைமுக மொழி, தரவு மொழிகள்',
  'hc_accountsInvoiceFormatsTerms': 'கணக்குகள், பட்டியல் வடிவங்கள், விதிமுறைகள்',
  'hc_advanced': 'மேம்பட்டவை',
  'hc_appVersionsCache': 'செயலி பதிப்புகள், தற்காலிக சேமிப்பு',
  'hc_selectASetting': 'அமைப்பைத் தேர்ந்தெடுக்கவும்',
  'hc_exportBackup1': 'காப்புநகலை ஏற்றுமதி செய்',
  'hc_downloadBackup': 'காப்புநகலைப் பதிவிறக்கு',
  'hc_restoreFromBackup': 'காப்புநகலிலிருந்து மீட்டமை',
  'hc_overwriteMatchingRecordsById': 'பொருந்தும் தரவுகளை மேலெழுது',
  'hc_welcomeToElvanNiril': 'Elvan Niril-க்கு நல்வரவு',
  'hc_businessDetails': 'வணிக தரவுகள்',
  'hc_businessName': 'வணிகத்தின் பெயர்',
  'hc_egSharmaConsultantsPvtLtd': 'எ.கா. Sharma Consultants Pvt. Ltd.',
  'hc_eg42MgRoadSector': 'எ.கா. 42, MG Road, Sector 15, Gurugram 122001',
  'hc_neededForAutoCgstsgstVs': 'தானியங்கி CGST/SGST மற்றும் IGST-க்குத் தேவை',
  'hc_phoneMobile': 'தொலைபேசி / அலைபேசி',
  'hc_egHdfcBank': 'எ.கா. HDFC Bank',
  'hc_accountNumber': 'கணக்கு எண்',
  'hc_eg12345678901234': 'எ.கா. 12345678901234',
  'hc_ifscCode': 'IFSC குறியீடு',
  'hc_egHdfc0001234': 'எ.கா. HDFC0001234',
  'hc_upiId': 'UPI எண்',
  'hc_egBusinessupi': 'எ.கா. business@upi',
  'hc_businessLogo': 'வணிகத்தின் இலச்சினை',
  'hc_pngjpgMax500kb': 'PNG/JPG, அதிகபட்சம் 500KB',
  'hc_digitalSignature': 'இலக்கமுறை கையொப்பம்',
  'hc_youreAllSet': 'எல்லாம் தயார்!',
  'hc_openSidebar': 'பக்கவாட்டுப் பட்டையைத் திற',
  'hc_closeSidebar': 'பக்கவாட்டுப் பட்டையை மூடு',
  'emptyKey': 'பண ரசீது',
  'hc_paymentReceipt': 'பண ரசீது',
  'hc_egAcmeCorp': 'எ.கா. Acme Corp',
  'hc_addressInEnglish': 'ஆங்கிலத்தில் முகவரி',
  'hc_cityInEnglish': 'ஆங்கிலத்தில் நகரம்',
  'hc_countryInEnglish': 'ஆங்கிலத்தில் நாடு',
  'hc_taxDataExport': 'வரித் தரவு ஏற்றுமதி',
  'hc_fullYear': 'முழு ஆண்டு',
  'hc_totalInvoices': 'மொத்தப் பட்டியல்கள்',
  'hc_taxCollected': 'வசூலிக்கப்பட்ட வரி',
  'hc_netPayable': 'செலுத்த வேண்டிய நிகரத் தொகை',
  'hc_invoicesForThisPeriod': 'இந்தக் காலத்திற்கான பட்டியல்கள்',
  'hc_noInvoicesFoundForThis': 'இந்தக் காலத்திற்குப் பட்டியல்கள் ஏதுமில்லை.',
  'hc_invoiceNo': 'பட்டியல் எண்',
  'hc_client': 'வாடிக்கையாளர்',
  'hc_taxableValue': 'வரிக்குரிய மதிப்பு',
  'hc_taxAmount': 'வரித் தொகை',
  'hc_type': 'வகை',
  'hc_b2bTotal': 'மொத்த B2B',
  'hc_creditdebitNotesTable9b': 'வரவு/பற்று குறிப்புகள் — அட்டவணை 9B',
  'hc_noteNo': 'குறிப்பு எண்',
  'hc_noItemsFound': 'பொருட்கள் ஏதுமில்லை.',
  'hc_noDocumentsIssued': 'ஆவணங்கள் வழங்கப்படவில்லை.',
  'hc_natureOfSupplies': 'வழங்கலின் தன்மை',
  'hc_na': 'பொருந்தாது',
  'hc_table32IntermaanilamSuppliesTo': 'அட்டவணை 3.2 — பதிவு செய்யப்படாதவர்களுக்கான மாநிலங்களுக்கு இடையிலான வழங்கல்',
  'hc_placeOfSupply': 'வழங்கல் இடம்',
  'hc_details': 'தரவுகள்',
  'hc_netItcAvailable': 'கிடைக்கக்கூடிய நிகர ITC',
  'hc_table6TaxPaymentSummary': 'அட்டவணை 6 — வரி செலுத்தும் சுருக்கம்',
  'hc_outputTaxLiability': 'செலுத்த வேண்டிய வெளிப்பாட்டு வரி',
  'hc_lessItcClaimed': 'கழிக்க: கோரப்பட்ட ITC',
  'hc_netTaxPayable': 'செலுத்த வேண்டிய நிகர வரி',
  'hc_netGstPayable': 'செலுத்த வேண்டிய நிகர GST',
  'hc_howToUse': 'எப்படிப் பயன்படுத்துவது:',
  'hc_import2bJson': '2B JSON-ஐ இறக்குமதி செய்',
  'hc_purchaseBills': 'கொள்முதல் பட்டியல்கள்',
  'hc_importYourGstr2bJsonTo': 'உங்கள் கொள்முதல் தரவுகளுடன் ஒப்பிட உங்கள் GSTR-2B JSON-ஐ இறக்குமதி செய்யவும்.',
  'hc_supplier': 'வழங்குபவர்',
  'hc_invoiceNo1': 'பட்டியல் எண்.',
  'hc_2bValue': '2B மதிப்பு',
  'hc_booksValue': 'கணக்கு மதிப்பு',
  'hc_diff': 'வித்தியாசம்',
  'hc_noEntriesMatchThisFilter': 'இந்த வடிகட்டிக்குப் பொருத்தமான பதிவுகள் ஏதுமில்லை.',
  'hc_whatThisIs': 'இது என்ன:',
  'hc_form26q': 'படிவம் 26Q',
  'hc_form27eq': 'படிவம் 27EQ',
  'hc_invoicesWithTds': 'TDS உள்ள பட்டியல்கள்',
  'hc_totalTdsReceivable': 'பெற வேண்டிய மொத்த TDS',
  'hc_quarter': 'காலாண்டு',
  'hc_section': 'பிரிவு',
  'hc_customizeTds': 'தனிப்பயனாக்கு → TDS',
  'hc_invoicesWithTcs': 'TCS உள்ள பட்டியல்கள்',
  'hc_totalTcsCollected': 'வசூலிக்கப்பட்ட மொத்த TCS',
  'hc_customizeTcs': 'தனிப்பயனாக்கு → TCS',
  'hc_steps': 'படிகள்:',
  'hc_dueR1By11th3b': '| கெடு: R1 11ஆம் தேதிக்குள், 3B அடுத்த மாதம் 20ஆம் தேதிக்குள் | தாமதக் கட்டணம்: நாள் ஒன்றுக்கு ₹50',
  'hc_gstr1ProTips': 'GSTR-1 சிறப்பு வழிகாட்டுதல்கள்',
  'hc_fastestMethod': 'விரைவான முறை:',
  'hc_exportGstr1JsonFromThe': 'மேலேயுள்ள GSTR-1 பட்டியில் இருந்து GSTR-1 JSON-ஐ ஏற்றுமதி செய் → GST இணையதளத்திற்குச் செல் → GSTR-1 → இணையத்தொடர்பின்றி தயார் செய் → ஆஃப்லைன் கருவியைப் பதிவிறக்கு → JSON-ஐ இறக்குமதி செய் → பதிவேற்று. 90% நேரத்தைச் சேமிக்கிறது.',
  'hc_gstr3bProTips': 'GSTR-3B சிறப்பு வழிகாட்டுதல்கள்',
  'hc_fromJuly2025': 'ஜூலை 2025 முதல்:',
  'hc_table3AutopopulatesFromGstr1': 'அட்டவணை 3 GSTR-1 இலிருந்து தானாகவே நிரப்பப்படும் — சரிபார்க்கவும், மதிப்புகளை மீண்டும் உள்ளிட வேண்டாம்.',
  'hc_itcMatching': 'ITC பொருத்துதல்:',
  'hc_alwaysCheckGstr2bStatementBefore': 'ITC-ஐக் கோருவதற்கு முன் எப்போதும் GSTR-2B அறிக்கையைச் சரிபார்க்கவும். படிவங்கள் → GSTR-2B → பதிவிறக்கு. GSTR-2B-இல் தோன்றும் ITC-ஐ மட்டுமே கோரவும்.',
  'hc_payment': 'பணம் செலுத்துதல்:',
  'hc_interestCalculation': 'வட்டி கணக்கீடு:',
  'hc_reverseCharge': 'எதிர்மறை வரி:',
  'hc_whenToFileNilReturn': 'NIL படிவத்தை எப்போது தாக்கல் செய்ய வேண்டும்',
  'hc_youHad': 'உங்களிடம்',
  'hc_zeroOutwardSupplies': 'வெளியேறும் வழங்கல்கள் ஏதுமில்லை',
  'hc_youHave': 'உங்களுக்கு',
  'hc_noInputTaxCredit': 'உள்ளீட்டு வரிக்கடன் ஏதுமில்லை',
  'hc_toClaim': 'கோருவதற்கு',
  'hc_noTaxLiability': 'வரிப் பொறுப்பு ஏதுமில்லை',
  'hc_noInwardSupplies': 'உள்ளே வரும் வழங்கல்கள் ஏதுமில்லை',
  'hc_liableToReverseCharge': 'எதிர்மறை வரிக்கு உட்பட்டது',
  'hc_ifAnyOfTheAbove': 'மேற்கூறியவற்றில் ஏதேனும் மதிப்பு இருந்தால், நீங்கள் வழக்கமான படிவத்தைத்தான் தாக்கல் செய்ய வேண்டும் — NIL அல்ல',
  'hc_nilGstr3bFileAfterNil': 'NIL GSTR-3B — NIL GSTR-1-க்குப் பிறகு தாக்கல் செய்யவும்',
  'hc_nilReturnQuickSummary': 'NIL படிவம் விரைவான சுருக்கம்',
  'hc_nilGstr1AndNilGstr3b': 'NIL GSTR-1 மற்றும் NIL GSTR-3B ஆகியவை',
  'hc_separateReturns': 'தனித்தனிப் படிவங்கள்',
  'hc_fileBoth': '— இரண்டையும் தாக்கல் செய்யவும்',
  'hc_nilFilingTakes23Minutes': 'NIL தாக்கல் செய்யப் படிவம் ஒன்றுக்கு 2-3 நிமிடங்கள் ஆகும் — உள்நுழையவும், பூஜ்ஜியங்களைச் சரிபார்க்கவும், சமர்ப்பிக்கவும், தாக்கல் செய்யவும்',
  'hc_youCanFileNilReturns': 'குறுஞ்செய்தி மூலமாகவும் NIL படிவங்களைத் தாக்கல் செய்யலாம்: அனுப்புக',
  'hc_nilSpaceGstinSpaceReturn': 'NIL இடைவெளி GSTIN இடைவெளி படிவக் காலம்',
  'hc_to14409VerifyWithOtp': '14409 என்ற எண்ணிற்கு. OTP-ஐக் கொண்டு சரிபார்க்கவும்.',
  'hc_qrmpUsersFilingQuarterlyNil': 'காலாண்டுக்கு ஒருமுறை தாக்கல் செய்யும் QRMP பயனர்கள்: NIL படிவம் முழு காலாண்டையும் உள்ளடக்கும்',
  'hc_keyGstRulesToRemember': 'நினைவில் கொள்ள வேண்டிய முக்கிய GST விதிகள்',
  'hc_itcForAnyInvoiceMust': 'எந்தவொரு பட்டியலுக்கான ITC-யும் அடுத்த நிதியாண்டின் செப்டம்பர் மாதப் படிவத்தின் கெடு தேதிக்குள் அல்லது ஆண்டுப் படிவம் தாக்கல் செய்யும் தேதிக்குள் — இதில் எது முந்தியதோ அதற்குள் கோரப்பட வேண்டும்.',
  'hc_section34': 'பிரிவு 34:',
  'hc_creditNotesMustBeIssued': 'அசல் பட்டியலின் நிதியாண்டு முடிந்த செப்டம்பர் 30-க்கு முன் அல்லது ஆண்டுப் படிவம் தாக்கல் செய்வதற்கு முன் — இதில் எது முந்தியதோ அதற்குள் வரவுக் குறிப்புகள் வழங்கப்பட வேண்டும்.',
  'hc_section31': 'பிரிவு 31:',
  'hc_taxInvoiceMustBeIssued': 'வழங்கும் நேரத்திலோ அல்லது அதற்கு முன்போ வரிப் பட்டியல் வழங்கப்பட வேண்டும். சேவைகளுக்கு, வழங்கிய 30 நாட்களுக்குள்.',
  'hc_section49': 'பிரிவு 49:',
  'hc_itcCanOnlyBeClaimed': 'GSTR-2B-இல் தோன்றும் பட்டியல்களுக்கு மட்டுமே ITC கோர முடியும். GSTR-2B-க்கு அப்பால் தற்காலிக ITC இல்லை.',
  'hc_section50': 'பிரிவு 50:',
  'hc_section7374': 'பிரிவு 73/74:',
  'hc_ewayBill': 'மின்னணு வழி ரசீது:',
  'hc_cannotGenerateEwayBillsIf': 'தொடர்ந்து 2+ மாதங்களுக்கு GSTR-3B தாக்கல் செய்யப்படாவிட்டால் மின்னணு வழி ரசீதுகளை உருவாக்க முடியாது.',
  'hc_bulletList': 'புள்ளிப் பட்டியல்',
  'hc_numberedList': 'எண் பட்டியல்',
  'hc_heading': 'தலைப்பு',
  'hc_paragraph': 'பத்தி',
  'hc_insertLink': 'இணைப்பைச் செருகு',
  'hc_clearFormatting': 'வடிவமைப்பை அகற்று',
  'hc_allChangesSaved': 'மாற்றங்கள் சேமிக்கப்பட்டன',
  'hc_addAClientNameAnd': 'சேமிக்க ஒரு வாடிக்கையாளர் பெயரையும் குறைந்தது ஒரு பொருளையாவது சேர்க்கவும்',
  'hc_sacCode': 'SAC குறியீடு',
  'hc_invoiceTitle': 'பட்டியலின் தலைப்பு',
  'hc_currency': 'நாணயம்',
  'hc_paymentAccountOnThisInvoice': 'இப்பட்டியலுக்கான கட்டணக் கணக்கு',
  'hc_pdfStyle': 'PDF வடிவமைப்பு',
  'hc_accentColor': 'முதன்மையான நிறம்',
  'hc_hideAll': 'அனைத்தையும் மறை',
  'hc_savedCustomer': 'சேமிக்கப்பட்ட வாடிக்கையாளர்',
  'hc_tempCustomer': 'தற்காலிக வாடிக்கையாளர்',
  'hc_savedClientDetails': 'சேமிக்கப்பட்ட வாடிக்கையாளர் தரவுகள்',
  'hc_maanilamRegion': 'மாநிலம் / பகுதி',
  'hc_originalInvoiceReference': 'அசல் பட்டியலின் குறிப்பு',
  'hc_egInv2025260001': 'எ.கா. INV/2025-26/0001',
  'hc_savedItem': 'சேமிக்கப்பட்ட பொருள்',
  'hc_tempItem': 'தற்காலிகப் பொருள்',
  'hc_searchSavedItems': 'சேமிக்கப்பட்ட பொருள்களைத் தேடு...',
  'hc_savedItemDetails': 'சேமிக்கப்பட்ட பொருளின் தரவுகள்',
  'hc_hsnsac': 'HSN/SAC:',
  'hc_unit': 'அலகு:',
  'hc_tax': 'வரி:',
  'hc_cess': 'Cess:',
  'hc_addCustom': '＋ புதிதாகச் சேர்…',
  'hc_remove': 'நீக்கு',
  'hc_saveChangesBeforeClosing': 'மூடுவதற்கு முன் மாற்றங்களைச் சேமிக்கவா?',
  'hc_forEstimationPurposesOnly': 'மதிப்பீட்டு நோக்கங்களுக்காக மட்டும்',
  'hc_against': 'இதற்கு எதிராக:',
  'hc_thisIsNotATax': 'இது ஒரு வரிப் பட்டியல் அல்ல. மதிப்பீட்டு நோக்கங்களுக்காக மட்டும்.',
  'hc_againstInvoice': 'பட்டியலுக்கு எதிராக:',
  'hc_disc': 'தள்ளுபடி',
  'hc_subtotal': 'உப மொத்தம்',
  'hc_gstCess': 'GST Cess',
  'hc_roundoff': 'முழுமையாக்குதல்',
  'hc_netReceivable': 'பெற வேண்டிய நிகரத் தொகை',
  'hc_reverseChargeApplicable': 'எதிர்மறை வரி பொருந்தும்.',
  'hc_exchangeRate': 'பரிமாற்ற விகிதம்',
  'hc_discardChanges': 'மாற்றங்களை நிராகரி',
  'hc_discardWarning': 'நீங்கள் சேமிக்காத மாற்றங்களை உறுதியாக நிராகரிக்க வேண்டுமா?',
  'hc_cancel': 'கைவிடு',
  'hc_discard': 'நிராகரி',
  'receiptDetails': 'ரசீது தரவுகள்',
  'invoiceData': 'பட்டியல் தரவுகள்',
  'receiptData': 'பற்றுச்சீட்டு தரவுகள்',
  'invoicesSelected': 'பட்டியல்(கள்) தேர்ந்தெடுக்கப்பட்டன',
  'paymentDetails': 'கட்டண தரவுகள்',
  'productDetails': 'பொருள் தரவுகள்',
  'pricingAndTax': 'விலை மற்றும் வரி',
  'clientDetails': 'வணிகர் தரவுகள்',
  'addressDetails': 'முகவரி தரவுகள்',
  'contactAndTaxDetails': 'தொடர்பு மற்றும் வரி தரவுகள்',
  'hc_addNewProduct': 'புதிய பொருளைச் சேர்',
  'hc_addNewClient': 'புதிய வணிகரைச் சேர்',
  'deleteInvoiceConfirmMsg': 'இந்தத் பட்டியலை நீக்க வேண்டுமா?',
  'notesAndTerms': 'குறிப்புகள் / வரையறைகள்',
  'customer': 'வாடிக்கையாளர்',
  'company': 'நிறுவனம்',
  'quantity': 'அளவு',
  'addOtherCharges': 'கூடுதல் கட்டணம் சேர்',
  'chargeName': 'கட்டணத்தின் பெயர்',
  'otherCharges': 'கூடுதல் கட்டணங்கள்',
  'setharam': 'சேதாரம்',
  'ahimsaSilk': 'அகிம்சா பட்டு',
  'courier': 'கொரியர்',
  'totalWeight': 'மொத்த எடை',
  'grams': 'கிராம்',
  'searchBillsPlaceholder': 'தேடுக...',
  'saveBtn': 'சேமி',
  'detailsSaved': 'தரவுகள் வெற்றிகரமாக சேமிக்கப்பட்டன',
  'bankNameTamil': 'வங்கி பெயர் (தமிழ்)',
  'bankNameEnglish': 'வங்கி பெயர் (ஆங்கிலம்)',
  'branchNameTamil': 'கிளை பெயர் (தமிழ்)',
  'branchNameEnglish': 'கிளை பெயர் (ஆங்கிலம்)',
  'manage': 'நெறி',
  'addNew': 'புதிய',
  'shortBusinessNameLabel': 'குறுகிய வணிக பெயர் (பில் எண்ணுக்கு)',
  'shortBusinessNameHelper': 'இது தானியங்கி பில் எண்ணில் முன்னொட்டாக பயன்படுத்தப்படும்.',
  'authorizedSignatoryName': 'அங்கீகரிக்கப்பட்ட கையொப்பத்தின் பெயர்',
  'profileSaved': 'தன்னுரு சேமிக்கப்பட்டது!',
  'unsavedChangesWarning': 'சேமிக்கப்படாத மாற்றங்கள் உள்ளன. தொடரவா?',
  'unsavedChanges': 'சேமிக்கப்படாத மாற்றங்கள்',
  'discardBtn': 'நிராகரி',
  'savingStatus': 'சேமிக்கிறது...',
  'createNewProfile': 'புதிய தன்னுருவை உருவாக்கு',
  'businessNameAsterisk': 'நிறுவனத்தின் பெயர் *',
  'addressLabel': 'முகவரி',
  'manageBusinessProfiles': 'வணிக தன்னுருக்களை நெறி',
  'vaniga_nirvagam': 'நெறியுக',
  'noSavedProfiles': 'தன்னுருக்கள் இல்லை',
  'confirmDeleteTitle': 'உறுதிப்படுத்தவும்',
  'english1': 'தமிழ்',
  'all': 'யாவை',
  'measureType': 'அளவீடு முறை',
  'invoiceCount': 'பட்டியல் எண்ணிக்கை',
  'selectYourOperatingMode': 'உங்கள் கணக்குப் பகுதியைத் தேர்ந்தெடுக்கவும்',
  'languageSettingsSaved': 'அமைப்புகள் சேமிக்கப்பட்டன',
  'usedAsTheDefaultPrefixForYourI': 'இது தானியங்கி பில் எண்ணில் முன்னொட்டாக பயன்படுத்தப்படும் (உதாரணமாக SJS/2026-27/0001).',
  'addAlternateMobile': 'மாற்று கைபேசி எண் சேர்க்க',
  'changeTheLanguageOfTheApplicat': 'பயன்பாட்டின் மொழியை மாற்றவும்.',
  'appUserName': 'பயனர் பெயர் (பயன்பாடு)',
  'thisNameWillAppearOnTheAppHome': 'இந்த பெயர் பயன்பாட்டின் முகப்புத்திரையில் தோன்றும்.',
  'userName': 'பயனர் பெயர்',
  'allowDataEntryInTwoLanguages': 'இரு மொழிகளிலும் தரவை உள்ளிட அனுமதிக்கவும்',
  'bankDetailsShownOnYourInvoices': 'பில்களில் காட்டப்படும் வங்கி தரவுகள்.',
  'accountNumber': 'கணக்கு எண்',
  'uPIIDOptional': 'UPI ID (விருப்பம்)',
  'totals': 'மொத்தம்',
  'subtotal': 'உபமொத்தம்',
  'totalDiscountAmt': 'மொத்த தள்ளுபடி தொகை',
  'roundOff': 'முழுமைப்படுத்து',
  'noInvoicesFound': 'பட்டியல்கள் கிடைக்கவில்லை',
  'featureNotSupported': 'அம்சம் ஆதரிக்கப்படவில்லை',
  'errorLoadingCustomers': 'வாடிக்கையாளர்களை ஏற்றுவதில் பிழை',
  'addressTamil': 'முகவரி (தமிழ்)',
  'addressEnglish': 'முகவரி (English)',
  'organizationLogo': 'நிறுவனத்தின் சின்னம்',
  'upcomingFeature': 'விரைவில் வரவுள்ளது',
  'cityTamil': 'ஊர் (தமிழ்)',
  'cityEnglish': 'ஊர் (English)',
  'districtTamil': 'மாவட்டம் (தமிழ்)',
  'districtEnglish': 'மாவட்டம் (English)',
  'cityLabel': 'ஊர்',
  'districtLabel': 'மாவட்டம்',
  'pincode': 'அஞ்சல் குறியீடு',
  'branchTamil': 'கிளை (தமிழ்)',
  'branchEnglish': 'கிளை (ஆங்கிலம்)',
  'appearanceDescription': 'பில்லின் நிறம் மற்றும் அச்சிடும் மொழிகளை அமைக்கவும்.',
  'billTheme': 'பில் தீம் (நிறம்)',
  'pachai': 'பச்சை',
  'uudha': 'ஊதா',
  'cooliePdfTheme': 'PDF வண்ணம்',
  'defaultPrintLanguage': 'பில் மற்றும் ரசீது மொழி',
  'cooliePrintLanguage': 'பட்டியல் & பற்றுச்சீட்டு மொழி',
  'receiptLanguage': 'ரசீது அச்சிடும் மொழி',
  'accountSecurityTitle': 'கணக்கு பாதுகாப்பு',
  'accountSecurityDesc': 'பயன்பாட்டு அணுகலைப் பூட்டவும்.',
  'signOutBtn': 'வெளியேறு',
  'eraseAppDataTitle': 'செயலித் தரவை அழி',
  'eraseAppDataDesc': 'தரவுகளை நிரந்தரமாக அழிக்கவும்.',
  'eraseDataBtn': 'தரவை அழி',
  'systemAndSecurity': 'அமைப்பு & பாதுகாப்பு',
  'systemSecurityDesc': 'கணக்கு பாதுகாப்பு மற்றும் செயலித் தரவை நெறியுக.',
  'clearCacheTitle': 'தேக்கத்தை அழி',
  'clearCacheDesc': 'தேக்கத்தை அழித்து பிழைகளை சரிசெய்யவும்.',
  'clearCacheBtn': 'தேக்கத்தை அழி',
  'clearCacheConfirmDesc': 'பயன்பாடு மீண்டும் ஏற்றப்படும். மீண்டும் உள்நுழைய நேரிடலாம்.',
  'signOutConfirmTitle': 'வெளியேற வேண்டுமா?',
  'signOutConfirmDesc': 'தரவை மீண்டும் அணுக உங்கள் கடவுச்சொல் தேவைப்படும்.',
  'eraseConfirmDesc': 'மேகக்கணி தரவுகள் நிரந்தரமாக அழிக்கப்படும். இதை செயல்தவிர்க்க முடியாது.',
  'confirmEmailLabel': 'மின்னஞ்சலை உறுதிசெய்க',
  'incorrectEmail': 'மின்னஞ்சல் பொருந்தவில்லை.',
  'confirmPassword': 'உறுதிசெய்க',
  'password': 'கடவுச்சொல்',
  'erasing': 'அழிக்கிறது...',
  'enterPassword': 'கடவுச்சொல்லை உள்ளிடவும்',
  'dataErasedSuccess': 'தரவு வெற்றிகரமாக அழிக்கப்பட்டது.',
  'incorrectPassword': 'தவறான கடவுச்சொல்.',
  'tooManyRequests': 'அதிக முயற்சிகள். பிறகு முயற்சிக்கவும்.',
  'errorOccurred': 'தரவை அழிப்பதில் பிழை.',
  'vanakkamTitle': 'வணக்கம்!',
  'whoIsWorkingToday': 'இன்று எந்தக் கணக்கு?',
  'welcomeTitle': 'நிறிளிற்கு நல்வரவு',
  'welcomeSubtitle': 'உங்கள் பட்டியல்கள் & GST, எளிதாக்கப்பட்டது.',
  'welcomeAgreeText': 'நிறிளை தொடங்க கீழ் உள்ள பொத்தானை தட்டவும்',
  'agreeAndContinueBtn': 'தொடங்குக',
  'nirilBrand': 'நிறிள்',
  'loginSubtitle': 'செயலியை அணுக உள்நுழையவும்',
  'emailAddress': 'மின்னஞ்சல் முகவரி',
  'enterEmail': 'மின்னஞ்சலை உள்ளிடவும்',
  'signIn': 'உள்நுழைக',
  'pleaseFillAllFields': 'அனைத்து விவரங்களையும் உள்ளிடவும்.',
  'selectLanguageTitle': 'மொழியைத் தேர்ந்தெடு',
  'selectLanguageSubtitle': 'விருப்பமான மொழியை தேர்வு செய்',
  'savedSuccessfully': 'வெற்றிகரமாகச் சேமிக்கப்பட்டது',
  'hc_alsoSaveACopyTo': 'ஒரு நகலை எனது கூகுள் டிரைவிலும் சேமிக்கவும்',
  'vanigam': 'வணிகம்',
  'vaniga_amaippugal': 'வணிக அமைப்புகள்',
  'settings_mugavari': 'முகவரி',
  'vangi': 'வங்கி',
  'uruvakku_amaippugal': 'உருவாக்கு அமைப்புகள்',
  'seyali_amaippugal': 'செயலி அமைப்புகள்',
  'pathugappu_amaippugal': 'பாதுகாப்பு அமைப்புகள்',

  'thirai': 'திரை',
  'pathugappu': 'பாதுகாப்பு',
  'menporul_vadivalar': 'மென்பொருள் வடிவாளர்',
  'adaiyalam': 'அடையாளம்',
  'desc_business_profile': 'வணிக தன்னுரு முறை',
  'desc_coolie_identifiers': 'கூலி வணிக அடையாளங்கள்',
  'desc_silk_identifiers': 'பட்டு வணிக அடையாளங்கள்',
  'desc_address': 'நிறுவன முகவரி தரவுகள்',
  'desc_bank': 'கணக்கு எண் & IFSC',
  'desc_invoice': 'பில் வடிவமைப்பு விருப்பங்கள்',
  'desc_display': 'ஒளிர், இருள், தானியங்கு',
  'desc_language': 'தமிழ், ஆங்கிலம், தானியங்கு',
  'desc_security': 'தேக்ககத்தை அழி, கணக்கு பாதுகாப்பு',
  'desc_about': 'எல்வன் பற்றி மேலும் அறிக',
  'logout_desc': 'பயன்பாட்டிலிருந்து வெளியேறவும்.',
  'erase_data': 'செயலித் தரவை அழி',
  'erase_data_desc': 'தரவுகளை நிரந்தரமாக அழிக்கவும்.',
  'primary_language': 'முதன்மை மொழி',
  'secondary_language': 'இரண்டாம் மொழி',
  'bilingual_entry': 'இருமொழி முறை',
  'system_auto': 'தானியங்கி அமைப்பு',
  'wideLogoLabel': 'செங்குத்து / அகலமான சின்னம்',
  'billHeaderStyle': 'சின்னத்தின் வடிவம்',
  'smallLogoBusinessName': 'சிறிய சின்னம் + பெயர்',
  'wideLogoOnly': 'அகலமான சின்னம் மட்டும்',
  'upload': 'பதிவேற்று',
};
