// Contains data for Indian States, Tamil Nadu Districts, and Countries for auto-fill

const List<Map<String, String>> silkTamilNaduDistricts = [
  {"en": "Ariyalur", "ta": "அரியலூர்"},
  {"en": "Chengalpattu", "ta": "செங்கல்பட்டு"},
  {"en": "Chennai", "ta": "சென்னை"},
  {"en": "Coimbatore", "ta": "கோயம்புத்தூர்"},
  {"en": "Cuddalore", "ta": "கடலூர்"},
  {"en": "Dharmapuri", "ta": "தருமபுரி"},
  {"en": "Dindigul", "ta": "திண்டுக்கல்"},
  {"en": "Erode", "ta": "ஈரோடு"},
  {"en": "Kallakurichi", "ta": "கள்ளக்குறிச்சி"},
  {"en": "Kanchipuram", "ta": "காஞ்சிபுரம்"},
  {"en": "Kanyakumari", "ta": "கன்னியாகுமரி"},
  {"en": "Karur", "ta": "கரூர்"},
  {"en": "Krishnagiri", "ta": "கிருஷ்ணகிரி"},
  {"en": "Madurai", "ta": "மதுரை"},
  {"en": "Mayiladuthurai", "ta": "மயிலாடுதுறை"},
  {"en": "Nagapattinam", "ta": "நாகப்பட்டினம்"},
  {"en": "Namakkal", "ta": "நாமக்கல்"},
  {"en": "Nilgiris", "ta": "நீலகிரி"},
  {"en": "Perambalur", "ta": "பெரம்பலூர்"},
  {"en": "Pudukkottai", "ta": "புதுக்கோட்டை"},
  {"en": "Ramanathapuram", "ta": "இராமநாதபுரம்"},
  {"en": "Ranipet", "ta": "இராணிப்பேட்டை"},
  {"en": "Salem", "ta": "சேலம்"},
  {"en": "Sivaganga", "ta": "சிவகங்கை"},
  {"en": "Tenkasi", "ta": "தென்காசி"},
  {"en": "Thanjavur", "ta": "தஞ்சாவூர்"},
  {"en": "Theni", "ta": "தேனி"},
  {"en": "Thoothukudi", "ta": "தூத்துக்குடி"},
  {"en": "Tiruchirappalli", "ta": "திருச்சிராப்பள்ளி"},
  {"en": "Tirunelveli", "ta": "திருநெல்வேலி"},
  {"en": "Tirupattur", "ta": "திருப்பத்தூர்"},
  {"en": "Tiruppur", "ta": "திருப்பூர்"},
  {"en": "Tiruvallur", "ta": "திருவள்ளூர்"},
  {"en": "Tiruvannamalai", "ta": "திருவண்ணாமலை"},
  {"en": "Tiruvarur", "ta": "திருவாரூர்"},
  {"en": "Vellore", "ta": "வேலூர்"},
  {"en": "Viluppuram", "ta": "விழுப்புரம்"},
  {"en": "Virudhunagar", "ta": "விருதுநகர்"}
];

const List<Map<String, String>> silkIndianStates = [
  {"en": "Andaman and Nicobar Islands", "ta": "அந்தமான் நிக்கோபார் தீவுகள்"},
  {"en": "Andhra Pradesh", "ta": "ஆந்திரப் பிரதேசம்"},
  {"en": "Arunachal Pradesh", "ta": "அருணாச்சலப் பிரதேசம்"},
  {"en": "Assam", "ta": "அஸ்ஸாம்"},
  {"en": "Bihar", "ta": "பீகார்"},
  {"en": "Chandigarh", "ta": "சண்டிகர்"},
  {"en": "Chhattisgarh", "ta": "சத்தீஸ்கர்"},
  {"en": "Dadra and Nagar Haveli and Daman and Diu", "ta": "தாத்ரா நகர் ஹவேலி மற்றும் டாமன் டையூ"},
  {"en": "Delhi", "ta": "டெல்லி"},
  {"en": "Goa", "ta": "கோவா"},
  {"en": "Gujarat", "ta": "குஜராத்"},
  {"en": "Haryana", "ta": "ஹரியானா"},
  {"en": "Himachal Pradesh", "ta": "இமாச்சலப் பிரதேசம்"},
  {"en": "Jammu and Kashmir", "ta": "ஜம்மு காஷ்மீர்"},
  {"en": "Jharkhand", "ta": "ஜார்க்கண்ட்"},
  {"en": "Karnataka", "ta": "கர்நாடகா"},
  {"en": "Kerala", "ta": "கேரளா"},
  {"en": "Ladakh", "ta": "லடாக்"},
  {"en": "Lakshadweep", "ta": "லட்சத்தீவு"},
  {"en": "Madhya Pradesh", "ta": "மத்தியப் பிரதேசம்"},
  {"en": "Maharashtra", "ta": "மகாராஷ்டிரா"},
  {"en": "Manipur", "ta": "மணிப்பூர்"},
  {"en": "Meghalaya", "ta": "மேகாலயா"},
  {"en": "Mizoram", "ta": "மிசோரம்"},
  {"en": "Nagaland", "ta": "நாகாலாந்து"},
  {"en": "Odisha", "ta": "ஒடிசா"},
  {"en": "Puducherry", "ta": "புதுச்சேரி"},
  {"en": "Punjab", "ta": "பஞ்சாப்"},
  {"en": "Rajasthan", "ta": "ராஜஸ்தான்"},
  {"en": "Sikkim", "ta": "சிக்கிம்"},
  {"en": "Tamil Nadu", "ta": "தமிழ்நாடு"},
  {"en": "Telangana", "ta": "தெலுங்கானா"},
  {"en": "Tripura", "ta": "திரிபுரா"},
  {"en": "Uttar Pradesh", "ta": "உத்தரப் பிரதேசம்"},
  {"en": "Uttarakhand", "ta": "உத்தராகண்ட்"},
  {"en": "West Bengal", "ta": "மேற்கு வங்கம்"}
];

const List<Map<String, String>> silkCountries = [
  {"en": "Australia", "ta": "ஆஸ்திரேலியா"},
  {"en": "Bangladesh", "ta": "வங்காளதேசம்"},
  {"en": "Canada", "ta": "கனடா"},
  {"en": "France", "ta": "பிரான்ஸ்"},
  {"en": "Germany", "ta": "ஜெர்மனி"},
  {"en": "India", "ta": "இந்தியா"},
  {"en": "Indonesia", "ta": "இந்தோனேஷியா"},
  {"en": "Kenya", "ta": "கென்யா"},
  {"en": "Malaysia", "ta": "மலேசியா"},
  {"en": "Nepal", "ta": "நேபாளம்"},
  {"en": "Netherlands", "ta": "நெதர்லாந்து"},
  {"en": "New Zealand", "ta": "நியூசிலாந்து"},
  {"en": "Nigeria", "ta": "நைஜீரியா"},
  {"en": "Pakistan", "ta": "பாகிஸ்தான்"},
  {"en": "Philippines", "ta": "பிலிப்பைன்ஸ்"},
  {"en": "Saudi Arabia", "ta": "சவுதி அரேபியா"},
  {"en": "Singapore", "ta": "சிங்கப்பூர்"},
  {"en": "South Africa", "ta": "தென்னாப்பிரிக்கா"},
  {"en": "Sri Lanka", "ta": "இலங்கை"},
  {"en": "United Arab Emirates", "ta": "ஐக்கிய அரபு அமீரகம்"},
  {"en": "United Kingdom", "ta": "ஐக்கிய இராச்சியம்"},
  {"en": "United States", "ta": "அமெரிக்கா"},
];
